end-of-first-life commit

diff --git a/eso/ubin-local/brushupon b/eso/ubin-local/brushupon
--- a/eso/ubin-local/brushupon
+++ b/eso/ubin-local/brushupon
@@ -30,6 +30,11 @@
 #           by using this flag. This flag will work for any language and may be easier for some especially new to
 #           the suffixes used by the languages as the second form can be confusing. Again at this time, this file
 #			is considered 'private' but is only released on pastebin semi-anonymously!
+# --nocache disable locally saved off-line versions of the webpages - has no effect when page is never been cached
+#			this does NOT prevent the file from being cached (to allow a up-to-date offline mode without needing to
+#			go back and forth with this switch.
+# --list	show all cached items one per line
+#
 #
 # examples(that work*): 
 #
@@ -58,6 +63,15 @@
 # see my git page for updates related to my stuff: https://osirisgothra.github.io
 #
 # this file is from: http://paste.ubuntu.com/26233733/
+[[ $1 == --nocache ]] && { cache=no; shift; } || cache=yes
+#shopt -o -s extdebug
+shopt -s xpg_echo
+shopt -s expand_aliases
+shopt -s globstar
+shopt -s interactive_comments
+fcache="$HOME/.cache/brushupon/"
+fitem="$1"
+mkdir --parents "$fcache" || echo "warning: cache could not be created on device under $HOME" --verbose
 
 RAWMODE=0
 if [[ $* =~ --help ]]; then
@@ -69,6 +83,25 @@ elif [[ $1 == -raw ]]; then
 	echo "disabling colorme support (if it was available)" > /dev/stderr
 	RAWMODE=1
 	shift
+	# (see *??)
+	echo ""
+elif [[ $1 =~ --list ]]; then
+	printf "filename\t\tfull path\n\n"
+	r=0
+	for x in ~/.cache/brushupon/*; do
+		if [[ -s "$x" ]]; then
+			echo "$(basename $x)\t\t\t$x"
+		else
+			echo "\twarning: found zero-length file, removing it..."
+			echo "\t$x - empty"
+			rm "$x" -f --verbose
+		fi
+		let r++
+	done
+	echo ""
+	echo "total $r"
+	echo ""
+	exit 122
 fi
 
 case $# in
@@ -97,7 +130,6 @@ elif [[ $NMISS -gt 0 ]]; then
 	echo "warning: some addons not available, support may be limited (but still functional)"
 fi
 
-
 if [[ $1 == -n ]]; then
 	shift
 	PFX="https://learnxinyminutes.com/docs/$1"
@@ -109,9 +141,45 @@ else
 	DOT="."
 	XLAT=cat
 fi
+alias unless="if !"
+alias sselnu="fi"
+alias elunless="elif"
+tgt="${fcache}${fitem}"
 
-if [[ $RAWMODE == 0 ]] && which colorme; then
-	GET "$PFX$1$DOT$2" | $XLAT | colorme | less -raw
+unless [[ -r "$tgt" && -f "$tgt" ]]; then
+	tgt="$(mktemp)"
+	cache=no
+sselnu
+if [[ $cache == no ]]; then
+	if [[ $RAWMODE == 0 ]] && which colorme; then
+		GET "$PFX$1$DOT$2" | $XLAT | colorme > "$tgt"
+	else
+		GET "$PFX$1$DOT$2" | $XLAT > "$tgt"
+	fi
 else
-	GET "$PFX$1$DOT$2" | $XLAT | less -raw
+	echo "using cache in $tgt"
 fi
+
+if [[ $(cat "$tgt") =~ "404 Not Found" ]]; then
+	echo "Error, page seems to be missing! (404: Page Not Found)"
+	exit 404
+elif [[ $(cat "$tgt" | wc -l) -lt 1 ]]; then
+	echo "Error, page retrieved was empty (possibly domain not found or unable to connect)"
+	exit 400
+else
+	less -raw "$tgt"
+	if [[ $cache == yes ]]; then
+		echo "skipping save to cache and tempfile"
+	else
+		if mv --force "$tgt" "${fcache}${fitem}"; then
+			R=$?
+			echo "saved to cache in ${fcache}${fitem}."
+		else
+			R=$?
+			echo "warn: cannot save to cache ($?)!"
+		fi
+	fi
+fi
+[[ -v R ]] || R=$?
+echo "script actions all finished ($R)"
+exit $R
diff --git a/eso/ubin-local/kaffeine b/eso/ubin-local/kaffeine
--- a/eso/ubin-local/kaffeine
+++ b/eso/ubin-local/kaffeine
@@ -1,4 +1,41 @@
 #!/bin/bash
-TARGETNAME=$0
-# disables compton when mplayer starts then re-enables it upon exit
-[[ -x /usr/bin/$TARGETNAME ]] && /usr/bin/$(basename $TARGETNAME) || echo "/usr/bin/$(basename $TARGETNAME) does not exist!"
+shopt -s interactive_comments
+
+if [[ $- =~ i ]]
+then
+	echo "fail: must not be run interactive!"
+	return 127
+	exit 127	# safeguard for corrupt scripts
+fi
+
+TARGET="$0"
+
+if [[ $TARGET =~ / ]]
+then
+	echo "trimming $TARGETNAME because it contained a path character...[s"
+	TARGETNAME="$(basename $TARGET)"
+	echo "[u$TARGETNAME"
+else
+	TARGETNAME="$TARGET"
+fi
+echo "target comm: $TARGET"
+echo "target name: $TARGETNAME"
+IFS=":"
+for _dir in $PATH
+do
+	[[ ${_dir: -1:1} != '/' ]] && _dir+='/'		# add a '/' if it doesnt end in on (useful for '/', '..', and '.')
+	dest="${_dir}$TARGETNAME"
+	echo "looking in $_dir for ${TARGETNAME}...[s"
+	if [[ -x "$dest" ]]
+	then
+		if diff "$dest" "$BASH_SOURCE"; then
+			echo "[uskip (is THIS script!!)"
+		else
+			echo "found $dest -- executing it with args=${@-<no arguments given>}"
+			[[ $# -gt 0 ]] && exec "$dest" "$@" || exec "$dest"		# prevents an empty argument from being sent
+		fi
+	else
+		echo "[ufailed\n"
+	fi
+done
+unset IFS
diff --git a/eso/ubin-local/rea b/eso/ubin-local/rea
--- a/eso/ubin-local/rea
+++ b/eso/ubin-local/rea
@@ -1,29 +1,134 @@
 #!/bin/bash
-function n()
-{
-	case $# in
-		2)
-			echo -e "\e[33;1msingle-shot for: \e[34;1m$1 \e[0mwith priority of\e[34;1m $2 \e[0m"
-			~/bin/ionice "$@"
-			;;
-		*)
-			echo "multi-shot not supported: org: $@"
-			exit 122
-			;;
-	esac
-}
-for i in {1..7}; do
-	for j in R B; do
-		#echo "generating function ${j}${i} ..."
-		eval 'function '${j}${i}'() {	for x; do echo -e "\e[33;1mmulti-shot for: \e[34;1m$x \e[0mwith priority of \e[34;1m${FUNCNAME}\e[0m"; ~/bin/ionice "$x" '${j}${i}';	done; }'
+#
+#    rea
+#    try (to) [r]enice [e]xtra [a]synchronous threads 
+#    eso project
+#    eso-bin on github/osirisgothra
+#
+#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all of my projects can be
+#    obtained by visiting the repository: 
+#
+#    <https://github.com/osirisgothra>
+#
+#    Because of the global availability of github at this point, hosting
+#    any additional servers for public use no longer serves a purpose. All
+#    content is available 24/7 through github. (Thanks to GITHUB!).
+#
+#    NOTE FROM THE AUTHOR
+#
+#    If the world ends and apes and monkeys start dating rattlesnakes, 
+#    I might consider bringing local servers back on. However, it is quite
+#    unlikely to have access to them, beyond having them hosted out of IRC
+#    or some doesnt-exist-without-paying-for-it domain name. See my network
+#    status page at larnica.whyfi.??? (??? is subject to change) for
+#    information, if it is available, when it is available.
+#
+#    LICENSE
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#    HISTORY
+#
+#    File's history is listed top-down as newest-oldest
+#
+#    Sun Aug 12 22:08:14 EDT 2018
+#		this header was created using the template generator 
+#		by Gabriel T. Sharp <osirisgothra@hotmail.com>.
+#		added support to include threads
+#
+#    Wed Apr 12 10:05:13 EST 2018
+#		osirisgothra@larnica initially created this file
+#		with the original name, rea
+#
+#
+#	 FUN FACT
+#
+#	  This program's name could have been 'treat' but since
+#     it already existed, the author was forced to go with the name
+#	  'rea' which was actually the former name of the merged program
+#     that USED to be ran in place of this program. The old 'rea' program
+#     was called that because it set all applicable processes to 'realtime'
+#     priority and used ionice exclusively. This program does not use
+#     ionice nor set realtime priorities, just nice values. However, the
+#     name was repurposed to fit the new, more system-friendly version of
+#     the eso project.
+#
 
+# these are written in this form:
+#    [process]="nice"
+# where:
+#    process	the BASENAME of the process, excluding it's full path (see EXAMPLES)
+#    nice		a numeric integer value between -19 and 19, values greater than 19 will be set to 19, less than -19 will be set to -19
+# EXAMPLES
+#
+#    [zsh]="-4"		sets all processes with the name 'zsh' (including all threads) to the nice value of -4
+#    [bash]="-1"	sets all bash shells running right now to a -1 nice value
+#
+# LANGUAGE NOTES
+#
+#    * the bash language requires [] in the process names in the list below for the hash values, they must be included
+#    * these values must remain on one line unless $IFS is set to $'\n', then the lines could be broken (use at own risk!)
+
+
+
+declare -A PROC_NAMES=( [java]="-17" [X]="-15" [perl]="-4" [i3bar]="5" [play]="-16" [Xorg]="-10" [dbus-daemon]="-12" [xinit]="-10" [startx]="5" [bash]="-5" [sh]="-2" [ssh]="12" [gvsd-fuse]="-17" [gvsd]="-12" [init]="-17" [htop]="-5" [nano]="4" )
+
+for x in "${!PROC_NAMES[@]}"; do
+	PROC_PRI="${PROC_NAMES[$x]}"
+	echo "threads for: $x (new priority: ${PROC_PRI})..."
+	echo "[s"
+	for y in `ps -L -C "$x" -o tid=`; do
+		echo -ne "[u$$: ${x}:${y} setting (to $PROC_PRI).. ("
+		sudo -H renice  -n "$PROC_PRI" -p "$y" | tr -d '\n'
+		#	echo "[32;1mok[0m"
+		#else
+		#	echo "[31;1mfailed(return=$?)[0m"
+		#fi
+		echo ")"
 	done
 done
-#declare -pf
+echo "renice-ing extra asynchronous processes completed"
 
-n java R1
-n X R0
-#n pulseaudio R3
-#n mocp R3
-R3 pulseaudio mocp
+
+#function n()
+#{
+#	case $# in
+#3		2)
+#3			echo -e "\e[33;1msingle-shot for: \e[34;1m$1 \e[0mwith priority of\e[34;1m $2 \e[0m"
+#			~/bin/ionice "$@"
+#			;;
+#		*)
+#			echo "multi-shot not supported: org: $@"
+#			exit 122
+#			;;
+#	esac
+#}
+#for i in {1..7}; do
+#	for j in R B; do
+#		#echo "generating function ${j}${i} ..."
+#		eval 'function '${j}${i}'() {	for x; do echo -e "\e[33;1mmulti-shot for: \e[34;1m$x \e[0mwith priority of \e[34;1m${FUNCNAME}\e[0m"; ~/bin/ionice "$x" '${j}${i}';	done; }'
+#
+#	done
+#done
+##declare -pf
+
+#n java B4
+#n X B4
+#n pulseaudio B4
+#n mocp B4
 
diff --git a/eso/ubin-local/stopservices b/eso/ubin-local/stopservices
--- a/eso/ubin-local/stopservices
+++ b/eso/ubin-local/stopservices
@@ -9,14 +9,7 @@
 # f.attr.taintprotect.bydemecration
 service()
 {
-	echo -ne "[0;32;2mStopping service [0;32;1m${1}..."
-	## BEGIN:(TAINT-PROTECT)
-	if command time sudo -H /usr/sbin/service "$@"; then
-	## END:(TAINT-PROTECT)
-		echo "[1mOK[0m"
-	else
-		echo "[1;31mFAILED[0m"
-	fi
+	sudo command service "$@" && echo "ok" || echo "fail"
 }
 # f.attr.reset	
 
@@ -37,3 +30,5 @@ service speech-dispatcher stop
 service irqbalance stop
 service ufw stop
 service cups-browsed stop
+sudo killall -KILL apache2
+sudo killall -KILL gnome-settings-daemon
