end-of-feb2021 esoterics update from offline master tree -- introduced the CSCS2020 programming standards

diff --git a/eso/ubin-local/colors b/eso/ubin-local/colors
--- a/eso/ubin-local/colors
+++ b/eso/ubin-local/colors
@@ -182,6 +182,54 @@ zmodload zsh/termcap
 zmodload zsh/terminfo
 
 
+declare -g entrypwd="$PWD"
+echo "entrypwd=$entrypwd"
+# can delete any time, if its still in use, the kernel will keep
+# our tempfile open for us and remove it for real once the last handle is
+# closed or the refcount is zero. If someone deletes it before we are done
+# with it, the same. We however, can remove it in cleanup (preferred)
+# which will be hanleded on those signals listed below
+declare -g tmpfile="$(mktemp minicolorsdataXXXXXXXXXXXXXXXX.temp-data-safe-to-delete-me)"
+
+# signal table, add signals you want cleanup to happen for
+# (dont add SIGCHLD or RETURN!!!! EXIT is preferred! and KILL usually wont be trappable)
+# without EXIT cleanup could possibly not happen at all, so it should not
+# be omitted. Many other signals would cause cleanup to be done prematurely
+# (mainly, SIGCHLD, DEBUG, STOP, TTIN, TTOU, TSTP, STOP, CONT, VTALRM, PIPE)
+# other critcal exit signals are probably ok but should only be used if they
+# have a need to be used, otherwise leave them out. I have included just
+# the signals that are ordinarily encounted that would require cleanup to
+# happen (EXIT at program exit, HUP when shell and/or session disconnects,
+# INT when user or system interrupts [by using CTRL+C or sysrq commands
+# or xterm menu to send sigint], QUIT (end-of-file CTRL+D or task manager or system requesting a
+# program to quit, or, user terminated host program).
+# why we dont use: STOP/CONT/TTSTP/TTIN/TTOU-when ctrl+z is pressed, happens in the middle of a run and does not temrinate the program
+#
+# possible valid signals are:
+# ABRT CONT INT  PROF  STKFLT TRAP URG  WINCH
+# ALRM FPE  KILL PWR   STOP   TSTP USR1 XCPU EXIT DEBUG SEGV TERM TTOU
+# BUS  HUP  PIPE QUIT  SYS    TTIN USR2 XFSZ CHLD ILL   POLL TTOU VTALRM
+declare -ga cleanup_signals=( EXIT
+                              HUP
+                              INT
+                              KILL
+                              QUIT
+                             )
+
+# cleanup (set it up)
+cleanup()
+{   echo "cleaning up..."
+    rm $tmpfile -f &> /dev/null && echo "removed $tmpfile ok" || echo "warning: error while removing $tmpfile"    
+    chdir $entrypwd && echo "returned to $entrypwd ok" || echo "warning: error while returning to $entrypwd"
+    xtitle "$entrypwd" && echo "restored xtitle ok" || echo "warning: xtitle returned with an error"
+    echo "cleanup done"
+}
+trap cleanup $cleanup_signals
+
+
+# cleanup
+
+
 case $1 in
     hi)
         exec 1>&4
@@ -248,6 +296,7 @@ case $1 in
 				echo "..Terminal Too Small, Need 20x9 at least!\nResize Your Terminal or CTRL-C to exit, if this is a console terminal you will need to use setfont(1) to change the size!..."
 			else
 				apptitle="Color Sequence Explorer v0.1-extreme-alpha by Gabriel Sharp <osirisgothra@hotmail.com>"
+				
 				[[ -n $DISPLAY ]] && xtitle "$apptitle"
 				adjmsg="adjust keys: (modifier: [Shift]=10 [None]=1) start[q/a]=$a end[w/s]=$b interval[e/d]=$c blockwidth[r/f]=$d spacing[t/g]=$e firstofs[y/h]=$f mode[u/j]=$g"
 				echo -ne "[40;37;0m[2J"
diff --git a/eso/ubin-local/dlgi b/eso/ubin-local/dlgi
--- a/eso/ubin-local/dlgi
+++ b/eso/ubin-local/dlgi
@@ -1,36 +1,352 @@
 #!/bin/zsh
 #
-# dlgi
+#    dlgi
+#    download google searched-for images
+#    mini
+#    eso-ubin-local
 #
-setopt aliases
+#    Copyright (C) 1995-2021 Gabriel T. Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all projects can be
+#    obtained by visiting the repository at:
+#
+#    <https://github.com/osirisgothra>
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#    HISTORY
+#
+#	 Sun 10 Jan 2021 03:42:28 PM EST
+#            osirisgothra@ initially created this file
+#            with the original name, dlgi
+#
+#
+#
+#  This template and header was created using the template generator by Gabriel T. Sharp
+#  You can download the latest version at: <https://www.github.com/osirisgothra/mini.git/eso/ubin-local/template>
+#  (the url is subject to changes on github's behalf, please submit a pull request to fix or request a fix on any url changes)
+#
 
-function htmlfilters()
-{
-    sed 's/</\n</g' |
-    grep '<img' |
-    head -n"$count" |
-    tail -n1 |
-    sed 's/.*src="\([^"]*\)".*/\1/'
+
+# Get Options from Command Line for dlgi
+
+declare -gi scales=0
+declare -gi restmode=0
+declare -g place_items="$PWD/downloaded"
+declare -ga opts
+declare -gi quiet_level=0
+declare -g version_text="$(tput setaf 124)dlgi$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
+declare -g getmode='disabled'
+declare -g viewmode=1
+declare -g help_text="dlgi
+download google searched-for images
+
+SYNTAX
+
+	dlgi [OPTIONS] SEARCHTERMS START
+
+OPTIONS
+   --names -n           automatically name the subdirectory (under downloaded) to place each search set into
+  --scales -C           automatically rescale the images to 64x64 argb portable network compressed graphic (now is  semi-implemented)
+	--help -h	        show this help text
+     --yes -y           do not prompt for accept, just accept it automatically
+ --version -v           display version information and exit (also shows license info)
+   --quiet -q           increase quiet level by one (quiet level is always zero if left alone)
+     --get -g NUMBER    use get mode, just get <NUMBER> of matches from starting point and download them
+    --view -w           view mode, use display after getting images (for -g only)
+ --no-view -W          reverses effects of --view, or, causes regular viewing to be disabled (not too useful without -g)
+
+ARGUMENTS
+
+    START       A NUMBER that specifies the index in which to start showing google results, defaults to a random NUMBER
+    SEARCHTERMS A STRING in this syntax: \"separate+matches+anywhere+matches that must be consecutive\" as it works in google search.
+
+	FILENAME	A filename that must exist or be writable by the current user.
+	PATHNAME	A relative or absolute path that must exist or be creatable.
+	STRING		A readable string, it must not contain any unreprintable characters.
+	NUMBER		An integer, usually between -32767 and 32767.
+	BOOLEAN		A true/false value, represented as 0 for false, and any other value for true.
+	FLOAT		A floating point single or double precision value, it is precise down to about 5 ot 6 decimal places.
+	ENG			Scientific notation, expressed in powers (3x10^4 is written as 3.4)
+	DEG			Like GRAD/RAD, but expressed in degrees (hours, minutes, seconds) so 3 5'5\" is written as \"3.5.5\"
+
+
+LICENSE
+
+	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
+
+"
+lecho() { builtin echo "$@"; }
+
+echo() {
+	if [[ $quiet_level -gt 0 ]]; then
+		return 127
+	else
+		builtin echo "$@"
+	fi
 }
 
+is() {
+    case $1 in
+        quiet)  ((quiet_level > 0));;
+      verbose)  ((quiet_level < 0));;
+       normal)  ((quiet_level == 0));;
+     notquiet)  ((quiet_level <= 0));;
+            *)  ((quiet_level == 1));;
+    esac
+}
+fail()
+{
+    echo "failed: $1"
+    exit $2
+}
 
-declare -gi hilimit=890
+if opts=( `getopt -n $0 -o g:WwnhvqyVCN -l get:,yes,names,no-view,verbose,help,version,quiet,scales -- "$@"` ); then
+	eval set -- "${opts[@]}"
+	echo "cmdline is: $@"
+	while [[ $# -ge 0 ]]; do
+		curopt=$1
+		nextopt=${2-none}
+		echo "$curpot -- $nextopt"
+		shift
+		# handle --options and -o ptions here
+		case $curopt in
+			--no-view|-W) let viewmode--;;
+		    --yes|-y) let restmode=1;;
+			--help|-h)	echo "$help_text"; exit 127;;
+			--version|-v) echo "$version_text"; exit 127;;
+            --verbose|-V) let quiet_level--;;
+			--quiet|-q) let quiet_level++;;
+			--names|-n) autoname=1;;
+			--view|-w) let viewmode++;;
+			--scales|-C) scales=1;;
+			--get|-g)
+			        if [[ $nextopt =~ '[0-9]+' ]]; then
+			            getmode=$nextopt
+			            shift
+			        else
+			            getmode=10
+			            echo "getmode is 10 (nextarg was $nextopt)"
+			        fi
+			        echo "getmode set to $getmode"
+			;;
+			--no|-N) let restmode=0;;
+			--) is verbose && echo "done with options";  break;;
+			*)	is verbose && echo "handling option: $curopt (next:$nextopt)";;
+		esac
+	done
+	echo "final config:"
+	echo "      scales=$scales"
+	echo "    restmode=$restmode"
+	echo "    viewmode=$viewmode"
+	echo " quiet_level=$quiet_level"
+	echo "    autoname=$autoname"
+	for arg; do
+		# verify/handle non-option arguments
+		case $arg in
+			*)	is verbose && echo "handling argument: $arg";;
+		esac
+	done
+
+else
+	is notquiet && echo "error, code is $?, exiting with fail"
+	exit 127
+fi
+
+
+tshortest()
+{
+  shortest=$1; for x; do if [[ $#x -lt $#shortest ]]; then shortest=$x;  fi; done; echo $shortest;
+}
+hrule()
+{
+    if [[ "$COLUMNS" == "" ]]; then
+        if [[ $TERM == linux ]]; then
+            export COLUMNS=80
+        elif [[ -n $DISPLAY ]]; then
+            eval `resize`
+        else
+            COLUMNS=40
+        fi
+    fi
+    repeat ${COLUMNS-39} { printf "$sep_char" }
+}
+vrule()
+{
+    if [[ "$LINES" == "" ]]; then
+        if [[ $TERM == linux ]]; then
+            export LINES=80
+        elif [[ -n $DISPLAY ]]; then
+            eval `resize`
+        else
+            LINES=40
+        fi
+    fi
+    printf '[s'
+    repeat $(( ${LINES-39} - 1 )) { printf "[1D[1B$sep_charv" }
+    printf '[u'
+}
+
+declare -g disp_prog="display-im6"
+declare -g ttyc_prog="tycat"
+declare -g ident_prog="identify-im6"
+declare -g sep_char="-" sep_charv="|"
+
+if [[ $(</proc/${$(</proc/$PPID/stat)[4]}/comm) == "terminology" ]]; then
+    declare -g disp="${ttyc_prog:c}"
+else
+    declare -g disp="${disp_prog:c}"
+fi
+declare -g ident="${ident_prog:c}"
+
+[[ -x $ident ]] || fail "cannot locate required dependency: $ident_prog"
+[[ -x $disp ]] || fail "cannot locate required dependency: $disp_prog"
+
+echo "dlgi: argsleft=$@"
+
+mkdir --parents "$place_items" || fail "cannot create $place_items which is required for it to run" 128
+
+zmodload zsh/mathfunc
+echo -n "pre-seeding randomizer...."
+randomseed=$(date +%N)
+echo "set to $randomseed"
+function htmlfilters() {
+    grep -Po '\<img [^\>]+\>' | sed -n 2p | grep -Po '(?<=src=")[^"]+'
+}
+
+declare -gi imgno
+declare -gi hilimit=500
 declare -gi lolimit=1
 for a b; do
+    echo "a=$a b=$b"
+    if ((autoname)); then
+        declare -g aplace_items="$place_items/${a//[[:punct:]]/}"
+        if mkdir --parents "$aplace_items"; then
+            echo "using $aplace_items for this group"
+        else
+            echo "couldnt write $aplace_items failing back to $place_items"
+            aplace_items="$place_items"
+        fi
+    else
+        declare -g aplace_items="$place_items"
+    fi
+
     reqtxt="${a?missing a search parameter (must be in single argument)}"
     imgno="${b?missing the count, it should be the second argument}"
     if [[ $imgno -lt $lolimit ]]; then
-        echo "count is below low limit, it must be $lolimit"
-        exit 127
+        echo -n "count is below low limit, assuming random..."
+        # avoid overlimit (hilimit-1), avoid 0 (+ 1)
+        imgno=$(( ceil(rand48(randomseed) * (hilimit-1) ) + 1 ))
+        echo "set to $imgno"
+        # should assert imgno again but this program isnt important enough
     elif [[ $imgno -gt $hilimit ]]; then
         echo "count exceeds high limit, google will surely complain (current limit is set to $hilimit items)"
         exit 127
     fi
-    echo "about to make query, \n\timage req: $reqtxt   \n\tpage=$page \n\tcount=$count \n\timgno=$imgno"
-    isrc=$(wget -qU 'Mozilla/5.0' -O /dev/stdout "www.google.com/search?q=${reqtxt}\&tbm=isch&start=$imgno" | htmlfilters)
-    idest="dlgi-${isrc##*/}"
-    wget -qO "$idest" "$isrc"
-    display "$idest"
+    if ((getmode > 0)); then
+        # GET MODE (uses -W or -w)
+        echo "getmode is $getmode, proceeding with mass downloader"
+        for ((i=0;i<getmode;i++)); do
+            ofs=$(( imgno + i ))
+            declare -g url='www.google.com/search?q='"${reqtxt// /+}"'&tbm=isch&start='"$ofs"
+            isrc=$(wget -qU 'Mozilla/5.0' -O /dev/stdout "$url"  | htmlfilters )
+            ext=${isrc##*\.}
+            ext=${ext//[[:punct:]]/}
+            if [[ $#ext -gt 4 ]]; then
+                ext="${ext: -4}"
+            fi
+            idest="$aplace_items/${RANDOM}"
+            wget -qO "$idest" "$isrc" &> /dev/null
+            ext=$( tshortest ${(s:/:)$(file --extension $idest -b)} )
+            inewdest="${idest}.${ext}"
+            mv "$idest" "$inewdest"
+            hrule
+            if (( viewmode >= 1 )); then
+                $disp $inewdest
+            fi
+            $ident $inewdest
+
+            if ((restmode != 1)); then            
+                echo -ne "[a (default) = ACCEPT IMAGE] [V = ACCEPT THIS AND REST OF IMAGES] [x = REJECT IMAGE]: "
+                read -sk1
+                if [[ $REPLY == "x" ]]; then
+                    echo "REVOKING IMAGE"
+                    rm -f "$inewdest"
+                elif [[ $REPLY =~ '[vV]' ]]; then
+                    restmode=1
+                else
+                    echo "ACCEPTED"
+                fi
+            fi
+            if (( scales == 1 )); then
+                echo "converting to 64x64"
+                if convert-im6 -adaptive-resize 64x64 "$inewdest" "$inewdest"; then
+                    echo "converted ok"
+                else
+                    echo "conversion error($?)"
+                fi
+            else
+                echo "no conversion was requested, keeping resolution (scales=$scales)"
+            fi
+            chmod u=rwx,g=rw,o=r $inewdest
+            chown $UID:$GID $inewdest
+            echo "finished"
+        done
+    else
+        # VIEW ONLY MODE (implies -w)
+        declare -g url='www.google.com/search?q='"${reqtxt// /+}"'&tbm=isch&start='"$imgno"
+
+        echo "about to make query, \n\timage reqstr: $reqtxt   \n\timgno=$imgno\n\turl=\"$url\""
+        if [[ $needs_confirm == 1 ]]; then
+                echo "press ENTER to confirm, or Q to stop (or A to abort altogether)"
+                read -sk1
+                if [[ $REPLY =~ '[Qq]' ]]; then
+                    echo "aborted this item by user..."
+                elif [[ $REPLY =~ '[aA]' ]]; then
+                    echo "aborted entire run, exiting now..."
+                    exit 127
+                fi
+        fi
+        isrc=$(wget -qU 'Mozilla/5.0' -O /dev/stdout "$url"  | htmlfilters )
+        idest="dlgi.image"
+    #    echo "got isrc: $isrc"
+    #    echo "got idest: $idest"
+        #read -sn1
+        wget -qO "$idest" "$isrc" &> /dev/null
+        # dont identify unless nonempty file
+        if [[ -s $idest ]] && $ident "$idest"; then
+            display "$idest" || echo "skip view because viewmode is $viewmode"
+        else
+            echo "cannot show $idest because it does not refer to an image"
+        fi
+    fi
 done
 
 
+
+
+# programmer NOTES:
+# function htmlfilters():
+    # some variations, stack exchange suggestions, etc, that were modified heavily by me:
+    # these are fine for the old way, but the new way doesnt work in terms of pages, instead
+    # they are referred to in terms of a starting match (you can discern the page number which is dynamic depending on the
+    # users results-per-page preference, which varies greatly and should not be assumed)
+    #sed -r 's/</\n</g' | grep -i '<img' | head -n${1} | tail -n1 | sed -r 's/.*src="([^"]*)".*/\1/g'
+    #grep -Poi '\<img[^\>]+' | sed -n ${1}p | grep -Poi '(?<=src=")[^"]+'
+    #NB: dont mistake the grabbing of line 2 in sed (2p), the image number is decided from the start= in url,
+    #    therefore we never need to actually parse anything but the second image result (the first is the google logo)
+    #    warning: this could change if google modifies their plain text pages (they dont do this often, most people use the modern device and https pages
+    #    limitations: only thumbnails can be retrieved this way, but this program is meant for just that anyhow so (small sized textures is what i use it for)
diff --git a/eso/ubin-local/perlfunc b/eso/ubin-local/perlfunc
--- a/eso/ubin-local/perlfunc
+++ b/eso/ubin-local/perlfunc
@@ -1,2 +1,220 @@
 #!/bin/zsh
-exec perldoc -f "$@"
+#
+#   perldoc-deduction-frontend
+#
+#   recognizes the following symbolic links to iteself as:
+#
+#   perlapi     perlwhere       rawpod      perlfunc        pa      pw
+#   perlvar     perlfaq         perlmod     rp              plv     pf
+#   perlfunc    pa              pw          pml             faq                  (see #2)
+#
+#    mini/eso
+#    small projects and stand-alone programs or documents, esoteric or dependant
+#
+#    Copyright (C) 1995-2021 Gabriel T. Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all projects can be
+#    obtained by visiting the repository at:
+#
+#    <https://github.com/osirisgothra>
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#   WARNING: NOT RESPONSIBLE FOR LOSS/DAMAGE TO SELF OR OTHERS AS A RESULT OF USING THIS PROGRAM OR ANY OTHER PROGRAMS OF MINE
+#
+#    NOTES
+#
+#       All notes are #numbered, and are listed at the END OF THIS FILE ONLY
+#       comments are NOT permitted unless they cannot be described without
+#       being inside the source, which should not really ever happen much.
+#
+#    HISTORY
+#
+#	 Fri 26 Feb 2021 08:59:41 PM EST
+#            osirisgothra@ initially created this file
+#            with the original name, perldoc-deduction-frontend
+#
+#
+#
+#  This template and header was created using the template generator by Gabriel T. Sharp
+#  You can download the latest version at: <https://www.github.com/osirisgothra/mini.git/eso/ubin-local/template>
+#  (the url is subject to changes on github's behalf, please submit a pull request to fix or request a fix on any url changes)
+#
+#
+
+setopt interactivecomments
+
+declare -gi quietmode=1
+declare -gx prog=perldoc
+declare -ga flags=( )
+
+showhelp()
+{
+echo "
+    Runs perldoc in a way dependant on the symlink that called it
+    $1 [option] [topic-name]
+
+    Two arguments max, first argument may be an option, but the
+    topic-name MUST be included or the program wont run. The
+    option itself is optional, of course, and can be exactly
+    one of these:
+
+        --raw            show raw pod text
+        --ignore-case    turn off case sensitivity
+        --use-file       topic-name is a filename
+        --quiet          do not run in verbose mode (hide messages)
+        --makelinks      force creation of sublinks (is very dangerous--only do if you know what your doing)
+        --help           this text (or no arguments at all will show it too
+
+    Written by Gabriel T. Sharp on Fri 26 Feb 2021 09:30:31 PM EST
+    Last Updated Fri 26 Feb 2021 09:30:54 PM EST
+    See LICENSE for more details.
+"
+    exit $2
+}
+prepare()
+{
+    echo "$0 called with: $@"
+    true
+    # create any files, etc
+    # opposite of cleanup() <- remember to put its destruction in here
+    echo "$0 done"
+}
+cleanup()
+{
+    echo "$0 executed with: $@"
+    true
+    # so far -- no destructiveness to the system has been done, this could change
+    # use this function when needed to cleanup
+    echo "$0: done"
+}
+
+#######################
+# MAIN PROGRAM        #
+#######################
+
+# setup init, and setup automatic-any-cause-cleanup safely exits even when CTRL+C or break, etc                 #5
+
+prepare $? $0 ${0:t} $PWD $# $@ $PIPESTATUS
+trap "echo aborted ok; cleanup; exit 127" SIGINT SIGTERM SIGKILL SIGQUIT
+
+if [[ $# -eq 0 ]] || [[ $* =~ '--help' ]]; then
+    showhelp $0 0                                                                                                                   #3
+elif [[ $1 == --raw ]]; then
+    flags+=( -T )
+elif [[ $1 == --ignore-case || $1 == "-i" ]]; then
+    flags+=( -i )
+elif [[ $1 == --use-file || $1 == "-l" ]]; then
+    flags+=( -F )
+elif [[ $1 == --quiet || $1 == "-q" ]]; then
+    quietmode=1
+elif [[ $1 == --makelinks ]]; then
+    echo "started makelinks (in $PWD)"
+    shift
+    [[ -d $1 ]] && pushd $1
+    echo "preparing makelinks (in $PWD)"
+    declare -ga l=( perlapi perlwhere rawpod perlvar perlfaq perlmod perlfunc pa pw rp plv pf pml pfaq )
+    declare -gi lc=${#l[@]}
+    echo "about to make all $lc links in $PWD, press ENTER to start or CTRL+C to abort"
+    read -sk1
+    if [[ -w . ]]; then
+        for x in $l; do
+                if [[ -r $x ]]; then
+                    echo "$x exists, not overwriting OK"
+                else
+                    if ln -vs "$0" "$x"; then
+                        echo "$x created ok"
+                    else
+                        echo "error when creating $x"
+                    fi
+                    [[ -x $x ]] || echo "warning: $x not executable, you need to check it manually!" 
+                fi
+        done
+    fi
+    echo "about to finish (in $PWD)"
+    [[ -d $1 ]] && popd
+    echo "finished (in $PWD)"
+    exit 0
+elif [[ $1 == '^--' ]]; then
+    echo "$1: unknown option"
+    showhelp ${0:t} 2
+fi
+if [[ -n $flags ]]; then                                                                                    #1
+    shift
+fi
+if ((quietmode)); then
+    flags=( )
+else
+    flags+=( -D )                                                                                          #2
+fi
+if [[ $# -eq 0 ]]; then
+    echo "error: You supplied flags, but no viable legal topic name..."
+    showhelp ${0:t} 3
+elif [[ $# -gt 1 ]]; then
+    echo "error: You supplied too many ($#) names (one is the limit)"
+    showhelp ${0:t} 3
+fi
+echo "sourcelink: ${0:t}"
+case ${0:t} in
+    pa|perlapi) flags+=( -a );;
+    pw|perlwhere) flags+=( -l );;
+    rp|rawpod) flags+=( -u );;
+    plv|pv|perlvar) flags+=( -v );;
+    pfaq|perlfaq) flags+=( -q );;
+    pm|plm|perlmod) flags=( );;
+    pf|plf|pfunc|perlfunc) flags+=( -f );;
+    *) echo "warning: unknown source link name $0, failing back to perlfunc";  flags+=( -f );;
+esac
+# transferring control to perldoc from here on
+exec $prog $flags "$@"
+# maybe #4
+echo "fatal: $prog is either missing or un-executable by current user ($USER)"
+exit 4
+
+# comments
+#
+# #1   [ re: shift when true: -n $flags ]
+#       the only way content could have been added, is through a value
+#       within $1 -- so we need to remove the item here as its not needed anymore
+#       and we really cannot send it to perldoc(!)
+# #2   [ re: Naming of the file and its links (sym) ]
+#       This file should be linked to with the recommended names in the header
+#       given below all the other names. Use ln(1) for that;
+#
+#   'ln -s perldoc-deduction-frontend perlfunc' 
+#
+#    This would make the perlfunc command available, and so on..
+#
+#        Deduces what flags for perldoc to use, based on the link or name of this source file
+#        note that perldoc-deduction-frontend is decorative and isnt recommended to be used
+#        at all except at first, you'll probably want to name it something shorter to make
+#        the subsequent calls to ln(1) easier to deal with. (or if you love to type, keep it, doesnt really
+#        matter eitehr way, its decorative sugar--thats all).
+#    If you are real lazy, just use --makelinks, WARNING: this is not tested very much, and should be done
+#   with extreme caution to prevent overwriting of other files, you have been warned!! Not responsible for
+#   losses or damages as a result of using any of my programs.
+# #3    [ re: showhelp ]
+#   used to simplify if calls to help are needed later on
+#   the code will always exit with given, and the first argument passed is assumed to be
+#   the program's name -- done because $0 loses its value to the function name once inside a function
+#
+# #4
+#   dont bother showing help here because its not a bad command line-perldoc just isnt executable
+#
+# #5
+#   from this point on, the cleanup() will be triggered automatically no matter what the method of exiting is
+#   however this does not sheild against stuff like power outages, sudden unblockable kills by admins, and
+#   all the stuff that isnt supposed to be able to be caugh in the first place!
diff --git a/eso/ubin-local/template b/eso/ubin-local/template
--- a/eso/ubin-local/template
+++ b/eso/ubin-local/template
@@ -33,51 +33,96 @@
 #    with this program; if not, write to the Free Software Foundation, Inc.,
 #    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
+#    CODE COMMENTS
+#
+#       The 2020CSCS (2020 Columnal Strict Commenting Scheme), which includes
+
+#            The Author has verfied that the file adheres to the '2020 Columnized Strict Commenting Scheme' which is
+#            also known as the "2020/CSCS". This scheme requires that 1) all comments are in the form of footnotes
+#            with only a refnum in the far right column. This is in an effort to join the massive need for commenting
+#            your code reformation goin on all over the world, 2) footnotes are at the END of the file, beyond any
+#            executable code or other footnotes. Are easy to read and spot. 3) Do not count for more than 20% of the file's size.
+#            3-CODE Status: PASS PASS PASS (all 100%) A score of 80% or better is required to be 2020CSCS compliant.
+#
+#
+#
 #    HISTORY
 #
 #	 Sun Apr 22 12:22:01 EDT 2018
 #            osirisgothra@larnica initially added a template to this file
 #            with the original name, template*
 #  	 Sun 05 May 2019 11:09:39 AM EDT
+#            bugfixes in template names
+#    Sat 27 Feb 2021 10:44:22 AM EST
+#            modified code to adhere to my new '2020CSCS' annotation standards
 #
-#
-#  * this file has existed well before this date (2-3 years at least), but is A
-#    now documented as being truly created at this date and time
-#
-#  (this header was created using the template generator by Gabriel T. Sharp)
-#
-# DATE_TIME: not sure why you need to change this really but if you forgot or something, or are on
-#            a deadline or have a specific release date it could be useful.
-#
-# TODOs (ordered in MOST-IMPORTANT To least-important)
-#	#1 --- VERY ---> implement X integration to take values for $1 thru $6 since most
-#                    will probably have an X manager running that supports at the least
-#                    floating or stacked windows, decide on whether we should use one of:
-#                    kdialog, zenity, gnome-dialog (but not dialog because thats CUI).
-#                    (we cant use any CUI input methods because they interfere with CUI editors!)
-# TODOs that are DONE
-#	#2 ---  done--> possibly put template in a system or user binpath, possibly on eso??
-#   #3 --- done --> put into esoteric ubin for testing on github???
-#   #4 --- done --> add templates that the user can pick for other licenses or filetypes
+
+emulate zsh;
+setopt extendedglob
+setopt monitor
+setopt hashdirs
+
+if [[ "" ==  $TEMPLATE_AUTHOR_NAME_PERSISTENT ]]; then
+    declare -g AUTHOR_NAME="Gabriel T. Sharp:21shariria@gmail.com"
+else
+    declare -g AUTHOR_NAME="$TEMPLATE_AUTHOR_NAME_PERSISTENT"
+fi
+
+if [[ $AUTHOR_GITHUB == "" ]]; then
+    AUTHOR_GITHUB="osirisgothra"
+fi
 
 declare -g USE_TARGET_NOTES=0
-declare -ga opts
-if opts=( `getopt -n $0 -o hp -l help,profile-target -- $@` ); then
-    set -- $opts
+
+if [[ $DISPLAY == "" ]]; then
+    declare -g GUI_MODE=0
+else
+    if [[ $NEVER_USE_GUI == 1 ]]; then
+        declare -g GUI_MODE=0
+    else
+        declare -g GUI_MODE=1
+    fi
+fi
+
+if [[ $GUI_MODE == 1 ]]; then
+    if [[ $# == 0 ]]; then
+        F=`zenity --entry --text "Name of Script" --title "Name Request"`
+        D=`zenity --entry --text "Short Script Description" --title "Description Request"`
+        P=`zenity --entry --text "Name of Project (that this script belongs to)" --title "Project Name Request"`
+        d=`zenity --entry --text "Quick Project Description" --title "Quick Project Description Request"`
+        A=`zenity --entry --text "Your Name (The Author) (use Name:Email if you want that filled too)" --title "Author Name Request"`
+        s=`zenity --entry --text "Shell to use (in #!/bang first line, usually /bin/something)" --title "Shell Path Request"`
+        a=`zenity --entry --text "Date to use (leave blank for today + now)" --title "Date/Time Request"`
+        if [[ $a == "" ]]; then
+            a="$(date)"
+        fi
+        set -- "$F" "$D" "$P" "$d" "$s" "$a"
+        declare -g AUTHOR_NAME="$A"
+    fi
+fi
+
+
+if opts=`getopt -n $0 -o hp -l help,change-author,profile-target -- $@`; then
+    eval set -- $opts
     y=0; for x; do let y++
     {
         case $x in
             --) shift $y; break;;
-            -p|--profile) USE_TARGET_NOTES=1;;
+            --change-author)    AUTHOR_NAME="$(if [[ $TEMPLATE_AUTHOR_NAME != "" ]]; then echo $TEMPLATE_AUTHOR_NAME; else cat /etc/passwd|grep $UID:$UID | head -n1 | awk -F : '{ print $5 }' | awk -F , '{ print $1 }' || echo '<<failed get new authorname>>'; fi)";;
+            -p|--profile-target) USE_TARGET_NOTES=1;;
             -h|--help)  echo "$0
                         [0G create a template
                         [0G
                         [0G syntax: template --profile-target --help
                         [0G
                         [0G --profile-target      generate a profile section (TARGET NOTES), this is for analysis only and should never be part of your program
+                        [0G --change-author       attempts to guess a new author name form the current user (or TEMPLATE_AUTHOR_NAME if set)
                         [0G --help                this help text
                         [0G
-                        [0G THIS PROGRAM IS LICENSED UNDER THE GNU GPL VERSION 3. SEE MY PROJECTS PAGE FOR MORE INFO.
+                        [0G If you set the TEMPLATE_AUTHOR_NAME_PERSISTENT variable to your name, then that will override the built-in one, unless of course you use the --change-author option.
+                        [0G If you set the AUTHOR_GITHUB variable, that will override the built-in, hard-coded one. This is the only way (atm) to change the github name.
+                        [0G
+                        [0G THIS PROGRAM IS LICENSED UNDER THE GNU GPL (LASTEST VERSION) AVAILABLE AT: https://www.gnu.org/licenses/gpl
                         "
                         exit 127
                         ;;
@@ -105,7 +150,9 @@ fi
 [[ $# -lt 6 ]] && DATE_TIME="$(date)" || DATE_TIME="$6"
 ARG_USED=$#
 ARG_UNUSED=0
+
 CREATED_NOTES="template program under renovation"
+
 TARGET_NOTES="# TARGET NOTES
 #
 # 	EXECUTIVE STATE CHANGES
@@ -127,6 +174,8 @@ TARGET_NOTES="# TARGET NOTES
 #		 ($(date)): $(id -un) ignored the final note and left this behind for
 #		           the user(s) to see, how embarassed I am for the author!
 #"
+
+
 if ! [[ -r "$MYSHELL" ]]; then
 	if [[ -r "$(which "$MYSHELL")" ]]; then
 		# user specified a name in PATH, use it
@@ -165,7 +214,10 @@ if [[ $USE_TARGET_NOTES == 0 ]]; then
     TARGET_NOTES="#"
 fi
 
+AUTHOR_EMAIL="${AUTHOR_NAME##*:}"
+AUTHOR_NAME="${AUTHOR_NAME%%:*}"
 
+#= = = = = = = = = = = = = = = = = TEXT CLIP = = = = = = = = = = = = = = = = = = =
 cat <<MY_EXTREME_END_OF_FILE
 #!${MYSHELL}
 #
@@ -174,17 +226,13 @@ cat <<MY_EXTREME_END_OF_FILE
 #    $PROJECT_NAME
 #    $PROJECT_DESCRIPTION
 #
-#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
+#    Copyright (C) 1995-2021 $AUTHOR_NAME
 #
-#    Written by Gabriel T. Sharp <21shariria@gmail.com>
-#    Latest versions of this and all of my projects can be
-#    obtained by visiting the repository:
+#    Written by $AUTHOR_NAME <$AUTHOR_EMAIL>
+#    Latest versions of this and all projects can be
+#    obtained by visiting the repository at:
 #
-#    <https://github.com/osirisgothra>
-#
-#    Because of the global availability of github at this point, hosting
-#    any additional servers for public use no longer serves a purpose. All
-#    content is available 24/7 through github. (Thanks to GITHUB!).
+#    <https://github.com/$AUTHOR_GITHUB>
 #
 #    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
@@ -208,10 +256,10 @@ cat <<MY_EXTREME_END_OF_FILE
 #
 $TARGET_NOTES
 #
-#  (this template+header was created using the template generator by Gabriel T. Sharp)
+#  This template and header was created using the template generator by Gabriel T. Sharp
+#  You can download the latest version at: <https://www.github.com/osirisgothra/mini.git/eso/ubin-local/template>
+#  (the url is subject to changes on github's behalf, please submit a pull request to fix or request a fix on any url changes)
 #
-
-
 
 
 # Get Options from Command Line for $1
@@ -219,12 +267,12 @@ $TARGET_NOTES
 declare -ga opts
 declare -gi quiet_level=0
 declare -g version_text="\$(tput setaf 124)$1\$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
-declare -g help_text="$1
-$2
+declare -g help_text="$FILENAME
+$DESCRIPTION
 
 SYNTAX
 
-	$1 [OPTIONS] ARGUMENTS
+	$FILENAME [OPTIONS] ARGUMENTS
 
 OPTIONS
 	--help -h	show this help text
@@ -248,6 +296,7 @@ LICENSE
 	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
 
 "
+lecho() { builtin echo "\$@"; }
 
 echo() {
 	if [[ \$quiet_level -gt 0 ]]; then
@@ -257,7 +306,17 @@ echo() {
 	fi
 }
 
-if opts=( \`getopt -n \$0 -o hvq -l help,version,quiet -- "\$@"\` ); then
+is() {
+    case \$1 in
+        quiet)  ((quiet_level > 0));;
+      verbose)  ((quiet_level < 0));;
+       normal)  ((quiet_level == 0));;
+     notquiet)  ((quiet_level <= 0));;
+            *)  ((quiet_level == 1));;
+    esac
+}
+
+if opts=( \`getopt -n \$0 -o hvqV -l verbose,help,version,quiet -- "\$@"\` ); then
 	eval set -- "\${opts[@]}"
 	while [[ \$# -ge 0 ]]; do
 		curopt=\$1
@@ -267,26 +326,27 @@ if opts=( \`getopt -n \$0 -o hvq -l help,version,quiet -- "\$@"\` ); then
 		case \$curopt in
 			--help|-h)	echo "\$help_text"; exit 127;;
 			--version|-v) echo "\$version_text"; exit 127;;
+            --verbose|-V) let quiet_level--;;
 			--quiet|-q) let quiet_level++;;
-			--) echo "done with options"; break;;
-			*)	echo "handling option: \$curopt (next:\$nextopt)";;
+			--) is verbose && echo "done with options";  break;;
+			*)	is verbose && echo "handling option: \$curopt (next:\$nextopt)";;
 		esac
 	done
 	for arg; do
 		# verify/handle non-option arguments
 		case \$arg in
-			*)	echo "handling argument: \$arg";;
+			*)	is verbose && echo "handling argument: \$arg";;
 		esac
 	done
 
 else
-	echo "error, code is \$?, exiting with fail"
+	is notquiet && echo "error, code is \$?, exiting with fail"
 fi
 
 
-
-
 MY_EXTREME_END_OF_FILE
+#= = = = = = = = = = = = = = = = = TEXT CLIP = = = = = = = = = = = = = = = = = = =
+
 
 
 echo "#	template output completed (code=$([[ $? -ne 0 ]] && echo $? || echo 'OK(ERROR_NONE)' ))\n#\n#"
@@ -306,3 +366,42 @@ echo "#	template output completed (code=$([[ $? -ne 0 ]] && echo $? || echo 'OK(
 
 
 
+#  * this file has existed well before this date (2-3 years at least), but is A
+#    now documented as being truly created at this date and time
+#
+# (this header was created using the (very early alpha version of) template generator by Gabriel T. Sharp)
+
+# RANKING (notdone) (expected timespan to complete or decide)
+# 1 <---- this week                4        this month                  7             this year            9        this decade       ----> 10
+# RANKING (done) (how easy the task ended up being)
+# 0 <---- easy peasy     1.5 cool beans               2       not too hard       4  a little annoying          5   very time consuming                8  pain in the ass            9 major headache       rather be shot and tortured than do that again --> 10
+#
+# TODOs (ordered in MOST-IMPORTANT To least-important) move them into DONE when they are finished.
+# #RANK [PLANNED|ONHOLD|LONGTERM|ETC] (HOWIMPORTANT) description <- format your syntax like this, pulls that dont will not be accepted
+# once complete will be: #RANK --- done --> desc (revised steps if needed)
+#
+# TODOs NOT DONE YET: (most of these require program-changing decisions, so they are not yet implemented for this reason)
+# ---------------------
+# #1  PLANNED (VERY)               extract from name:emailname@addr, guess the github username form this, probably 'emailname' would be a good guess, or 'name', <- decide on this soon
+# #2  PLANNED (IMPORTANT)          move code to use a high-level language to take over this project, its getting a bit big to just be a script, even a higher level scripting language might be fine
+# #4  PLANNED (SO-SO)              add multiple and file-based template support, dynamic if possible, with template language description support (TDF, etc)
+# #4  PLANNED (MEH..)              add support for an XML template language (XGSTL possibly?) that will define a template, in a file, kinda dependant on above
+# #6  PLANNED (...MEH)             move X support in zenity into a single form or into a python glob of subcode (or more likely, perl) <- decide on perl/python/zenity for that
+# #5  ONHOLD MUSTDECIDE (...)      multi-license/filetype support <- so far this is just for zsh-like shells
+#
+# TODOs that are DONE:
+# ---------------------
+#	#2 ---  done--> possibly put template in a system or user binpath, possibly on eso??
+#   #3 --- done --> put into esoteric ubin for testing on github???
+#   $1.5 -- done --> added an option system and a more robust author thing
+#                    added a proper getopt parser
+#                    added a better template that starts you off with option parsing, messages with verbosity adjustment in either direction
+#                   added a way to add email and github info into the template (github has to be done via AUTHOR_GITHUB variable (ie, env AUTHOR_GITHUB="blah" template ...)
+#	#1 --- done ---> implement X integration to take values for $1 thru $6 since most
+#                    will probably have an X manager running that supports at the least
+#                    floating or stacked windows, decide on whether we should use one of:
+#                    kdialog, [[zenity]], gnome-dialog (but not dialog because thats CUI). <---- decided on zenity, and implemented it!
+#                    (we cant use any CUI input methods because they interfere with CUI editors!)
+#                    added it anyway: DATE_TIME: not sure why you need to change this really but if you forgot or something, or are on
+#                                     a deadline or have a specific release date it could be useful.
+#
