commission 2018-2020 thats right 2 years now back online

diff --git a/eso/ubin-local/compositor b/eso/ubin-local/compositor
--- a/eso/ubin-local/compositor
+++ b/eso/ubin-local/compositor
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/bin/zsh
+emulate zsh
 #
 #    compositor
 #    A Compositor Program
@@ -40,11 +41,37 @@
 #  (this header was created using the template generator by Gabriel T. Sharp)
 #
 #
-shopt -s extglob
+setopt interactivecomments
+setopt 	extendedglob
 
+declare -gi com_lasterr=250
+declare -gi com_firsterr=128
+declare -gi com_no_error=0
+declare -gx com_binary="compton"
+declare -gxa errors=( unreachable	'cannot locate compositor $com_binary'
+						generic		'generic error'	 )
+
+
+fail()
+{
+	(($#)) || { echo "fatal; no arguments"; exit $com_lasterr; }
+	kind="$*"
+	local -i ecode=1
+	for ekind emsg in $errors; do
+		if [[ $ekind == $kind ]]; then
+			printf "error(%s::%04X): %s" "$ekind" "$ecode" "$emsg"
+			exit $ecode
+		fi
+	done
+	echo "fatal: unknown action=$kind message=$emsg"
+	echo "        check code and try again or notify if it is a bug."
+	exit 255
+}
+
+com_binary=`which $com_binary`
 while [[ $# -gt 0 ]]; do
 	declare nextarg="${1}"; shift
-	case ${nextarg,,} in
+	case ${(L)nextarg} in
 		on|1|true|yes|y|enable?(d)|start|create|begin|go|birth) 	mode=on;;
 		off|0|false|no|n|disable?(d)|stop|kill|end|finish|destroy)	mode=off;;
 		*)	echo "unknown argument: $nextarg"; exit $(( 127 + ${#nextarg} ));;
diff --git a/eso/ubin-local/gzhexedit b/eso/ubin-local/gzhexedit
--- a/eso/ubin-local/gzhexedit
+++ b/eso/ubin-local/gzhexedit
@@ -1,40 +1,22 @@
 #!/bin/bash
 
+# shelloptions
+
 shopt -s interactive_comments
 shopt -s expand_aliases			# let use comments like this one and expand aliases
 
-vecho()
-{
-	if [[ $_OPTIONS_VERBOSEMODE -eq 1 ]]; then
-		echo "$*"
-	fi
-}
+# notes
 
-_OPTIONS_VERBOSEMODE=1
-HEX_EDITOR="/usr/bin/hexeditor"
+# 	vecho delay: + dialog overhead of 0.8 sec, = 1.2+0.8 = 2 second delay approx avg
+#  				 (feel free to change this to your preferred time)
 
-# quick and dirty mode 
-# also coerced by 'env NO_SAFEBACKUP=1 gzhexedit ...'
+# 	HEX_*****: -b for hexeditor, enables buffer mode allowing changing of stream's length (files only)
+#  				 (quick and dirty mode and also coerced by 'env NO_SAFEBACKUP=1 gzhexedit ...'
 
-if [[ $NO_SAFEBACKUP -eq 1 ]]; then
-	vecho "skipped backup because NO_SAFEBACKUP is in the environment"
-else
-	read -sn1 -p "Make safe backup first?? [[y]/n]" QAD
-	if [[ $QAD =~ [nN] ]]; then
-		vecho "user skipping optional extra-safe backup.."
-		vecho "(a backup will still be made, but could be overwritten in the future runs of this program)"
-	else
-		vecho "making safety gzhe/qad backup first..."
-
-		[[ -d ".gzhexedit" ]] || ( ( mkdir ".gzhexedit" || let ERRORS++ ) && ( echo ".gzhexedit exists, using it..." ) )
-		cp "$1" ".gzhexedit/$1-$(date +'%M%d%Y-%H%M%S')-gzhe" || let ERRORS++
-		[[ $ERRORS -gt 0 ]] && { echo "too many errors($ERRORS)"; exit $[ 127 + $ERRORS ]; }
-	fi
-fi
 # functions
 
-	# extras [install|uninstall] -- used internally for extra features present in the OS
-	extras()
+extras()		# ( [install|uninstall] ) -- used internally for extra features present in the OS
+
 	{
 		case $1 in
 			install)
@@ -51,98 +33,176 @@ fi
 				unset -f printf
 			;;
 			*)
-				echo "FATAL: incorrect call (cl=$*) to $FUNCNAME $LINENO ${BASH_SOURCE[@]} $(callers)"
+				dialog --msgbox "FATAL: incorrect call (cl=$*) to $FUNCNAME $LINENO ${BASH_SOURCE[@]} $(callers)" 0 0
 				exit 125
 			;;
 		esac
-	}
-	# cleanup_exit [no params] -- automatically cleanup and exit from any point of the program
-	cleanup_exit()
-	{
+}
+cleanup_exit() #(void) -- automatically cleanup and exit from any point of the program
+{
 		# still try to remove tempfile, otherwise many tmpfiles could pile up if we are automated somehow
 		# this is also a security measure for DDoS protection on the filesystem level
-		rm -f "$TMPFILE"
+		rm -f "$TMPFILE" | dialog --progressbox "Removing Temporary File(s)" 0 0
 		extras uninstall
-		[[ $EXITS -gt 0 ]] && echo "too many errors ($EXITS), aborting!"
+		[[ $EXITS -gt 0 ]] && { dialog --infobox "Some Operations ($EXITS of them) Failed! Exiting..." 0 0 && sleep 4; }
+		dialog --colors --infobox "\Z2All Operations Completed (No Errors Reported)" 0 0 && sleep 2
 		exit $[ 127+$EXITS ]
-	}
-
+}
+vecho() #(string) -- show infobox and wait for no more than 2 seconds
+{
+	dialog --infobox "$*" 0 0
+	sleep $vecho_timeout
+}
 
 # aliases
 
 alias noargs='[[ $# -eq 0 ]]'
 alias wantshelp='[[ $* =~ --help ]] || [[ $* =~ -h ]]'
-alias exit_on_error='[[ $EXITS -gt 0 ]] && cleanup_exit'
+alias exit_on_error='[[ $EXITS -gt 0 ]] && { dialog --infobox "Some Operations Failed ($EXITS of them)" 0 0; sleep 3; cleanup_exit; }'
+alias help_exit='exit 122'
+alias user_exit='exit 125'
+alias flagarg='[[ $* == ^- ]]'
 
-# main
+# variables
 
-extras install
+HEX_EDITOR="/usr/bin/hexeditor"
+HEX_FLAGS="-b"
+vecho_timeout=1.2
 EXITS=0
 TARGET="$1"
 TMPFILE="$(mktemp -u)"
 TARGET_COPY="${1}.copy.gz"
 TARGET_EDIT="${1}.copy"
-cp "$TARGET" "$TARGET_COPY" || let EXITS++		# delegates own error messages
-cp "$TARGET" "$TMPFILE" || let EXITS++
+
+# program
+
+extras install
+
 if noargs || wantshelp; then
 	printf "\n"
 	printf "usage: $(basename "$BASH_SOURCE") [path[/..]/]target-file.ext\n"
 	printf "\n"
-	exit 127
+	# should return as error
+	# because some programs that incorrectly use another program by passing a -h or --help
+	# would need to know it wasnt supposed to be used for normal operation
+	# though technically it could be intentional redirection in which case the program should EXPECT
+	# a return value of 122 anyway.
+	help_exit
+elif flagarg; then
+	printf "flags are not supported, use -h or --help only"
+	help_exit
 fi
+
+# does not pass this point if no arguments are given or --help/-h is given
+
+if [[ $NO_SAFEBACKUP -eq 1 ]]; then
+	vecho "skipped backup because NO_SAFEBACKUP is in the environment"
+else
+	if dialog --yesno "Make Safe Backup of $TARGET first??" 0 0; then
+		vecho "Making safe backup..."
+		[[ -d ".gzhexedit" ]] || ( ( mkdir ".gzhexedit" || let ERRORS++ ) && ( vecho ".gzhexedit exists, using it..." ) )
+		cp "$1" ".gzhexedit/$1-$(date +'%M%d%Y-%H%M%S')-gzhe" || let ERRORS++
+		[[ $ERRORS -gt 0 ]] && { 
+			dialog --msgbox "Too Many Errors ($ERRORS), Exiting)" 0 0
+			exit $[ 127 + $ERRORS ]; 
+		}
+	else
+			vecho "User skipped safe backup, proceeding with edit..."
+	fi
+fi
+
+
+{
+cp "$TARGET" "$TARGET_COPY" || let EXITS++		# delegates own error messages
+cp "$TARGET" "$TMPFILE" || let EXITS++
+} | dialog --progressbox "Making Backups..." 0 0
+
 for CHECK_TARGET in "$TARGET" "$TMPFILE" "$TARGET_COPY"; do
-	printf "acquired target: $CHECK_TARGET -- checking sanity..."
+	dialog --infobox "acquired target: $CHECK_TARGET -- checking sanity..." 0 0; sleep 0.125
 	if ! [[ -r "$CHECK_TARGET" ]]; then
-		printf " **FAILED** - cannot read!!\n"
+		dialog --infobox " $CHECK_TARGET **FAILED** - cannot read!!" 0 0; sleep 2
 		let EXITS++
 	elif ! [[ -w "$CHECK_TARGET" ]]; then
-		echo "**FAILED** - cannot overwrite!!\n"
+		dialog --infobox " $CHECK_TARGET **FAILED** - cannot overwrite!!" 0 0; sleep 2
 	else
-		printf "ok!\n"
+		dialog --infobox "$CHECK_TARGET ok!" 0 0; sleep 0.125
 	fi
 done
 exit_on_error
 # at this point, no errors, all files are now in place
 # the BACKUP can be decompressed and edited in-place
 # source will be decompressed with .gz so we must use a suffix .gz
-gunzip "$TARGET_COPY"
-$HEX_EDITOR "$TARGET_EDIT"
+# -- but we need to make sure the copy isnt there yet
+
+TARGET_NOGZ="${TARGET_COPY%.gz}"
+if [[ -r "${TARGET_NOGZ}" ]]; then
+	if dialog --yesno "${TARGET_NOGZ} already exists, replace it?" 0 0; then
+		rm "${TARGET_NOGZ}" -f
+	else
+		dialog --infobox "${TARGET_NOGZ} must be re/moved before you can edit $TARGET_COPY !!" 0 0
+		sleep 1.25
+		user_exit
+	fi
+fi
+
+if ! gunzip "$TARGET_COPY"; then
+	# now we have a problem, the file:
+	# 1) was copied but is bad because (maybe) it is NOT in gzip format, inform the user and abort the program 
+	# 2) gunzip had an error of some kind or failed to access the file, expects interactive input*
+	# 3) permissions are not met for this file to perform operations
+	# 4) some files that should have been removed, are not (or were recreated by another user/process)
+	# 5) some other unknown error with gunzip
+	# *fails only when running in quiet mode
+	dialog --msgbox "Sorry, $TARGET_COPY (copy of $TARGET) is NOT in gzip format! (You dont need gzhexedit to edit binaries outright, just use hexedit for that!" 0 0
+	exit 134
+fi
+if ! [[ -r "$TARGET_EDIT" ]]; then
+	# bad news still, we have had a good status from gunzip, but we have
+	# no file in TARGET_EDIT which should have been populated
+	# inform the user and exit
+	dialog --msgbox "Internal Error: ($TARGET_COPY did not yeild an editable/readable file. (Is your filesystem full or erroneous, or lacking in permissions?)" 0 0
+	exit 135
+fi
+# at this time, all is good, and the file should be ready to edit
+$HEX_EDITOR ${HEX_FLAGS} "$TARGET_EDIT"
 gzip "$TARGET_EDIT"
 if [[ -r "${TARGET}.before-edit" ]]; then
-	echo "WARNING: a previous backup file before edit exists already, what do you wish to do with it?"
-	echo "1: delete OLD backup data and replace it with the NEW backup data from your most recent edit"
-	echo "   This means: you will not be able to undo the edit before this edit,"
-	echo "   but will still be able to undo THIS edit only. It is recommended only if you are"
-	echo "   certain that you will not need to undo more than just the most recent edit to the"
-	echo "   file being edited. (recommended for advanced users only)"
-	echo "2: cancel changes and quit and ***LOSE MOST RECENT EDITS*** (not recommended)"
-	echo "3: specify a new name for the backup (recommended for most users)"
-	echo -n "choose one: [s"
-	unset TODO
-	while ! [[ "$TODO" =~ [123] ]]; do
-        # BEEK if TODO is set, echo invalid choice, wait 3/4sec, clear up to end of line, and wait again
-		[[ -n "$TODO" ]] || { printf "INVALID CHOICE, TRY AGAIN"; sleep 0.75; printf "[u[Ku"; }
-		read -sn1 TODO
-	done
-	case $TODO in
-		1)	echo "proceeding overwriting data"
+	dialog --help-button --yes-label Overwrite --no-label Discard --help-label Rename --yesno "An old undo backup file exists, what do you want do do (note: Discarding will lose ALL changes!)" 0 0
+	case $? in
+		0)	vecho "Proceeding Overwriting Data"
 			NO_BACKUP=0
 			;;	#needs no intervention
-		2)	echo "cancelling edit..."
+		1)	vecho "cancelling edit..."
 			F=$(mktemp)
 			cp -f "${TARGET_COPY}" "$F"
-			echo "tried copying your edits anyway to $F in case you want it, will be delted by system at some time"
+			vecho "tried copying your edits anyway to $F in case you want it, will be delted by system at some time"
 			exit 141
 			;;
-		3)	read -p "enter new name, this is a one shot deal so type it in correctly:" NEWNAME
-			touch "$NEWNAME"
-			cp -f "${TARGET_COPY}" "$NEWNAME"
+		2)	NEWNAME=""
+			while true ; do
+				NEWNAME=$(dialog --output-fd 1 --inputbox "Pick a new filename (include extension, it is not automatically added!)" 0 0)
+				OK=0
+				if ! [[ -r $NEWNAME ]] && touch "$NEWNAME" && [[ -r "$NEWNAME" ]]; then
+					OK=1
+				else
+					OK=0
+				fi
+				if [[ $OK == 0 ]]; then
+					if	! dialog --yesno "$NEWNAME is not valid (either it exists or it couldnt be written, try again? (cancelling here will abort and lose ALL changes!" 0 0; then
+						vecho "Aborted upon user request, all changes discarded"
+						exit 142
+					fi
+				else
+					[[ $OK -eq 1 ]] && cp -f "${TARGET_COPY}" "$NEWNAME" && break
+				fi
+			done
 			NO_BACKUP=1
 			;;
 		*)	exit 142
 			;;
 	esac
 fi
-( [[ $NO_BACKUP -eq 1 ]] || mv --verbose "$TARGET" "${TARGET}.before-edit" ) && mv "$TARGET_COPY" "$TARGET" --verbose
+(( [[ $NO_BACKUP -eq 1 ]] || mv --verbose "$TARGET" "${TARGET}.before-edit" ) && mv "$TARGET_COPY" "$TARGET" --verbose) | dialog --progressbox "Applying All Settings" 0 0
 exit_on_error
+sleep 1
 cleanup_exit
diff --git a/eso/ubin-local/pick-wallpaper b/eso/ubin-local/pick-wallpaper
--- a/eso/ubin-local/pick-wallpaper
+++ b/eso/ubin-local/pick-wallpaper
@@ -1,5 +1,4 @@
 #!/bin/bash
-# vim:ft=sh
 if [[ $1 == -force ]]; then
 	shift
 else
@@ -16,6 +15,7 @@ shopt -s nullglob
 shopt -s extglob
   set +o nounset
   set +o histexpand
+
 # the color values are given in #, so we cant have interactive comments!
 shopt -u interactive_comments
 
@@ -25,6 +25,308 @@ declare -a PICK_WALLPAPER_REQUIREMENTS=( hsetroot sed perl identify.im6 grep )
 declare -a PICK_WALLPAPER_MISSING
 declare -i PICK_WALLPAPER_NODEPS=0
 declare -i PICK_WALLPAPER_IMAGE_CMD_RUNNING=0
+if [[ -v TRANSFORMATIONS ]] && [[ $TRANSFORMATIONS =~ : ]]; then
+	echo "skipping transformations, defined (properly) elsewhere: $TRANSFORMATIONS"
+	echo "becoming:"
+	IFS=":"
+	let r=0
+	declare -gxa TRANSFORMATIONS=( $TRANSFORMATIONS )
+	for x in $TRANSFORMATIONS; do
+		let r++
+		echo element:$r $x
+	done
+else
+
+# - IMAGEMAGICK TM POSSIBLE TRANSFORMATIONS -
+#
+# RASTERIZE OPERATIONS
+#  -affine matrix       affine transform matrix
+#  -alpha option        activate, deactivate, reset, or set the alpha channel
+#  -antialias           remove pixel-aliasing
+#  -attenuate value     lessen (or intensify) when adding noise to an image
+#  -background color    background color
+#  -bias value          add bias when convolving an image
+#  -black-point-compensation                       use black point compensation
+#  -blue-primary point  chromaticity blue primary point
+#  -bordercolor color   border color
+#  -caption string      assign a caption to an image
+#  -channel type        apply option to select image channels
+#  -clip-mask filename  associate a clip mask with the image
+#  -colors value        preferred number of colors in the image
+#  -colorspace type     alternate image colorspace
+#  -comment string      annotate image with comment
+#  -compose operator    set image composite operator
+#  -compress type       type of pixel compression when writing the image
+#  -delay value         display the next image after pausing
+#  -density geometry    horizontal and vertical density of the image
+#  -depth value         image depth
+#  -direction type      render text right-to-left or left-to-right
+#  -display server      get image or font from this X server
+#  -dispose method      layer disposal method
+#  -dither method       apply error diffusion to image
+#  -encoding type       text encoding type
+#  -endian type         endianness (MSB or LSB) of the image
+#  -family name         render text with this font family
+#  -fill color          color to use when filling a graphic primitive
+#  -filter type         use this filter when resizing an image
+#  -font name           render text with this font
+#  -format "string"     output formatted image characteristics
+#  -fuzz distance       colors within this distance are considered equal
+#  -gravity type        horizontal and vertical text placement
+#  -green-primary point chromaticity green primary point
+#  -intensity method    method to generate intensity value from pixel
+#  -intent type         type of rendering intent when managing the image color
+#  -interlace type      type of image interlacing scheme
+#  -interline-spacing value                       set the space between two text lines
+#  -interpolate method  pixel color interpolation method
+#  -interword-spacing value                       set the space between two words
+#  -kerning value       set the space between two letters
+#  -label string        assign a label to an image
+#  -limit type value    pixel cache resource limit
+#  -loop iterations     add Netscape loop extension to your GIF animation
+#  -mask filename       associate a mask with the image
+#  -matte               store matte channel if the image has one
+#  -mattecolor color    frame color
+#  -moments             report image moments
+#  -monitor             monitor progress
+#  -orient type         image orientation
+#  -page geometry       size and location of an image canvas (setting)
+#  -ping                efficiently determine image attributes
+#  -pointsize value     font point size
+#  -precision value     maximum number of significant digits to print
+#  -preview type        image preview type
+#  -quality value       JPEG/MIFF/PNG compression level
+#  -quiet               suppress all warning messages
+#  -red-primary point   chromaticity red primary point
+#  -regard-warnings     pay attention to warning messages
+#  -remap filename      transform image colors to match this set of colors
+#  -respect-parentheses settings remain in effect until parenthesis boundary
+#  -sampling-factor geometry                       horizontal and vertical sampling factor
+#  -scene value         image scene number
+#  -seed value          seed a new sequence of pseudo-random numbers
+#  -size geometry       width and height of image
+#  -stretch type        render text with this font stretch
+#  -stroke color        graphic primitive stroke color
+#  -strokewidth value   graphic primitive stroke width
+#  -style type          render text with this font style
+#  -support factor      resize support: > 1.0 is blurry, < 1.0 is sharp
+#  -synchronize         synchronize image to storage device
+#  -taint               declare the image as modified
+#  -texture filename    name of texture to tile onto the image background
+#  -tile-offset geometry                       tile offset
+#  -treedepth value     color tree depth
+#  -transparent-color color                       transparent color
+#  -undercolor color    annotation bounding box color
+#  -units type          the units of image resolution
+#  -verbose             print detailed information about the image
+#  -view                FlashPix viewing transforms
+#  -virtual-pixel method                       virtual pixel access method
+#  -weight type         render text with this font weight
+#  -white-point point   chromaticity white point
+# IMAGE OPERATORS
+#  -adaptive-blur geometry                       adaptively blur pixels; decrease effect near edges
+#  -adaptive-resize geometry                       adaptively resize image using 'mesh' interpolation
+#  -adaptive-sharpen geometry                       adaptively sharpen pixels; increase effect near edges
+#  -alpha option        on, activate, off, deactivate, set, opaque, copy transparent, extract, background, or shape
+#  -annotate geometry text                    annotate the image with text
+#  -auto-gamma          automagically adjust gamma level of image
+#  -auto-level          automagically adjust color levels of image
+#  -auto-orient         automagically orient (rotate) image
+#  -bench iterations    measure performance
+#  -black-threshold value                       force all pixels below the threshold into black
+#  -blue-shift factor   simulate a scene at nighttime in the moonlight
+#  -blur geometry       reduce image noise and reduce detail levels
+#  -border geometry     surround image with a border of color
+#  -bordercolor color   border color
+#  -brightness-contrast geometry			improve brightness / contrast of the image
+#  -canny geometry      detect edges in the image
+#  -cdl filename        color correct with a color decision list
+#  -charcoal radius     simulate a charcoal drawing
+#  -chop geometry       remove pixels from the image interior
+#  -clamp               keep pixel values in range (0-QuantumRange)
+#  -clip                clip along the first path from the 8BIM profile
+#  -clip-path id        clip along a named path from the 8BIM profile
+#  -colorize value      colorize the image with the fill color
+#  -color-matrix matrix apply color correction to the image
+#  -connected-components connectivity                       connected-components uniquely labeled  -contrast            enhance or reduce the image contrast
+#  -contrast-stretch geometry                       improve contrast by `stretching' the intensity range
+#  -convolve coefficients                       apply a convolution kernel to the image
+#  -cycle amount        cycle the image colormap
+#  -decipher filename   convert cipher pixels to plain pixels
+#  -deskew threshold    straighten an image
+#  -despeckle           reduce the speckles within an image
+#  -distort method args                       distort images according to given method ad args
+#  -draw string         annotate the image with a graphic primitive
+#  -edge radius         apply a filter to detect edges in the image
+#  -encipher filename   convert plain pixels to cipher pixels
+#  -emboss radius       emboss an image
+#  -enhance             apply a digital filter to enhance a noisy image
+#  -equalize            perform histogram equalization to an image
+#  -evaluate operator value                       evaluate an arithmetic, relational, or logical expression
+#  -extent geometry     set the image size
+#  -extract geometry    extract area from image
+#  -features distance   analyze image features (e.g. contrast, correlation)
+#  -fft                 implements the discrete Fourier transform (DFT)
+#  -flip                flip image vertically
+#  -floodfill geometry color                       floodfill the image with color
+#  -flop                flop image horizontally
+#  -frame geometry      surround image with an ornamental border
+#  -function name parameters                       apply function over image values
+#  -gamma value         level of gamma correction
+#  -gaussian-blur geometry                       reduce image noise and reduce detail levels
+#  -geometry geometry   preferred size or location of the image
+#  -grayscale method    convert image to grayscale
+#  -hough-lines geometry                       identify lines in the image
+#  -identify            identify the format and characteristics of the image
+#  -ift                 implements the inverse discrete Fourier transform (DFT)
+#  -implode amount      implode image pixels about the center
+#  -interpolative-resize geometry                       resize image using 'point sampled' interpolation
+#  -kuwahara geometry   edge preserving noise reduction filter
+#  -lat geometry        local adaptive thresholding
+#  -level value         adjust the level of image contrast
+#  -level-colors color,color                       level image with the given colors
+#  -linear-stretch geometry                       improve contrast by `stretching with saturation'
+#  -liquid-rescale geometry                       rescale image with seam-carving
+#  -magnify             double the size of the image with pixel art scaling
+#  -mean-shift geometry delineate arbitrarily shaped clusters in the image
+#  -median geometry     apply a median filter to the image
+#  -mode geometry       make each pixel the 'predominant color' of the                       neighborhood
+#  -modulate value      vary the brightness, saturation, and hue
+#  -monochrome          transform image to black and white
+#  -morphology method kernel                       apply a morphology method to the image
+#  -motion-blur geometry                       simulate motion blur
+#  -negate              replace every pixel with its complementary color 
+#  -noise geometry      add or reduce noise in an image
+#  -normalize           transform image to span the full range of colors
+#  -opaque color        change this color to the fill color
+#  -ordered-dither NxN                       add a noise pattern to the image with specific                       amplitudes
+#  -paint radius        simulate an oil painting
+#  -perceptible epsilon                       pixel value less than |epsilon| become epsilon or  -epsilon
+#  -polaroid angle      simulate a Polaroid picture
+#  -posterize levels    reduce the image to a limited number of color levels
+#  -profile filename    add, delete, or apply an image profile
+#  -quantize colorspace reduce colors in this colorspace
+#  -radial-blur angle   radial blur the image (deprecated use -rotational-blur
+#  -raise value         lighten/darken image edges to create a 3-D effect
+#  -random-threshold low,high                       random threshold the image
+#  -region geometry     apply options to a portion of the image
+#  -render              render vector graphics
+#  -repage geometry     size and location of an image canvas
+#  -resample geometry   change the resolution of an image
+#  -resize geometry     resize the image
+#  -roll geometry       roll an image vertically or horizontally
+#  -rotate degrees      apply Paeth rotation to the image
+#  -rotational-blur angle                       rotational blur the image
+#  -sample geometry     scale image with pixel sampling
+#  -scale geometry      scale the image
+#  -segment values      segment an image
+#  -selective-blur geometry                       selectively blur pixels within a contrast threshold
+#  -sepia-tone threshold                       simulate a sepia-toned photo
+#  -set property value  set an image property
+#  -shade degrees       shade the image using a distant light source
+#  -shadow geometry     simulate an image shadow
+#  -sharpen geometry    sharpen the image
+#  -shave geometry      shave pixels from the image edges
+#  -shear geometry      slide one edge of the image along the X or Y axis
+#  -sigmoidal-contrast geometry                       increase the contrast without saturating highlights or                       shadows
+#  -sketch geometry     simulate a pencil sketch
+#  -solarize threshold  negate all pixels above the threshold level
+#  -sparse-color method args                       fill in a image based on a few color points
+#  -splice geometry     splice the background color into the image
+#  -spread radius       displace image pixels by a random amount
+#  -statistic type geometry                       replace each pixel with corresponding statistic from the                       neighborhood
+#  -strip               strip image of all profiles and comments
+#  -swirl degrees       swirl image pixels about the center
+#  -threshold value     threshold the image
+#  -thumbnail geometry  create a thumbnail of the image
+#  -tile filename       tile image when filling a graphic primitive
+#  -tint value          tint the image with the fill color
+#  -transform           affine transform image
+#  -transparent color   make this color transparent within the image
+#  -transpose           flip image vertically and rotate 90 degrees
+#  -transverse          flop image horizontally and rotate 270 degrees
+#  -trim                trim image edges
+#  -type type           image type
+#  -unique-colors       discard all but one of any pixel color
+#  -unsharp geometry    sharpen the image
+#  -vignette geometry   soften the edges of the image in vignette style
+#  -wave geometry       alter an image along a sine wave
+#  -white-threshold value                       force all pixels above the threshold into white
+
+
+#
+# rand() -- fast sh-based random number generator
+# 
+# rand(max=255,min=1)	prints a random number between min and max to /dev/stdout
+# min	minimum value to print (will be this value or higher)
+# max	maximum value to print (will be this value or lower)
+# completely internal, does not use /dev/*rand* or external scripting languages
+# footnote: defaults are shown above after their parameters (min/max=[default])
+#           it is typical to just use the first parameter to get a 1-num unless zerobase_frand is set
+# footnote: moved this to perl program called 'frn(1)' see it for details
+# keeping this function for possible future use
+function frand()
+{
+	# defaults set here
+	local -i min=${2-0}
+	if (($zerobase_frand)); then
+		local -i min=${2-0}
+	fi
+	local -i max=${1-255}
+	local -i base=$RANDOM
+	local -i resultbase=$[ ((base*(max+min))/32768)+min ]
+	echo $resultbase
+}
+function rand_color()
+{
+	# generates 3 pairs
+	printf "%02x%02x%02x" $(frn 255) $(frn 255) $(frn 255)
+}
+function rand_geom()
+{
+	printf "%dx%d" $(frn 16) $(frn 16)
+}
+function rand_geom_neg()
+{
+	printf "%dx%d" $(frn 16 -16) $(frn 16 -16)
+}
+function rand_byte()
+{
+	printf "$(frn 255)"
+}
+function rand_angle()
+{
+	printf "$(frn 359)"
+}
+function rand_fpu()
+{
+	# generate a random pseudo-floatingpoint number
+	# based on generation of two decimal places:
+	# first: randomly give a negative sign
+	# second: ones place (0 or 1)
+	# third: hundredths place (0.01 to 0.99)
+	if [[ $(frn 2) -eq 2 ]]; then
+		printf "-"
+	fi
+	printf "%d.%02d" "$(frn 1)" "$(frn 99)"
+
+}
+
+# END TRANSFORMATIONS POSSIBLE
+	declare -gxa TRANSFORMATIONS=(
+			"-gamma $(rand_fpu)"
+			"-brightness-contrast $(rand_geom_neg)"
+			"-paint $(frn 2)"
+			"-fill \#$(rand_color)  -tint $(rand_byte)"
+			"-blur $(frn 6)"
+			)
+	declare -gxa RAND_TRANSFORMS=(
+			"-rotational-blur $(rand_byte)"
+			)
+
+
+fi
+
 
 # preliminary checks
 
@@ -56,10 +358,39 @@ if [[ $PICK_WALLPAPER_NODEPS == 0 ]]; then
 	}
 	function setwp()
 	{
+		local target="$1"; shift
+		local tmpfile="$(mktemp)"
+		if [[ -r $target ]] && [[ -w $tmpfile ]]; then
+			echo "readable"
+			echo "applying transformation(s)"
+			cp "$target" "$tmpfile" || { echo "failed to copy target, aborting"; exit 122; return 122; }
+			for xform in "${TRANSFORMATIONS[@]}"; do
+				echo "applying $xform ..."
+				eval im6-convert $xform "$tmpfile" "$tmpfile"
+			done
+			echo "finished, applying wallpaper+final blend..."
+			setwp_old "$tmpfile"
+			echo "removing tempfile.."
+			rm "$tmpfile" && echo ok || echo "failed---remove it manually because I cannot"
+		else
+			if [[ -r $target ]]; then
+				printf "%s unwrit" $tmpfile
+			else
+				echo "%s unread" $target
+			fi
+			echo "able...STOP"
+			exit 124
+			return 124
+		fi
+	}
+
+	function setwp_old()
+	{
 		local WP="$1"; shift
+		echo "selected: $WP"
 		PICK_WALLPAPER_IMAGE_CMD=( -cover "$WP" "$@" )
 		( identify.im6 "$WP" &&
-		  echo "Command Line: <program> ${PICK_WALLPAPER_IMAGE_CMD[@]}" &&
+		  echo "Command Line: hsetroot ${PICK_WALLPAPER_IMAGE_CMD[@]}" &&
 		  hsetroot "${PICK_WALLPAPER_IMAGE_CMD[@]}" &&
 		  return 1
 		) || return 0
@@ -95,7 +426,7 @@ if [[ $PICK_WALLPAPER_NODEPS == 0 ]]; then
 	[[ -r $PICK_WALLPAPER_FAILSAFE_EFFECT ]]	||	PICK_WALLPAPER_FAILSAFE_EFFECT=( "-add" "#808080" "-add" "#404040" "-gradient" "45" )
 	[[ -r $PICK_WALLPAPER_FAILSAFE_IMAGE ]]		||	PICK_WALLPAPER_FAILSAFE_IMAGE="/opt/tilebg.jpg"
 	[[ -x $PICK_WALLPAPER_BINARY ]] 			||	PICK_WALLPAPER_BINARY=hsetroot
-	[[ -n $PICK_WALLPAPER_DEFAULT_FLAGS ]] 		||	PICK_WALLPAPER_DEFAULT_FLAGS=( "-tint" "#$(perl -e 'printf("%06x", int(rand(16777215)))')" "-cover" )
+	[[ -n $PICK_WALLPAPER_DEFAULT_FLAGS ]] 		||	PICK_WALLPAPER_DEFAULT_FLAGS=( "-tint" "#$(perl -e 'printf("%06x", int(rand(16777215)))')" )
 	[[ -n $PICK_WALLPAPER_WALLPAPER_IMAGES ]]	||	PICK_WALLPAPER_WALLPAPER_IMAGES=( /usr/share/wallpapers/**/*.{png,gif,jpg,jpeg,bmp,xpm} )
 	[[ -n $PICK_WALLPAPER_FLAGS ]]              ||  PICK_WALLPAPER_FLAGS=( "${PICK_WALLPAPER_DEFAULT_FLAGS[@]}" )
 	[[ -n $PICK_WALLPAPER_WALLPAPER_COUNT ]]    ||  PICK_WALLPAPER_WALLPAPER_COUNT=${#PICK_WALLPAPER_WALLPAPER_IMAGES[@]}
diff --git a/eso/ubin-local/pwp b/eso/ubin-local/pwp
--- a/eso/ubin-local/pwp
+++ b/eso/ubin-local/pwp
@@ -1,1 +1,271 @@
-#!/usr/bin/python3
+#!/bin/zsh
+#      vim: ft=zsh:fdm=marker:fmr=###{,###}:et:ts=2:sw=2:mls=5:more:laststatus=2:foldclose=all:foldopen=all
+#    pwp
+#    as the mneomic suggests, picks a wallpaper
+#    github/osirisgothra/mini[dev]/eso/ubin-local
+#    small insignificant esoteric projects, usually only consisting of a single file
+#
+#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all of my projects can be
+#    obtained by visiting the repository:
+#
+#    <https://github.com/osirisgothra>
+#
+#    Because of the global availability of github at this point, hosting
+#    any additional servers for public use no longer serves a purpose. All
+#    content is available 24/7 through github. (Thanks to GITHUB!).
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+# INTENDED RUNNING ENVIRONMENT
+#
+#	This script is meant to run in window managers that dont use a desktop
+#	manager of any kind and usually no session or background manager. There
+#	is support for icewm's background manager (icewmbg), but this is the only
+#	one so far that can be setup here without breaching restrictive protocol.
+#	I wrote this script for dwm, tinywm, evilwm, i3, icewm, blackbox, and a
+#	slew of other small window managers including my own personal gxdwm.
+#
+# ANNOTATIONS
+#
+#	Annotations take the form of 'SECTION:line'. Sections should broken down
+#	into no more than 2 pages (or 100 lines) long. Anthing longer than this
+#	should be sectioned further otherwise the reader will be counting lines
+#	until the cows come home.
+#
+#		PRE-RUN CHECKS:4
+#			Checking for the usage of XDG_CURRENT_DESKTOP is important to
+#			see if we even need to set wallpapers this way. Most Window
+#			managers using this (kde, gnome, xfce) wont have the root window
+#			visible anyway. Furthermore, most use compositing so it is just
+#			best to use their (however bad or good it may be) wallpaper selection
+#			method. You can of course, undefine XDG_CURRENT_DESKTOP and still
+#			use this program, and then use the ~/.config/pwp-last-wallpaper.jpg
+#			created by it, set it in your window managers desktop wallpaper
+#			selector, and then somehow refresh that (usually via dbus or a command)
+#			but this is cumbersome at best and insecure at worst. Since this
+#			is a restricted mode program, nothing like that is done here.
+#
+# HISTORY
+#
+#    Sat Aug 17 08:15:17 EDT 2019
+# 			osirisgothra@larnica fixed some things:
+#				- last of old redirection code is fixed (not allowed in rzsh!)
+#				- checking of dirs before sending them to find(1)
+#				- a spiffy new banner from tetradraw, now that i know about iconv(1)
+#				- ensure we are NOT in MSDOS line endings after appending any ansi text! (cough* hackers *cough)
+#	 Thu Jun 18 21:25:17 EDT 2019
+#            osirisgothra@larnica initially created this file
+#            with the original name, pwp
+#	 Sat Jun 22 11:17:25 EDT 2019
+#			 osirisgothra@larnica pretended to add this common template that is
+#			 used on all github/osirisgothra projects, but it isnt, and since
+#			 has decided that rah template (random-as-hell template) is the
+#			 best of all his templates in which to use!
+#
+# TARGET NOTES
+#
+#   WARNING -- WRITTEN FOR RESTRICTED SHELL MODE#
+#	read about  restricted (rzsh) shell modes in your zsh(1) or zshall(1)
+#	man pages
+#
+#  (this header was created using the template generator by Gabriel T. Sharp)
+#
+# PRE-RUN CHECKS
+
+[[ $options[restricted] == on ]] && { "fail: must not be run with rzsh or zsh in restricted mode"; exit 127; }
+[[ $options[interactive] == on ]] && { "fail: do not run interactivly using source or dot(.) instead run as an executable"; exit 126; }
+[[ $DISPLAY =~ ^:[0-9][0-9]?(.[0-9][0-9]?)?$ ]] || { "fail: cant find proper DISPLAY, needs to run in X"; exit 125; }
+[[ "$XDG_CURRENT_DESKTOP" == "" ]] || ( [[ $KDE_FULL_SESSION != true ]] &&  { "fail: x desktop manager present, you must use it instead to set wallpapers!"; exit 124; } )
+# SHELL OPTIONS
+zmodload zsh/mathfunc
+setopt interactivecomments
+setopt extendedglob
+setopt nobeep
+# VARIABLES
+declare -gx pwp_banner="\e[0,\e[11m\e[1;30m────────────────────────────────────────────────────────────\e[0;37m\n\e[A\e[79C\n┌┐   ┌┐       \e[1;30m┌──────────────────────┐\e[0;37m\n\e[A\e[79C\n\e[36m│┘└┴┘│┘\e[37m       \e[1;30m│\e[37mWall\e[0;36mpape\e[1;34mr P\e[0;36mi\e[1mck an\e[37md\e[36m \e[37mSet\e[30m│\e[0;37m\n\e[A\e[79C\np\e[1;36mi\e[0;36mc\e[1;34mk\e[0;37m          \e[1;30m│\e[37mSc\e[0;36mript\e[1;34m Fo\e[0;36mr I\e[1mce\e[37m/i/D/wm\e[0m \e[1;30m│\e[0;37m\n\e[A\e[79C\n \e[1;30m\_\e[0;37m \e[34mw\e[1;30mal\e[0;34ml\e[1;30m  \e[0;37m \e[1;30m_\e[0;37m  \e[1;30m│\e[37m(\e[0;36man\e[1;34md ma\e[0;36mn\e[1my ot\e[37mhers!)\e[0m    \e[1;30m│\e[0;37m\n\e[A\e[79C\n\e[1;30m  \e[0;37m    \e[1;34mp\e[0;36ma\e[1mpe\e[0;37mr \e[1;30m\\e[0;37m \e[1;30m└──────────────────────┘\e[0;37m\n\e[A\e[79C\n\e[1;30m────────────────────────────────────────────────────────────\e[0;37m\n\e[A\e[79C\n\e[1;31m(\e[0;37mC\e[1;31m)\e[30m2015\e[31m-\e[30m2019 Gabriel T\e[31m.\e[30m Sharp\e[0;37m\n\e[A\e[79C\n\e[1;30mLicense subjet to \e[0;37mPARADISIM LICENSE AGREEMENT\n\e[A\e[79C\n\e[1;30mWhich can be found on https\e[31m://\e[30mgithub\e[31m.\e[30mio\e[31m/\e[30mosirisgothra\e[31m/\e[30mmini\e[0;37m\n\e[A\e[79C\n\e[1;31m(\e[30mlicense or license\e[31m.\e[30mmd for markdown versions\e[31m)\e[0;37m\n\e[A\e[79C\n\e[1;30m────────────────────────────────────────────────────────────\e[0;37m\n\e[A\e[79C\n\e[0m\e[21m"
+declare -gx pwp_method="new"
+declare -gx pwp_process_age="newest"		# possible settings: n(ewest), o(ldest) only the first character is significant
+declare -gx pwp_hsr_binary="hsetroot"
+declare -gx pwp_icewm_binary="icewmbg"
+declare -gx pwp_pgrep_binary="pgrep"
+declare -gx pwp_icewmbg_pid="$(command $pwp_pgrep_binary -x${icewmbg_process_age: 0:1} icewmbg || echo '-1')"
+declare -gx pwp_image_dirs=( /usr/share/wallpapers /b/way/usr/share/wallpapers /b/usr/share/wallpapers )
+declare -gx pwp_images=( )
+declare -gA pwp_presets=(
+	'Havelock Blue' '#3399FF'										# 0
+	'Havelock Blue' '#65B2FF'          								# 1
+	'Dim Gray' '#5E5E5E'											# 2
+	'Havelock Blue Blend Node' '#3399FF'							# 3
+	'Havelock Blue 66 Blend 33 Havelock Blue' '#42A1FF'				# 4
+	'Havelock Blue 33 Blend 66 Havelock Blue' '#52A9FF'				# 5
+	'Havelock Blue Blend Node' '#65B2FF'							# 6
+	'Havelock Blue 66 Blend 33 Dim Gray' '#6393C0' #7
+	'Havelock Blue 33 Blend 66 Dim Gray' '#60778B' #8
+	'Dim Gray Blend Node' '#5E5E5E' #9
+	'Dim Gray' '#5E5E5E' #10
+	'Dim Gray Blend Node' '#5E5E5E' #11
+	'image map 1' '#191487' #12
+	'image map 2' '#120759' #13
+	'vdark' '#050506' #14
+	'vdark2' '#10100a' #15
+	'vdark3' '#151516' #16
+	'vdark4' '#1e1e1f' #16
+)
+
+# FUNCTIONS
+function getimages()
+{
+	if [[ -s /tmp/imgcache ]]; then
+		seecho "found cache, using it (remove it to refresh)"
+		#cat /tmp/imgcache | while read r; do
+		#	pwp_images+=( "$r" )
+		#done
+		#IFS=$'\n'
+		pwp_images=( )
+		#unset IFS
+	else
+		truncate -s0 /tmp/imgcache
+		local id fn
+		for id in $pwp_image_dirs; do
+			if [[ -d $id ]]; then
+				# echo "getting images in $id"
+				IFS=$'\n'
+				found=( `find -L "$id" -regextype posix-extended -iregex '.*\.(png|[gt]iff?|jpe?g|x[pb]m|bmp)'` )
+				for fn in "${found[@]}"; do
+					# echo "adding $fn..."
+					pwp_images+=( $fn )
+					# to list, and to cache
+					# zero length or nonexistent
+					echo "$fn" >> /tmp/imgcache
+				done
+			else
+				seecho "warning: configured directory, \"$id\" is currently not reachable by me"
+			fi
+		done
+	fi
+}
+
+function getimage()
+{
+	if [[ -s /tmp/imgcache ]]; then
+		maxi="${$(wc -l /tmp/imgcache)% *}"
+		iidx="$(( int(floor(rand48($SECONDS) * maxi)) ))"
+		sed -n "${iidx}p" /tmp/imgcache | tr -d '\n'
+	else
+	local -i imin=1 imax=$#pwp_images iidx=${1-1}
+	if [[ $1 == "rand" ]]; then
+		iidx=$(frn $imax $imin)
+	elif [[ $1 =~ "^[0-9]*$" ]]; then
+		iidx=${iidx}
+	else
+		secho "syntax: getimage [<number>|rand]"
+		secho "argument must be a number or 'rand'"
+	fi
+	iidx=$((iidx<imin?imin:iidx))
+	iidx=$((iidx>imax?imax:iidx))
+	printf "${pwp_images[iidx]}"
+	fi
+}
+
+function save_icewm_img()
+{
+	if (( pwp_icewm_pid > 0 )); then
+		printf "icewmbg(pid=$icewmbg_pid) detected, attempting to give it the new wallpaper..."
+		if [[ -r ~/.icewm/preferences ]]; then
+			if perl -i -wpe "s!^[# ]*DesktopBackgroundImage.*!DesktopBackgroundImage=\"$HOME/.config/pwp.jpg\"!g" ~/.icewm/preferences
+			then
+				printf "config=ok "
+				icewmbg -r | perl -wne "0;"
+			else
+				printf "config=fail\ncouldnt successfully write into settings file in ~/.icewm/preferences"
+			fi
+		else
+			printf "failed\n~/.icewm/preferences does not exist, it needs to be created first and have a DesktopBackgroundImage setting entry!\n"
+		fi
+	fi
+}
+seecho() { echo "$@" > /dev/stderr; }
+function get_image_name()
+{
+	case $pwp_method in
+		old)	printf ~/wall/1/$(frn 148 1).jpg
+				;;
+		new)	seecho "getting images..."
+				getimages
+				seecho "done, chosing..."
+				echo "$(getimage rand)"
+				seecho "done"
+			;;
+		*)	cat "$0" | grep pwp_method
+			echo "error: pwp_method must be either old or new, method '$pwp_method' is unknown! (corrupt file or newer version counterparts?)"
+			exit 122;
+			;;
+	esac
+}
+
+
+function translate_tint()
+{
+	# syntax: translate_tint #rrggbb | rrggbb | presetname
+	case ${(L)1} in
+		\#[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])
+			printf "$1";; # leave alone
+		[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])
+			printf "#$1";; # just add the hash
+		*)				# use a preset (from above)
+			case $1 in
+				[0-9]*) ci=0
+						for x in ${(k)pwp_presets}; do
+							if [[ $ci == $1 ]]; then
+								printf "$pwp_presets[$x]"
+								break
+							fi
+							let ci++
+						done
+						;;
+					*)	printf "$pwp_presets[$1]"
+						;;
+			esac
+	esac
+}
+function show_image()
+{
+	TINTCOLOR="$(translate_tint ${1-\#909090})"
+	echo "tint: $TINTCOLOR"
+	image_name="$(get_image_name)"
+	echo "image: $image_name"
+	hsetroot -cover "$image_name" -tint "$TINTCOLOR" -write ~/.config/pwp.jpg
+	if [[ $KDE_FULL_SESSION == true ]]; then
+		print -P "\n%F{27}%BRUNNING IN KDE COMPATIBILITY MODE (see NOTES: KDECOMPAT)\n%f%b"
+		rm /var/cache/pwp/^README
+		cp ~/.config/pwp.jpg /var/cache/pwp/$(mktemp -u pwpXXXXXXXXXXXXX.jpg) -f
+		echo "be sure to use /var/cache/pwp as your wallpaper slideshow to be compatible with kde!"
+	fi
+
+}
+
+##
+## MAIN SCRIPT
+##
+
+echo "${pwp_banner}"
+if show_image "$@"; then
+	# for icewmbg, even if we are not using it now
+	# can at least save it for later when we might
+	save_icewm_img
+fi
diff --git a/eso/ubin-local/starter b/eso/ubin-local/starter
--- a/eso/ubin-local/starter
+++ b/eso/ubin-local/starter
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env perl
 #
 #    starter
 #    program starter hub
@@ -46,19 +46,32 @@
 #
 
 # hub
-FIFO_NAME="$(mktemp)"
-FIFO_OK=0
-if [[ -r "$FIFO_NAME" ]]; then
-	rm "$FIFO_NAME" && 	mkfifo "$FIFO_NAME" && FIFO_OK=1
-fi
-
-while ((FIFO_OK)); do
-	nextitem=$(cat $FIFO_NAME)
-	echo "$nextitem"
-done
-
-
-
+use warnings;
+use v5.20;
+use strict;
+use Path::Tiny qw( tempfile );
+use POSIX qw( mkfifo );
+sub execute {
+	# execute item or set of items
+	# items are executed sequentally, one after the other ends
+	# this procedure is done in the background
+	# returns: pid of executioner
+	unless (fork()) {
+		qx! $_ ! for @_;
+	}
+}
+my $finame = tempfile;
+my $fiok=0;
+$finame->remove() if $finame->exists();
+say("using $finame to communicate with other programs");
+mkfifo($finame,770) || die("cant make $finame into a fifo, aborting");
+while ($fiok == 0) {
+	say("waiting for call...");
+   for my $item ($finame->lines()) {
+		say "recieved: $item";  
+		execute "$item";
+	}
+}
 
 
 
diff --git a/eso/ubin-local/template b/eso/ubin-local/template
--- a/eso/ubin-local/template
+++ b/eso/ubin-local/template
@@ -1,9 +1,11 @@
-#!/bin/bash
+#!/bin/zsh
 #
 #    template
 #    template generator
 #    template generator project
 #    a project for generating templates
+#
+#    NOTICE: this is NOT the template block, it is down below in the code!
 #
 #    Copyright (C) 1995-2018 Gabriel Thomas Sharp
 #
@@ -36,8 +38,10 @@
 #	 Sun Apr 22 12:22:01 EDT 2018
 #            osirisgothra@larnica initially added a template to this file
 #            with the original name, template*
+#  	 Sun 05 May 2019 11:09:39 AM EDT
+#   
 #
-#  * this file has existed well before this date (2-3 years at least), but is 
+#  * this file has existed well before this date (2-3 years at least), but is A
 #    now documented as being truly created at this date and time
 #
 #  (this header was created using the template generator by Gabriel T. Sharp)
@@ -58,23 +62,70 @@
 
 # defaults
 [[ $# -lt 1 ]] && FILENAME="<file>" || FILENAME="$1"
-[[ $# -lt 2 ]] && DESCRIPTION="A ${FILENAME^} Program" || DESCRIPTION="$2"
-[[ $# -lt 3 ]] && PROJECT_NAME="The ${FILENAME^} Project / eso-bin" || PROJECT_NAME="$3"
-[[ $# -lt 4 ]] && PROJECT_DESCRIPTION="A Project That Gloriously Houses ${FILENAME^} / esoteric projects and scripts" || PROJECT_DESCRIPTION="$4"
+[[ $# -lt 2 ]] && DESCRIPTION="A ${(U)FILENAME} Program" || DESCRIPTION="$2"
+[[ $# -lt 3 ]] && PROJECT_NAME="mini/eso" || PROJECT_NAME="$3"
+[[ $# -lt 4 ]] && PROJECT_DESCRIPTION="small projects and stand-alone programs or documents, esoteric or dependant" || PROJECT_DESCRIPTION="$4"
 [[ $# -lt 5 ]] && MYSHELL="/bin/bash" || MYSHELL="$5"
 [[ $# -lt 6 ]] && DATE_TIME="$(date)" || DATE_TIME="$6"
-
+ARG_USED=$#
+ARG_UNUSED=0
+CREATED_NOTES="template program under renovation"
+TARGET_NOTES="# TARGET NOTES
+#
+# 	EXECUTIVE STATE CHANGES
+#		marking single existing file executable
+#			- mode of '$FILENAME' changed to u+rwx/og+rx.. [$C]
+#		completed (0)
+# 	ARGUMENTUAL ANALYSIS
+#       remaining arguments:
+#			${REMARGS-no arguments to list}
+#       disposition:
+#			${ARG_USED-all} were used during execution of template
+#   		${ARG_UNUSED-none} were extra and/or unexpected
+# 	TEMPLATE SUMMARY OF GENERATION
+#	     outcome: ${OUTCOME-good}
+#	     errors: ${SERRORS-0}
+# 	FINAL NOTE
+#	     ${CREATED_NOTES-completed without any significant problems}
+#        you should REMOVE the TARGET NOTES section once youve reviewed this!
+#		 ($(date)): $(id -un) ignored the final note and left this behind for
+#		           the user(s) to see, how embarassed I am for the author!
+#"
 if ! [[ -r "$MYSHELL" ]]; then
 	if [[ -r "$(which "$MYSHELL")" ]]; then
 		# user specified a name in PATH, use it
 		MYSHELL="$(which "$MYSHELL")"
-	fi		
+	fi
 fi
 # base name of executable, for getting language specific data
 # in the default case, '/bin/bash' would be 'bash'
 # or '/usr/bin/perl' would be 'perl'
 # users can be
 MYLANG=$(basename $MYSHELL)
+
+critical() { echo "critical error ($caller): ${1-corrupted state}";  (( $# > 1 )) && shift; exit $1; }
+
+Z=$(( COLUMNS / 2 ))
+
+foundit=0
+item=${1}
+for x in $(echo ${PATH//~/$HOME} | sed 's/:/ /g' ); do 
+	nx="${x}/${item}"
+	if [[ -r "$nx" ]]; then		
+		copies+=( "$nx" )
+	fi
+done
+
+for ci in "${copies[@]}"; do
+	#if [[ -f "$ci" ]]; then
+		#echo -ne "#	"; sudo chmod -v a+x "$ci" | tr '\n' ',' && CMOK="SUCCEEDED" || CMOK="FAILED ON AT LEAST ONE OR MORE FILES"
+		#echo "#	"
+	#else
+	#	echo "#	file $ci didnt exist, skipped it"
+	#fi
+done
+
+
 
 cat <<MY_EXTREME_END_OF_FILE
 #!${MYSHELL}
@@ -116,96 +167,13 @@ cat <<MY_EXTREME_END_OF_FILE
 #            ${USER}@${HOSTNAME} initially created this file
 #            with the original name, $FILENAME
 #
-#  (this header was created using the template generator by Gabriel T. Sharp)
+$TARGET_NOTES
 #
+#  (this template+header was created using the template generator by Gabriel T. Sharp)
 #
 MY_EXTREME_END_OF_FILE
 
-critical() { echo "critical error ($caller): ${1-corrupted state}";  (( $# > 1 )) && shift; exit $1; }
 
-Z=$(( COLUMNS / 2 ))
-echo "# TARGET NOTES"
-echo "#"
-
-foundit=0
-item=${1}
-for x in $(echo ${PATH//~/$HOME} | sed 's/:/ /g' ); do 
-	nx="${x}/${item}"
-	if [[ -r "$nx" ]]; then		
-		copies+=( "$nx" )
-	fi
-done
-case ${#copies[@]} in
-	1) copykind=single;;
-	0) copykind=new;;
-	*) echo "several copies found, make them all executable"
-       echo "${copies[@]}"
-	   select n in yes no abort/quit; do ((REPLY)) && break
-		   echo "incorrect choice!"
-		   echo "please enter a choice listed above."
-    	done	 
-		case $n in
-			1)	copykind=multi;;
-			2)  copykind=none;;
-			3)  exit 165;;
-			*)  critical 166;;
-		esac
-		;;
-esac
-case $copykind in
-	none) echo "not marking any files executable";;
-	new) echo "marking new file executable";;&
-	single) echo "marking single existing file executable";;&
-	multi) echo "marking all files executable";;&
-	*)	for ci in "${copies[@]}"; do sudo chmod -v a+x "$ci"; done;;
-esac	
-echo "completed ($?)"
+echo "#	template output completed (code=$([[ $? -ne 0 ]] && echo $? || echo 'OK(ERROR_NONE)' ))\n#\n#"
 
 
-#!/bin/bash
-
-# A small example program for using the new getopt(1) program.
-# This program will only work with bash(1)
-# An similar program using the tcsh(1) script language can be found
-# as parse.tcsh
-
-# Example input and output (from the bash prompt):
-# ./parse.bash -a par1 'another arg' --c-long 'wow!*\?' -cmore -b " very long "
-# Option a
-# Option c, no argument
-# Option c, argument `more'
-# Option b, argument ` very long '
-# Remaining arguments:
-# --> `par1'
-# --> `another arg'
-# --> `wow!*\?'
-
-# Note that we use `"$@"' to let each command-line parameter expand to a
-# separate word. The quotes around `$@' are essential!
-# We need TEMP as the `eval set --' would nuke the return value of getopt.
-TEMP=`getopt -o ab:c:: --long a-long,b-long:,c-long:: \
-     -n 'example.bash' -- "$@"`
-
-if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
-
-# Note the quotes around `$TEMP': they are essential!
-eval set -- "$TEMP"
-
-while true ; do
-	case "$1" in
-		-a|--a-long) echo "Option a" ; shift ;;
-		-b|--b-long) echo "Option b, argument \`$2'" ; shift 2 ;;
-		-c|--c-long)
-			# c has an optional argument. As we are in quoted mode,
-			# an empty parameter will be generated if its optional
-			# argument is not found.
-			case "$2" in
-				"") echo "Option c, no argument"; shift 2 ;;
-				*)  echo "Option c, argument \`$2'" ; shift 2 ;;
-			esac ;;
-		--) shift ; break ;;
-		*) echo "Internal error!" ; exit 1 ;;
-	esac
-done
-echo "Remaining arguments:"
-for arg do echo '--> '"\`$arg'" ; done
diff --git a/eso/ubin-local/testscript b/eso/ubin-local/testscript
--- a/eso/ubin-local/testscript
+++ b/eso/ubin-local/testscript
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/zsh
 #===============================================================================
 #
 #          FILE: testscript.sh
@@ -9,53 +9,50 @@
 # 
 #===============================================================================
 
-shopt -s interactive_comments
-shopt -s expand_aliases
-shopt -o -s nounset                              # Treat unset variables as an error
+setopt extendedglob
+setopt nullglob
+setopt kshglob
 
-exec 3>&1 4>&2				    # Allow unconditional access to STDOUT/STDERR (required for this example!)
-# now override the echo and return builtins so they work as expected (except for the value of $?)
-function echo() { builtin echo "$@" >&3; }
-function return() { builtin echo "$@"; } # you could add 'exit $1' to indicate a numeric value but unfortunately it wouldnt support >255
-function echo_err() { builtin echo "$@" >&4; }
-function return_err() { builtin echo "$@" >&2; } # result goes to fd/2, good if you wanted multiple return targets 
-alias ret='builtin return'  # access to the "original" return builtin, it must be an alias or it is useless
-function result2err() { [[ -v $1 ]] && (exit ${!1}); }   # convert return code to $? (only supports numeric codes up to 255, of course)
+setopt aliases
+disable hash
+disable true
+disable false
 
-function showsum()
-{
-	# demonstrates returning "nonstandard" values
-	if [[ $# -lt 2 ]]; then
-		# output to stderr instead
-		echo_err "Error #300: Missing some arguments, need 2!! (you gave me $#)" >&3		
-		return 300; ret
-	else
-		echo "Adding up $1 and $2 !! ..." >&3
-		echo "The result is.. $[ $1 + $2 ] !!"
-		return 400; ret 
-	fi
-	echo "THIS LINE SHOULD NOT EXECUTE!"
+alias die='echo "failed in: $zsh_context err=$? perr=${pipestatus-n/a}"; () { eval "exit die_error_$*"; }'
+alias char='typeset -gg'
+alias int='typeset -gi'
+alias array='typeset -ga'
+alias hash='typeset -gA'
+alias bool='typeset -gi'
+alias echo='print -P'
+alias necho='print -Pn'
+alias rint='typeset -gir'
+
+rint false=0
+rint true=1
+
+
+
+
+dadd() { dirs+=( $@ ); }
+fadd() { files+=( $@ ); }
+dmk() { for d ($dirs) { mkdir -p $d || die $0 }}
+fmk() { for f ($files) { touch $f || die $0 }}
+imakeall() { dmk; fmk; items=( $dirs $files )}
+
+dadd /tmp/tempdir/test_dir
+fadd /tmp/tempdir/existing.file
+dadd /tmp/tempdir/existing.dir
+imakeall "$0" "$?" "$@"
+
+for somefile ($items) {
+	echo "inline----"
+	echo "head of $somefile:" $somefile(:h)
+	echo "tail of $somefile:" $somefile(:t)
+	echo "coded----"
+	headfile=( $somefile(:h) )
+	tailfile=( $somefile(:t) )
+	echo "head reassigned: $headfile"
+	echo "tail reassigned: $tailfile"
+	[[ -d $somefile ]] && rmdir $somefile || { [[ -e $somefile ]] && rm -f $somefile; }
 }
-
-echo "### test the normal case ###"
-
-result=`showsum 1 2 3 4`
-echo "This function returned $result"
-
-echo "### test the error case [ERRORS ARE EXPECTED BELOW THIS LINE!] ###"
-
-result=`showsum 1`
-echo "This function returned $result"
-
-result2err result
-echo "The converted value is $?, which of course is not the same as $result"
-
-echo "### test result2err converts values below 255 okay ###"
-result=122
-
-result2err result
-
-echo "The new value of \$? is $?, which should be the same as $result (\$result)"
-
-echo "Testing completed"
-
diff --git a/eso/ubin-local/thrgrep b/eso/ubin-local/thrgrep
--- a/eso/ubin-local/thrgrep
+++ b/eso/ubin-local/thrgrep
@@ -1,4 +1,330 @@
-#!/bin/bash
+#!/bin/zsh
+MAXINT=32767
+docloc="/usr/share/doc/paradisim/mini/ubin-local/thrgrep"
+presetconfig="$HOME/.thrgreppresetrc"
+# adhere to this comment either inline or during execution!
+! [[ -r ~/.iamosirisgothra ]] && { echo "
+# NB: not intended for release of any kind use at own risk, or not at all! (ctrl+break aborts) you will have to read code to disable this message if you are not me
+"; sleep 15; }
+# NB: new argument, do we:
+#    1) allow preset lines such as:
+#					 "mystuffavg" "allavg"
+#    2) or have a special operator like:
+#					 alias mystuffavg=allavg
+#				or	alias mystuffavg allavg
+#				or  allavg [definitions] "aliases:testavg,[otheraliasnames]"
+#	problem being in 1) confusion whether the preset is a process name or not
+#	and in 2) another type of syntax to check, that basically doesnt do
+#	anything special or new (except resolves ambiguity).
+#	at this time, the only way it can be done is to use a "singular list"
+#	to disambiguate it from a non-preset or process name. This can be written
+#	one of two different ways:
+#						"mystuffavg"  ",allavg"
+#	or (preferred) 		"mystuffavg"	"allavg,"
+#
+#	the second one is preferred because the operator is in the back which
+#   keeps it from obstructing the name from view, and also acts as a placeholder
+#   for new items, should they be added (this is actually an idiom used by many
+#	mid and hi-level languages, where lists or hashes [aka dictionaries] are used).
+#	# NB: much argumenting about if (or not) bash->zsh was 'worth it', i wrote out
+# this lengthy evaluation to put this topic to bed.
+# CHANGED: arrays from bash format ( declare -gxA VARNAME=( [keyname]="value" )
+#                   to zsh format: ( declare -gxA VARNAME=( "keyname" "value" )#
+# have been converted and then also the ini file updated, and tested 
+# the meta feature was never in the bash version (is why we went to zsh)
+# the meta feature makes use of parameter flags (zsh only) and prevents the
+# need of manipulating IFS (saving, checking, setting, resetting)
+# the risks of going to zsh were far less than the risks of staying with bash
+# draft risks:
+# bash risks: possibly incompatible because of newer versions (0%)
+#             syntax problems (5%)  inferior syntax methods (30%)
+#             execution time and redundant code (10%)
+#             syntax reviewing confusion (10%)
+#			  user not having bash (0%)  conversion of code (%0)
+#			  overall: 55%
+# zsh risks:  user not having zsh (5%)   conversion of code (1%)
+#			  syntax reviewing confusion (5%)
+#			  overhead due to underuse on the system (2%)
+#			  overall: 13%
+# calculated risks: (draft is for observation and reference only, 
+#                    not for calculation!)
+# risk ---------------:---BASH---:---ZSH---:
+# incompatible version:    0%         1%
+#   conversion of code:   25%         5%
+#   syntax workarounds:   20%         0%
+#script execution time:    0%        15%
+#  reviewing confusion:   10%         8%
+#    language overhead:    2%        20%
+# user missing program:    0%        10%
+# -overall percentage:----[57%]------[59%]
+# -average----------------[8.1%]     [8.4%]
+# -largest risk-----------[25%]------[20%]
+# -integrated risk--------[30.0]     [29.1]
+# -overall gain in using zsh: [0.9] (9%)
+# -integrated "worth-it" percentage: [0.65] (65% gain in positive features and effects)
+#declare -gxA BUILTIN_PRESETS=( [rtfast]="-12 realtime 2" [rtgood]="-14 realtime 4"
+#							 [normal]="0 best-effort 5" [lazy]="12 idle 0" 
+#							 [javafast]="java -14 realtime 5"
+#							 [xorg]="Xorg -14 realtime 2"  )
+# yes this is sugar, pure sugar, and will be moved to another document once
+# this document is in the tree and has a place for older version(s)
+# *if this happened already you are looking at an older branch!!*
+# now, no more complaining, yes its worth it!
+otty=$(tty)
+stty sane
+unset_state="$(uuidgen)"
+assert()
+{
+	# syntax: assert(directive,value) (works for all but developer tool(s) below)
+	#   developer tools:
+	#     assert(avg_op,opname,target,value) --> [[ value OPERATION target ]]
+	#			(where OPERATION is opname replaced at runtime)
+	#			(note: avg_op is not usually to be used directly by user)
+	#
+	directive="${1-$unset_state}"
+	shift
+	case $directive in
+	   $unset_state) echo "super failure, not enough arguments for assert!!"
+					 echo "(none at all given, not even a DIRECTIVE)"
+					 echo "report code: $unset_state"
+					 exit 131; sleep 12288
+					;;
+			 eqavg)	 assert avg_op eq $@ ;;
+			 gtavg)	 assert avg_op gt $@ ;;
+			 ltavg)  assert avg_op lt $@ ;;
+			 geavg)  assert avg_op ge $@ ;;
+			 leavg)  assert avg_op le $@ ;;
+			 neavg)  assert avg_op ne $@ ;;
+			 avg_op)
+					 typeset -g op="${1-eq}"; shift
+					 typeset -i target="${1-0}"; shift
+			 		 typeset -i final=0
+					 typeset -i count=$#
+					 typeset -i tag=0
+					 [[ $# -lt 1 ]] && { return 0 }
+					 for tag; do final+=$tag; done
+					 eval "[[ $final -$op $target ]]"
+					;;
+			 R) for tag; do assert r "$tag"; done;;
+			 W) for tag; do assert w "$tag"; done;;
+			 X) for tag; do  assert x "$tag"; done;;
+			 D) for tag; do  assert d "$tag"; done;;
+			 x) [[ -x "$*" ]];;		d) [[ -d "$*" ]];;
+			 w) [[ -w "$*" ]];;
+	         r) [[ -r "$*" ]];;
+	 qbalanced) r=$(grep -c "[\"']" "$*"); (( r % 2 == 0 && r > 1 ));;
+   qunbalanced) ! assert qbalanced;;
+	   numeric) [[ "$*" =~ ^[0-9]+$ ]];;
+       nimatch) ! assert imatch "$@";;
+        imatch) assert match "${(U)@}";;
+        nmatch) ! assert match "$@";;
+         match)  [[ $1 =~ ${@: 2} ]];;
+        filled) ! assert empty "$@";;
+         empty)    [[ ${#${(j: :)*}} -lt 1 ]];;
+             *) echo "assert failed (${directive-UNSPECIFIED} directive was unexpected) failing abnormally(130): testparams=[$@]";    false;;
+	esac
+	# return value will be delegated to caller by default, make sure not to do ANYTHING outside of the case
+}
+xassert()
+{
+	if assert "$@"; then
+		exec 1>$otty
+		exec 2>&1
+		echo "failed to assert $1 $2 ..."
+		echo "stopping"
+		sleep 2
+		echo "press a key to exit"
+		read -sk1
+	fi
+}
+if [[ $1 == custom ]]; then
+	ib() {
+			stty sane > $otty
+			echo -e "\n\nabout to execute \"$0(${(j:,:)${(qq)@}})\"" | hi "[\"'][^\"']+[\"']"  > $otty
+			echo -e "\ndetail:\n\n\tPrompt=[$1]\n\tDefaultValue=[$2]\n\tTestAgainst=[$3]\n\n" > $otty
+			read -sk1
+			response="$unset_state"
+			# common dialog settings (here only)
+			local comm=( --cancel-label Back --no-lines --output-fd 1 --backtitle "\"${THRGREP_BACKTITLE-Press Cancel or Break anytime to abort custom selection process}\"" )
+			xassert filled "$3"
+			xassert empty "$4"
+			until [[ $response =~ ${3} ]]; do
+				[[ $response != "$unset_state" ]] && {
+					dialog $comm --msgbox "$response is not a valid option (expects a match to regex: $3)" 0 0
+				}
+				response=`dialog $comm --inputbox "$1" 0 0 "$2"`
+			done
+		}
+	# remember DIALOGRC to be set before call(s) for custom colors!
+	declare -gx proc=`ib "RegEx for Processes to Match" ".*"` || exit 127
+	declare -gx nlvl=`ib "Process Niceness, -19 (fastest) to 19 (slowest)" "^-?1?[0-9]\$"` || exit 127
+	declare -gx iogrp=`ib "Process IO Group (realtime,best-effort,idle)" "best-effort" "^(realtime|best-effort|idle)\$"` || exit 127
+	declare -gx iopri=`ib "Process IO Priority (0=none 1=lowest .. 5*=normal .. 7=highest)" "5"` || exit 127
+exit 111
+	dialog --prgbox $((LINES-4?LINES-4:24)) $((COLUMNS-4?COLUMNS-4:80)) "Applying Custom Preset" "thrgrep $proc $nlvl $iogrp $iopri"
+fi
+
+
+declare -gxA BUILTIN_PRESETS=( "rtfast"		"-12 realtime 2"
+								"rtgood"	"-14 realtime 4"
+							 	"normal"	"0 best-effort 5"
+								"lazy"		"12 idle 0"
+							 	"javafast"	"java -14 realtime 5"
+							 	"xorg"		"Xorg -14 realtime 2"  )
+declare -gxA PRESETS=( )
+declare -gxA err=(	unk		"127?unspecified error" )
+function crash()
+{
+	case ${1-none} in
+		none) 	echo "fatal error: crashing (no error description given (cmdline=$*)!"
+			  	crash unk
+				;;
+		*)  	if [[ $1 =~ ^[0-9]+\\\?[a-z]+$ ]] {
+					local errcode=${1%%\?*}
+					local errtext=${1##*\?}
+					echo "crashing (code $errcode): $errtext"
+				}
+				;;
+	esac
+}
+
+function gather()
+{	#    int gather(type)
+	#	 type: owned all root service system siblings parent-siblings toplevel bottomlevel detached tty stopped stopping zombied
+	#	  int: 0=ok !0=error (1=unspecified error, return code possible from last program executed)
+	# type(s) implemented so far: (uncoded: owned all root) (coded: NONE YET)
+	case ${1-unk} in
+		unk)	echo "no type given - program error - exiting (${?-no return code available}/${pipestatus-no pipe status})"; exit ;;
+		*) echo "unsupported: $1"; return 1;;
+	esac
+
+}
+local function debug()
+{
+	#completely transparent if not enabled, let all status codes
+	#fall through the cracks!
+	if ((tg_debug_enable)); then
+		printf "debug($SECONDS,$PWD,$?,$pipestatus): $*"
+	fi
+}
+assert()
+{
+	local R=$? PS=$pipestatus USCOR="$_" BS="$0"
+	if eval "$@"; then
+		return 0
+	else
+		echo "FATAL: ASSERT FAILED!"
+		echo "-----------------------------\ncall stack:\n$(caller $MAXINT)-----------------------------\n"
+		echo "pipes: $PS			status/returncode: $R"
+		echo "lastparam: $USCOR		source(?stack?): $BS"
+		echo "pid: $$ 				ppid: $PPID"
+		tput setaf 13
+		echo "[A] ABORT(DEFAULT)	[C] CONTINUE AT OWN RISK"
+		tput sgr0
+		while true; do read -sk1
+			[[ $REPLY =~ [aAcC] ]] && break
+			if [[ $REPLY == "" ]]; then
+				REPLY=A
+				break
+			fi
+			echo "Invalid Choice, please pick A or C [ENTER=C]"
+		done
+
+		case ${REPLY^^} in A) echo "aborted."; exit 124;;
+                           C) echo "continuing in 5 seconds...";sleep 5s; return 122;;
+			     		   *) echo "fatal??? real bad: even assert failed, must be corruption somewhere!"; exit 123;;
+		esac
+	fi
+}
+init_presets()
+{
+	local nopresets=0
+	if [[ -r $presetconfig ]]; then
+		 eval "typeset -gxA PRESETS=( `cat $presetconfig | grep '^\".*" ".*"'` )"
+#		mapfile PRESETS <$presetconfig ## DISABLED (due to lack of support for named array entries)
+		if [[ ${#PRESETS[@]} -lt 1 ]]; then
+			echo "$presetconfig did not contain any valid presets!"
+			let nopresets++
+		else
+			echo "$#PRESETS preset(s) loaded from $presetconfig"
+		fi
+	else
+		let nopresets++
+	fi
+	if ((nopresets)); then
+		echo -e "notice: no $presetconfig found, only internal presets are available at this time\n		  see $docloc (make sure ubinlocal-docs are installed) for details/examples"
+		unset PRESETS
+		declare -gA PRESETS=( "${(kv)BUILTIN_PRESETS[@]}" )
+	fi
+}
+function has_preset()
+{
+	select_preset "$1"
+	if [[ $PRESETVAL != "" ]]; then
+		return 0;
+	else
+		return 1;
+	fi
+	# (1==false 0==true)
+}
+function select_preset()
+{
+	for x in "${(k)PRESETS[@]}"; do
+		debug echo "checking $1 against $x"
+		if [[ $1 == $x ]]; then
+			echo "found $x = $PRESETS[$x]"
+			PRESETNAME="$x"
+			PRESETVAL="$PRESETS[$x]"
+			return 0
+		else
+			PRESETNAME=""
+		fi
+	done
+}
+init_presets
+if ! has_preset "$1"; then
+	echo "processing as normal command line (no known preset named)"
+else
+	echo "about to use preset $PRESETNAME with value of $PRESETVAL"
+	assert '[[ $PRESETVAL != "" ]]'
+	if [[ "$2" != "" ]]; then
+		searchterm="$2"
+	else
+		searchterm=""
+	fi
+	[[ $# -gt 2 ]] && { echo "warning: more arguments on command line in preset mode---they will be ignored"; }
+	echo "transform from preset: $PRESETNAME -> $PRESETVAL"
+	if [[ $PRESETVAL =~ , ]]; then
+		echo "detected meta-preset, running as subcommand..."
+		for x in ${(s:,:)PRESETVAL}; do
+			echo "delegating thrgrep $x..."
+			command "$0" "$x"
+		done
+		exit 122
+	fi
+	if [[ $searchterm != "" ]]; then
+		eval set -- $searchterm $PRESETVAL
+	else
+		eval set -- $PRESETVAL
+	fi
+
+	echo "injecting into normal command..."
+fi
+
+if [[ $1 == "list" ]]; then
+	# declare -p PRESETS
+	pp=0
+	echo "known presets"
+	echo "---------------------------------------------------"
+	for p in "${(k)PRESETS[@]}"; do
+		echo "$p[[20C${PRESETS[$p]}"
+		let pp++
+	done
+	echo "---------------------------------------------------"
+	echo "$pp preset(s)"
+
+fi
+
 usage()
 {
 cat <<-EOF
@@ -6,6 +332,18 @@ cat <<-EOF
 					   or: thrgrep "search-regex" [nice]
 					   or: thrgrep "search-regex" [nice] [be-ionice]
 					   or: thrgrep "search-regex" [nice] [class] [ionice]
+					   or: thrgrep [preset]
+
+					presets are in the form of command assigning to a thrgrep
+					syntax as stated above (except for the preset one of course)
+					an example shown here:
+						thrgrep javafast		<- typed
+					inside .thrgreppresetrc or BUILTIN_PRESETS:
+ORIGINALLY (when bash was the scripting language):
+						[presetname]='commandline'
+CHANGE:
+						presetname 'commandline'
+						presetname subpreset1, subpreset2, ...
 
 					where "search-regex" is any regular expression(s) that are
 					supported by pgrep (see pgrep(1) for details), and [nice] is
@@ -50,8 +388,30 @@ fi
 
 CMD="$1"
 shift
+echo "using $CMD as criteria"
 THREADS=( $(pgrep -w $CMD) )
-if [[ ${#THREADS[@]} -eq 0 ]]; then
+if [[ $CMD == "all" ]]; then
+	echo "special criteria 'all' found (meaning: all threads under current user)"
+	BLACKLIST=( '\(sd' '^systemd' '^dbus-' )
+	NAMES=( $(awk '{ print $2 ; }' <<< `pgrep -u1000 -l`) )
+	# 2(0) <- loop distance-from-right(left-depth) \v/
+	for x in $NAMES; do
+								#1(1)
+		for y in $BLACKLIST; do
+									#0(2)
+			if [[ $x =~ $y ]]; then
+				echo "cannot do $x, its a blacklist item"
+				continue 2
+			fi
+		done
+        # echo "we should thrgrep $x $@"
+		# we do, here (recalls self, but not in same symbol space)
+		# debug only: # echo thrgrep $x $@
+		thrgrep $x $@
+		# if we had to continue inner_loop, we would actually do inner_loop-1 here (but that wouldnt be needed since its our loop anyway)
+	done
+	exit 0
+elif [[ ${#THREADS[@]} -eq 0 ]]; then
 	echo "no threads found under the given critieria: $CMD"
 	exit 1
 else
@@ -63,21 +423,30 @@ else
 		pfx=sudo
 	fi
 fi
+std_out="/dev/stdout"
+err_out="/dev/null"
+
 for THREADID in "${THREADS[@]}"; do
 	case $# in
 		0)	# display only
 			echo "$THREADID"
 			;;
 		1)	# renice only
-			$pfx renice -n $1 -p $THREADID
+#			[[ $1 =~ ^-?[0-9]+$ ]] || die "bad nice level value: $1"
+#			[[ $THREADID =~ ^[0-9]+$ ]] || die "thread id not legal (numeric decimal integers only): $THREADID"
+			$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out
 			;;
 		2)	# renice | besteffort-prio
-			$pfx renice -n $1 -p $THREADID
-			$pfx ionice -c best-effort -n $2 -p $THREADID
+			$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out
+			$pfx ionice -c best-effort -n $2 -p $THREADID 2>$err_out 1>$std_out
 			;;
 		3)	# renice | class + prio
-			$pfx renice -n $1 -p $THREADID
-			$pfx ionice -c $2 -n $3 -p $THREADID
+			#echo "pfx=\"$pfx\", declaration follows:"
+			#declare -p pfx
+			#echo "$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out"
+			$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out
+			#echo "$pfx ionice -c $2 -n $3 -p $THREADID 2>$err_out 1>$std_out"
+			$pfx ionice -c $2 -n $3 -p $THREADID 2>$err_out 1>$std_out
 			;;
 		*)
 			usage
