3-30-2019

diff --git a/eso/ubin-local/dis b/eso/ubin-local/dis
--- a/eso/ubin-local/dis
+++ b/eso/ubin-local/dis
@@ -1,3 +1,8 @@
 #!/bin/bash
-sudo mv "$1" "$1".disabled
-sudo ln -s /bin/true "$1"
+_choice() { if [[ $(read -n1) =~ [yY] ]]; then return 0; else return $(( 1+$? )); fi; }
+choice() { while true; do _choice; rv=$?; case $rv in 0|1) return $rv;; *) echo "bad choice, try again";; esac; done; echo "fatal error $rv $? $PIPESTATUS 127"; exit 127; }
+if [[ $# -gt 0 ]]; then
+	sudo ln -s /bin/true "$1"
+else
+	echo "syntax: dis [file or directory]"
+fi
diff --git a/eso/ubin-local/rml b/eso/ubin-local/rml
--- a/eso/ubin-local/rml
+++ b/eso/ubin-local/rml
@@ -34,7 +34,7 @@
 #	 NOTES
 #
 #      VARIABLES
-#
+# 
 #        STEPS
 #            Number of jobs to split the signature into evenly across the transfer.
 #            this is how many chunks will be collected from the input at a time each
@@ -65,10 +65,11 @@
 #            replace username/hostname with "X" for unsecure systems
 #        RANDOM_INPUT_DEVICE 
 #            change to the input device that will be used to generate random seed
-#            (default: "/dev/input/event3")
+#            (default: "/dev/input/mice")
 #        RANDOM_DEVICE_TYPE 
+#			 what to call RANDOM_INPUT_DEVICE when displaying it on the screen to the user
+#            during the script's runtime. (examples are: "mouse", "toaster", "peice of crap", "tu-tu", etc)
 #            (default: "mouse")
-#            informal name for RANDOM_INPUT_DEVICE ("mouse", "keyboard", "toaster", etc)
 #        RANDOM_INPUT_LEN 
 #            (default: 0[*])
 #            number of scanlines to read total
@@ -93,6 +94,8 @@
 #
 
 # --- script begins here ---------------------------------------------------------------
+
+
 
 # priority cleanups (done under any condition)
 function cleanup_exit()
@@ -136,6 +139,28 @@ else
 	[[ $- =~ i ]] && { cleanup; return; }
 	cleanup_exit 124
 fi
+# 1.5 verify media files
+shopt -s nullglob
+shopt -s interactive_comments
+FOUND_MEDIA=0
+for x in */*.mp3 *.mp3; do
+	if [[ -e "$x" ]]; then
+		let FOUND_MEDIA++
+	fi
+done
+if [[ $FOUND_MEDIA -eq 0 ]]; then
+	echo "cannot find media in this or child directories, please run from a directory or below a directory with media"
+	echo "or proceed if your media is deeply rooted beyond 2 dirs deep."
+	echo "proceed? [Y to proceed, any other key to abort]"
+	read -sn1 PROCEED
+	if ! [[ $PROCEED =~ [Yy] ]]; then
+		echo "terminating at user's request (at program's recommendation)"
+		cleanup_exit 125
+	else
+		echo "proceeding (could take a bit to search deeply...)"
+	fi
+fi
+
 # #2 flag variables were not initialized with a value of "0"
 for chk in "$RANDOM_NOSECURE" "$RANDOM_NOTINIT" "$RANDOM_NOSANE"; do
 	if [[ "$chk" == "0" ]]; then
@@ -149,7 +174,7 @@ for bins in echo which stty setterm clear rm mktemp echo head tail find uniq sor
 do
 	if r=$(which "$bins")
 	then
-		
+
 		stat "$r" > /dev/null
 		builtin echo -ne "[2K[u$r found ok!"
 	else
@@ -163,6 +188,22 @@ if [[ $RANDOM_CLEANUP_REQUIRED -eq 1 ]]; then
 	echo "[0;31mfatal: too many errors and/or missing executables![0m"
 	cleanup_exit 125
 fi
+# #4 command line
+declare EXTRAPARAMS=( )
+export MAXARG=1 # <- should be same as highest number in case statement below
+case $# in
+	0)	echo "running with defaults (no command line passed)";;
+	1)	case $1 in
+			--linkstoo|-l)	EXTRAPARAMS+=( "-L" );;
+			*)	echo "ignoring argument: $1";;
+		esac
+		;;
+	#^ MAXARG should be same as this number above
+	#
+	*)  echo "error: $# arguments expected, the maximum is $MAXARG"
+		exit 122
+		;;
+esac
 
 # --- end pre-run checks / init -------------------------------------------------------------------------
 
@@ -183,23 +224,25 @@ shopt -s interactive_comments
 
 # data
 
+
 declare RANDOM_LIST_OUTPUT="$(mktemp -- "$0-XXXXXXXX-$USERNAME.$HOSTNAME.$$-XXXXXXXX.rmlpls")"
 declare RANDOM_LIST_SECSIG="$(mktemp -- "$0-XXXXXXXX-$USERNAME-$HOSTNAME-$$-XXXXXXXX.rmlsig")"
-declare RANDOM_INPUT_DEVICE="/dev/input/event3"
+echo "RMLS: $RANDOM_LIST_OUTPUT\n${RANDOM_LIST_SECSIG}"
+declare RANDOM_INPUT_DEVICE="/dev/input/mice"
 declare RANDOM_DEVICE_TYPE="mouse"
 declare -i RANDOM_INPUT_LEN=0
 declare RANDOM_HEADER="_RANDOM_RML_HEADERv1.0gen"
 declare STEPS=4
 
 # code
-
-#RANDOM_HEADER=$(perl -we 'printf("%c",${#RANDOM_HEADER})')"$RANDOM_HEADER"
 if [[ -r $RANDOM_LIST_OUTPUT ]] || [[ -r $RANDOM_LIST_SECSIG ]]; then
+#RANDOM_HEADER=$(perl -we 'printf("%c",${#RANDOM_HEADER})')"$RANDOM_HEADER"
 	echo -ne "not shut down properly, removing old files.."
 	rm -f "$RANDOM_LIST_OUTPUT"
 	rm -f "$RANDOM_LIST_SECSIG"
 	echo "done"
 fi
+
 while [[ $RANDOM_INPUT_LEN -lt 1 ]]; do
 	echo "enter a NONZERO number for signature unique-ness \n(larger numbers takes more $RANDOM_DEVICE_TYPE inputs to generate)\n[number?]: "
 	read RANDOM_INPUT_LEN
@@ -216,7 +259,10 @@ echo -e "[u100% complete!         "
 ss=$(sha256sum $RANDOM_LIST_SECSIG)
 echo "matrix ok, signature: $ss"
 echo -ne "generating list..."
-find -iname '*.mp3' | sort | uniq | sort --random-source="$RANDOM_LIST_SECSIG" -R > $RANDOM_LIST_OUTPUT
+if [[ "$1" == "-v" ]]; then
+	echo "video mode enabled - but not supported yet!"
+fi
+find "${EXTRAPARAMS[@]}" -iname '*.mp3' | sort | uniq | sort --random-source="$RANDOM_LIST_SECSIG" -R > $RANDOM_LIST_OUTPUT
 echo "done"
 sleep 0.65
 clear
diff --git a/eso/ubin-local/template b/eso/ubin-local/template
--- a/eso/ubin-local/template
+++ b/eso/ubin-local/template
@@ -51,17 +51,30 @@
 #                    floating or stacked windows, decide on whether we should use one of:
 #                    kdialog, zenity, gnome-dialog (but not dialog because thats CUI).
 #                    (we cant use any CUI input methods because they interfere with CUI editors!)
-#	#2 --- SOrTa --> possibly put template in a system or user binpath, possibly on eso??
-#   #3 --- kindA --> put into esoteric ubin for testing on github???
-#   #4 --- maybe --> add templates that the user can pick for other licenses or filetypes
+# TODOs that are DONE
+#	#2 ---  done--> possibly put template in a system or user binpath, possibly on eso??
+#   #3 --- done --> put into esoteric ubin for testing on github???
+#   #4 --- done --> add templates that the user can pick for other licenses or filetypes
 
 # defaults
 [[ $# -lt 1 ]] && FILENAME="<file>" || FILENAME="$1"
 [[ $# -lt 2 ]] && DESCRIPTION="A ${FILENAME^} Program" || DESCRIPTION="$2"
-[[ $# -lt 3 ]] && PROJECT_NAME="The ${FILENAME^} Project" || PROJECT_NAME="$3"
-[[ $# -lt 4 ]] && PROJECT_DESCRIPTION="A Project That Gloriously Houses ${FILENAME^}" || PROJECT_DESCRIPTION="$4"
+[[ $# -lt 3 ]] && PROJECT_NAME="The ${FILENAME^} Project / eso-bin" || PROJECT_NAME="$3"
+[[ $# -lt 4 ]] && PROJECT_DESCRIPTION="A Project That Gloriously Houses ${FILENAME^} / esoteric projects and scripts" || PROJECT_DESCRIPTION="$4"
 [[ $# -lt 5 ]] && MYSHELL="/bin/bash" || MYSHELL="$5"
 [[ $# -lt 6 ]] && DATE_TIME="$(date)" || DATE_TIME="$6"
+
+if ! [[ -r "$MYSHELL" ]]; then
+	if [[ -r "$(which "$MYSHELL")" ]]; then
+		# user specified a name in PATH, use it
+		MYSHELL="$(which "$MYSHELL")"
+	fi		
+fi
+# base name of executable, for getting language specific data
+# in the default case, '/bin/bash' would be 'bash'
+# or '/usr/bin/perl' would be 'perl'
+# users can be
+MYLANG=$(basename $MYSHELL)
 
 cat <<MY_EXTREME_END_OF_FILE
 #!${MYSHELL}
@@ -107,3 +120,92 @@ cat <<MY_EXTREME_END_OF_FILE
 #
 #
 MY_EXTREME_END_OF_FILE
+
+critical() { echo "critical error ($caller): ${1-corrupted state}";  (( $# > 1 )) && shift; exit $1; }
+
+Z=$(( COLUMNS / 2 ))
+echo "# TARGET NOTES"
+echo "#"
+
+foundit=0
+item=${1}
+for x in $(echo ${PATH//~/$HOME} | sed 's/:/ /g' ); do 
+	nx="${x}/${item}"
+	if [[ -r "$nx" ]]; then		
+		copies+=( "$nx" )
+	fi
+done
+case ${#copies[@]} in
+	1) copykind=single;;
+	0) copykind=new;;
+	*) echo "several copies found, make them all executable"
+       echo "${copies[@]}"
+	   select n in yes no abort/quit; do ((REPLY)) && break
+		   echo "incorrect choice!"
+		   echo "please enter a choice listed above."
+    	done	 
+		case $n in
+			1)	copykind=multi;;
+			2)  copykind=none;;
+			3)  exit 165;;
+			*)  critical 166;;
+		esac
+		;;
+esac
+case $copykind in
+	none) echo "not marking any files executable";;
+	new) echo "marking new file executable";;&
+	single) echo "marking single existing file executable";;&
+	multi) echo "marking all files executable";;&
+	*)	for ci in "${copies[@]}"; do sudo chmod -v a+x "$ci"; done;;
+esac	
+echo "completed ($?)"
+
+
+#!/bin/bash
+
+# A small example program for using the new getopt(1) program.
+# This program will only work with bash(1)
+# An similar program using the tcsh(1) script language can be found
+# as parse.tcsh
+
+# Example input and output (from the bash prompt):
+# ./parse.bash -a par1 'another arg' --c-long 'wow!*\?' -cmore -b " very long "
+# Option a
+# Option c, no argument
+# Option c, argument `more'
+# Option b, argument ` very long '
+# Remaining arguments:
+# --> `par1'
+# --> `another arg'
+# --> `wow!*\?'
+
+# Note that we use `"$@"' to let each command-line parameter expand to a
+# separate word. The quotes around `$@' are essential!
+# We need TEMP as the `eval set --' would nuke the return value of getopt.
+TEMP=`getopt -o ab:c:: --long a-long,b-long:,c-long:: \
+     -n 'example.bash' -- "$@"`
+
+if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
+
+# Note the quotes around `$TEMP': they are essential!
+eval set -- "$TEMP"
+
+while true ; do
+	case "$1" in
+		-a|--a-long) echo "Option a" ; shift ;;
+		-b|--b-long) echo "Option b, argument \`$2'" ; shift 2 ;;
+		-c|--c-long)
+			# c has an optional argument. As we are in quoted mode,
+			# an empty parameter will be generated if its optional
+			# argument is not found.
+			case "$2" in
+				"") echo "Option c, no argument"; shift 2 ;;
+				*)  echo "Option c, argument \`$2'" ; shift 2 ;;
+			esac ;;
+		--) shift ; break ;;
+		*) echo "Internal error!" ; exit 1 ;;
+	esac
+done
+echo "Remaining arguments:"
+for arg do echo '--> '"\`$arg'" ; done
