dlgi final, ls now CSCS2020 compliant, quietly and twil undocumented, insert prevelant releasature all n.e.n.

diff --git a/eso/ubin-local/dlgi b/eso/ubin-local/dlgi
--- a/eso/ubin-local/dlgi
+++ b/eso/ubin-local/dlgi
@@ -40,10 +40,20 @@
 #  (the url is subject to changes on github's behalf, please submit a pull request to fix or request a fix on any url changes)
 #
 
+# Shell Options
 
-# Get Options from Command Line for dlgi
+setopt interactivecomments
 
-declare -gi scales=0
+# ZSH Modules
+
+zmodload zsh/mathfunc
+zmodload zsh/terminfo
+
+# Declarations
+
+declare -gi termx=${terminfo[cols]} termy=${terminfo[lines]}
+declare -g cls=${terminfo[clear]}
+declare -gi scales=0                                                                                                                                                     #1
 declare -gi restmode=0
 declare -g place_items="$PWD/downloaded"
 declare -ga opts
@@ -67,30 +77,35 @@ OPTIONS
    --quiet -q           increase quiet level by one (quiet level is always zero if left alone)
      --get -g NUMBER    use get mode, just get <NUMBER> of matches from starting point and download them
     --view -w           view mode, use display after getting images (for -g only)
- --no-view -W          reverses effects of --view, or, causes regular viewing to be disabled (not too useful without -g)
+ --no-view -W           reverses effects of --view, or, causes regular viewing to be disabled (not too useful without -g)
+ --rescale=WxH -r       like -C, but allows a number to be used
 
 ARGUMENTS
 
     START       A NUMBER that specifies the index in which to start showing google results, defaults to a random NUMBER
     SEARCHTERMS A STRING in this syntax: \"separate+matches+anywhere+matches that must be consecutive\" as it works in google search.
 
-	FILENAME	A filename that must exist or be writable by the current user.
-	PATHNAME	A relative or absolute path that must exist or be creatable.
-	STRING		A readable string, it must not contain any unreprintable characters.
-	NUMBER		An integer, usually between -32767 and 32767.
-	BOOLEAN		A true/false value, represented as 0 for false, and any other value for true.
-	FLOAT		A floating point single or double precision value, it is precise down to about 5 ot 6 decimal places.
-	ENG			Scientific notation, expressed in powers (3x10^4 is written as 3.4)
-	DEG			Like GRAD/RAD, but expressed in degrees (hours, minutes, seconds) so 3 5'5\" is written as \"3.5.5\"
-
-
 LICENSE
 
 	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
 
 "
-lecho() { builtin echo "$@"; }
+declare -g disp_prog="display-im6"
+declare -g ttyc_prog="tycat"
+declare -g ident_prog="identify-im6"
+declare -g sep_char="-" sep_charv="|"
+declare -g disp="${disp_prog:c}"
+declare -g ident="${ident_prog:c}"
+declare -gi imgno
+declare -gi hilimit=500
+declare -gi lolimit=1
 
+# Subroutines
+
+lecho()
+{
+    builtin echo "$@";
+}
 echo() {
 	if [[ $quiet_level -gt 0 ]]; then
 		return 127
@@ -98,7 +113,6 @@ echo() {
 		builtin echo "$@"
 	fi
 }
-
 is() {
     case $1 in
         quiet)  ((quiet_level > 0));;
@@ -113,60 +127,6 @@ fail()
     echo "failed: $1"
     exit $2
 }
-
-if opts=( `getopt -n $0 -o g:WwnhvqyVCN -l get:,yes,names,no-view,verbose,help,version,quiet,scales -- "$@"` ); then
-	eval set -- "${opts[@]}"
-	echo "cmdline is: $@"
-	while [[ $# -ge 0 ]]; do
-		curopt=$1
-		nextopt=${2-none}
-		echo "$curpot -- $nextopt"
-		shift
-		# handle --options and -o ptions here
-		case $curopt in
-			--no-view|-W) let viewmode--;;
-		    --yes|-y) let restmode=1;;
-			--help|-h)	echo "$help_text"; exit 127;;
-			--version|-v) echo "$version_text"; exit 127;;
-            --verbose|-V) let quiet_level--;;
-			--quiet|-q) let quiet_level++;;
-			--names|-n) autoname=1;;
-			--view|-w) let viewmode++;;
-			--scales|-C) scales=1;;
-			--get|-g)
-			        if [[ $nextopt =~ '[0-9]+' ]]; then
-			            getmode=$nextopt
-			            shift
-			        else
-			            getmode=10
-			            echo "getmode is 10 (nextarg was $nextopt)"
-			        fi
-			        echo "getmode set to $getmode"
-			;;
-			--no|-N) let restmode=0;;
-			--) is verbose && echo "done with options";  break;;
-			*)	is verbose && echo "handling option: $curopt (next:$nextopt)";;
-		esac
-	done
-	echo "final config:"
-	echo "      scales=$scales"
-	echo "    restmode=$restmode"
-	echo "    viewmode=$viewmode"
-	echo " quiet_level=$quiet_level"
-	echo "    autoname=$autoname"
-	for arg; do
-		# verify/handle non-option arguments
-		case $arg in
-			*)	is verbose && echo "handling argument: $arg";;
-		esac
-	done
-
-else
-	is notquiet && echo "error, code is $?, exiting with fail"
-	exit 127
-fi
-
-
 tshortest()
 {
   shortest=$1; for x; do if [[ $#x -lt $#shortest ]]; then shortest=$x;  fi; done; echo $shortest;
@@ -199,69 +159,122 @@ vrule()
     repeat $(( ${LINES-39} - 1 )) { printf "[1D[1B$sep_charv" }
     printf '[u'
 }
-
-declare -g disp_prog="display-im6"
-declare -g ttyc_prog="tycat"
-declare -g ident_prog="identify-im6"
-declare -g sep_char="-" sep_charv="|"
-
-if [[ $(</proc/${$(</proc/$PPID/stat)[4]}/comm) == "terminology" ]]; then
-    declare -g disp="${ttyc_prog:c}"
-else
-    declare -g disp="${disp_prog:c}"
-fi
-declare -g ident="${ident_prog:c}"
-
-[[ -x $ident ]] || fail "cannot locate required dependency: $ident_prog"
-[[ -x $disp ]] || fail "cannot locate required dependency: $disp_prog"
-
-echo "dlgi: argsleft=$@"
-
-mkdir --parents "$place_items" || fail "cannot create $place_items which is required for it to run" 128
-
-zmodload zsh/mathfunc
-echo -n "pre-seeding randomizer...."
-randomseed=$(date +%N)
-echo "set to $randomseed"
-function htmlfilters() {
+function htmlfilters()                                                                                                                                                   #2
+{
     grep -Po '\<img [^\>]+\>' | sed -n 2p | grep -Po '(?<=src=")[^"]+'
 }
 
-declare -gi imgno
-declare -gi hilimit=500
-declare -gi lolimit=1
+# Main Program
+
+if opts=( `getopt -n $0 -o g:Wwnhvqyr:VCN -l get:,yes,names,no-view,verbose,help,version,quiet,rescale:,scales -- "$@"` ); then
+	eval set -- "${opts[@]}"
+	is verbose && echo "cmdline is: $@"
+	while [[ $# -ge 0 ]]; do
+		curopt=$1
+		nextopt=${2-none}
+		is verbose && echo "processing argument: current=$curopt next(or current-argument)=$nextopt"
+		shift
+		# handle --options and -o ptions here
+		case $curopt in
+		    --rescale|-r) scales=9
+		                  if [[ $nextopt =~ '^[0-9]+x[0-9]+$' ]]; then
+		                        scalewidth=${nextopt%%x*}
+		                        scaleheight=${nextopt##*x}
+		                        (( scalewidth < 1 | scaleheight < 1 )) && fail "scale must be no less than one pixel" 122
+	                      else
+	                            fail "rescale size must be in NUMxNUM format (ie; 212x15), not $nextopt" 123
+	                      fi
+                          ;;
+			--no-view|-W) let viewmode--;;
+		    --yes|-y) let restmode=1;;
+			--help|-h)	echo "$help_text"; exit 127;;
+			--version|-v) echo "$version_text"; exit 127;;
+            --verbose|-V) let quiet_level--;;
+			--quiet|-q) let quiet_level++;;
+			--names|-n) autoname=1;;
+			--view|-w) let viewmode++;;
+			--scales|-C) scales=1;;
+			--get|-g)
+			        if [[ $nextopt =~ '[0-9]+' ]]; then
+			            getmode=$nextopt
+			            shift
+			        else
+			            getmode=10
+			            is verbose && echo "getmode is 10 (supplied argument was invalid: $nextopt)"
+			        fi
+			        is verbose && echo "getmode set to $getmode"
+			;;
+			--no|-N) let restmode=0;;
+			--) is verbose && echo "done with options";  break;;
+			*)	is verbose && echo "handling option: $curopt (next:$nextopt)";;
+		esac
+	done
+	if is verbose; then
+    	echo "final config:"
+    	echo "      scales=$scales"
+    	echo "    restmode=$restmode"
+    	echo "    viewmode=$viewmode"
+    	echo " quiet_level=$quiet_level"
+    	echo "    autoname=$autoname"
+	fi
+	for arg; do                                                                                                                                                          #3
+		case $arg in
+			*)	is verbose && echo "handling argument: $arg";;
+		esac
+	done
+else
+	is notquiet && echo "error, code is $?, exiting with fail"
+	exit 127
+fi
+
+
+[[ $(</proc/${$(</proc/$PPID/stat)[4]}/comm) == "terminology" ]] && disp="${ttyc_prog:c}"
+[[ -x $ident ]] || fail "cannot locate required dependency: $ident_prog"
+[[ -x $disp ]] || fail "cannot locate required dependency: $disp_prog"
+mkdir --parents "$place_items" || fail "cannot create $place_items which is required for it to run" 128
+is verbose && echo -ne "pre-seeding randomizer...."
+randomseed=$(date +%N)
+is verbose && echo "set to $randomseed"
+
+
+
 for a b; do
-    echo "a=$a b=$b"
+    is verbose && echo "this pass: a(search-terms)=$a b(offset into google image database)=$b"
     if ((autoname)); then
         declare -g aplace_items="$place_items/${a//[[:punct:]]/}"
         if mkdir --parents "$aplace_items"; then
-            echo "using $aplace_items for this group"
+            echo "creating and/or using directory \"$aplace_items\" as download location"
         else
-            echo "couldnt write $aplace_items failing back to $place_items"
+            echo "couldnt write \"$aplace_items\"; failing back to \"$place_items\""
             aplace_items="$place_items"
         fi
     else
         declare -g aplace_items="$place_items"
     fi
-
     reqtxt="${a?missing a search parameter (must be in single argument)}"
     imgno="${b?missing the count, it should be the second argument}"
     if [[ $imgno -lt $lolimit ]]; then
-        echo -n "count is below low limit, assuming random..."
-        # avoid overlimit (hilimit-1), avoid 0 (+ 1)
+        echo -n "count is below low limit, assuming random..."                                                                                                           #6
         imgno=$(( ceil(rand48(randomseed) * (hilimit-1) ) + 1 ))
         echo "set to $imgno"
-        # should assert imgno again but this program isnt important enough
     elif [[ $imgno -gt $hilimit ]]; then
         echo "count exceeds high limit, google will surely complain (current limit is set to $hilimit items)"
         exit 127
-    fi
+    fi                                                                                                                                                                   #7
     if ((getmode > 0)); then
-        # GET MODE (uses -W or -w)
-        echo "getmode is $getmode, proceeding with mass downloader"
+        # more google arguments
+        # you can add more to this
+        # li:1 -> this tells google NOT to mess with our search terms (re-spell, suggest, split or guessing annoyingly -> google has largely disabled this function so it is ALMOST useless, keep it just in case they get forced to reenable it by the angry masses)
+        # isz:ex -> image size: exact  (iszw: and iszwh: should be obvious enough, width and height for those who need it explained to them)
+        # ic:color -> basically prevents searches from returning black&white or blatently analogous images
+        sargs=(     "tbs=li:1"
+                    "tbs=isz:ex,iszw:256,iszh:256"
+                    "tbs=ic:color"
+              )
+        is verbose && echo "getmode $getmode (total), will now be proceeding with mass downloader for this set..."
         for ((i=0;i<getmode;i++)); do
             ofs=$(( imgno + i ))
-            declare -g url='www.google.com/search?q='"${reqtxt// /+}"'&tbm=isch&start='"$ofs"
+            declare -g url='www.google.com/search?q='"${reqtxt// /+}"'&tbm=isch&'"${(j:&:)sargs}"'&start='"$ofs"
             isrc=$(wget -qU 'Mozilla/5.0' -O /dev/stdout "$url"  | htmlfilters )
             ext=${isrc##*\.}
             ext=${ext//[[:punct:]]/}
@@ -273,13 +286,11 @@ for a b; do
             ext=$( tshortest ${(s:/:)$(file --extension $idest -b)} )
             inewdest="${idest}.${ext}"
             mv "$idest" "$inewdest"
-            hrule
             if (( viewmode >= 1 )); then
                 $disp $inewdest
             fi
-            $ident $inewdest
-
-            if ((restmode != 1)); then            
+            $ident $inewdest | tr -d '\n'; printf ": "
+            if ((restmode != 1)); then
                 echo -ne "[a (default) = ACCEPT IMAGE] [V = ACCEPT THIS AND REST OF IMAGES] [x = REJECT IMAGE]: "
                 read -sk1
                 if [[ $REPLY == "x" ]]; then
@@ -292,23 +303,28 @@ for a b; do
                 fi
             fi
             if (( scales == 1 )); then
-                echo "converting to 64x64"
+                echo -ne " converting to 64x64 "
                 if convert-im6 -adaptive-resize 64x64 "$inewdest" "$inewdest"; then
-                    echo "converted ok"
+                    echo -ne " ok. "
                 else
-                    echo "conversion error($?)"
+                    echo -ne " err($?)"
+                fi
+            elif (( scales == 9 )); then
+                echo -ne "convert ${scalewidth}x${scaleheight} "
+                if convert-im6 -adaptive-resize "${scalewidth}x${scaleheight}" "$inewdest" "$inewdest"; then
+                    echo -ne "ok. "
+                else
+                    echo -ne "err($?) "
                 fi
             else
-                echo "no conversion was requested, keeping resolution (scales=$scales)"
+                echo -ne " (noconvert) "
             fi
             chmod u=rwx,g=rw,o=r $inewdest
             chown $UID:$GID $inewdest
-            echo "finished"
+            echo "(done $SECONDS)"
         done
-    else
-        # VIEW ONLY MODE (implies -w)
+    else                                                                                                                                                                 #9
         declare -g url='www.google.com/search?q='"${reqtxt// /+}"'&tbm=isch&start='"$imgno"
-
         echo "about to make query, \n\timage reqstr: $reqtxt   \n\timgno=$imgno\n\turl=\"$url\""
         if [[ $needs_confirm == 1 ]]; then
                 echo "press ENTER to confirm, or Q to stop (or A to abort altogether)"
@@ -321,12 +337,8 @@ for a b; do
                 fi
         fi
         isrc=$(wget -qU 'Mozilla/5.0' -O /dev/stdout "$url"  | htmlfilters )
-        idest="dlgi.image"
-    #    echo "got isrc: $isrc"
-    #    echo "got idest: $idest"
-        #read -sn1
+        idest="dlgi.image"                                                                                                                                               #8
         wget -qO "$idest" "$isrc" &> /dev/null
-        # dont identify unless nonempty file
         if [[ -s $idest ]] && $ident "$idest"; then
             display "$idest" || echo "skip view because viewmode is $viewmode"
         else
@@ -334,19 +346,24 @@ for a b; do
         fi
     fi
 done
-
-
-
-
-# programmer NOTES:
-# function htmlfilters():
-    # some variations, stack exchange suggestions, etc, that were modified heavily by me:
-    # these are fine for the old way, but the new way doesnt work in terms of pages, instead
-    # they are referred to in terms of a starting match (you can discern the page number which is dynamic depending on the
-    # users results-per-page preference, which varies greatly and should not be assumed)
-    #sed -r 's/</\n</g' | grep -i '<img' | head -n${1} | tail -n1 | sed -r 's/.*src="([^"]*)".*/\1/g'
-    #grep -Poi '\<img[^\>]+' | sed -n ${1}p | grep -Poi '(?<=src=")[^"]+'
-    #NB: dont mistake the grabbing of line 2 in sed (2p), the image number is decided from the start= in url,
-    #    therefore we never need to actually parse anything but the second image result (the first is the google logo)
-    #    warning: this could change if google modifies their plain text pages (they dont do this often, most people use the modern device and https pages
-    #    limitations: only thumbnails can be retrieved this way, but this program is meant for just that anyhow so (small sized textures is what i use it for)
+# CSCS2020 comments:
+#0 this section is where comments must be, nowhere else (only tags elsewhere, or the header)
+#1 this section will get options from command line for dlgi
+#2 some variations, stack exchange suggestions, etc, that were modified heavily by me:
+#  these are fine for the old way, but the new way doesnt work in terms of pages, instead
+#  they are referred to in terms of a starting match (you can discern the page number which is dynamic depending on the
+#  users results-per-page preference, which varies greatly and should not be assumed)
+#  sed -r 's/</\n</g' | grep -i '<img' | head -n${1} | tail -n1 | sed -r 's/.*src="([^"]*)".*/\1/g'
+#  grep -Poi '\<img[^\>]+' | sed -n ${1}p | grep -Poi '(?<=src=")[^"]+'
+#  NB: dont mistake the grabbing of line 2 in sed (2p), the image number is decided from the start= in url,
+#      therefore we never need to actually parse anything but the second image result (the first is the google logo)
+#      warning: this could change if google modifies their plain text pages (they dont do this often, most people use the modern device and https pages
+#      limitations: only thumbnails can be retrieved this way, but this program is meant for just that anyhow so (small sized textures is what i use it for)
+#3 verify/handle non-option arguments
+#6 avoid overlimit (hilimit-1), avoid 0 (+ 1)
+#  below this, should assert imgno again but this program isnt important enough
+#7 these lines are GET MODE (uses -W or -w)
+#8 removed (testing only, before get): echo "got isrc: $isrc"; echo "got idest: $idest"
+#  removed (testing only, after get): read -sn1
+#  conditional identify use: dont identify unless nonempty file
+#
diff --git a/eso/ubin-local/quietly b/eso/ubin-local/quietly
--- a/eso/ubin-local/quietly
+++ b/eso/ubin-local/quietly
@@ -1,174 +1,3 @@
 #!/bin/zsh
-#
-#    gimp-fork
-#    forks gimp while making sure it is done right
-#    mini/eso
-#    small projects and stand-alone programs or documents, esoteric or dependant
-#
-#    Copyright (C) 1995-2021 Gabriel T. Sharp
-#
-#    Written by Gabriel T. Sharp <21shariria@gmail.com>
-#    Latest versions of this and all projects can be
-#    obtained by visiting the repository at:
-#
-#    <https://github.com/osirisgothra>
-#
-#    This program is free software; you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation; either version 2 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License along
-#    with this program; if not, write to the Free Software Foundation, Inc.,
-#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-#
-#    HISTORY
-#
-#	 Sat 27 Feb 2021 08:44:02 AM EST
-#            osirisgothra@ officially applied a template to this file
-#            with the original name, gimp-fork, renamde to ~/bin/gimp (or ubin-local/gimp online)
-#    Sat 27 Feb 2021 08:59:29 AM EST
-#            The Author finalized this script and declares it a finished product -- it will now be mirrored
-#            and has gained completion status fully tested under Xubuntu 20.04 and 20.10, passing all tests.
-#
-#            The Author has verfied that the file adheres to the '2020 Columnized Strict Commenting Scheme' which is
-#            also known as the "2020/CSCS". This scheme requires that 1) all comments are in the form of footnotes
-#            with only a refnum in the far right column. This is in an effort to join the massive need for commenting
-#            your code reformation goin on all over the world, 2) footnotes are at the END of the file, beyond any
-#            executable code or other footnotes. Are easy to read and spot. 3) Do not count for more than 20% of the file's size.
-#            3-CODE Status: PASS PASS PASS (all 100%) A score of 80% or better is required to be 2020CSCS compliant.
-#
-#
-#  This template and header was created using the template generator by Gabriel T. Sharp
-#  You can download the latest version at: <https://www.github.com/osirisgothra/mini.git/eso/ubin-local/template>
-#  (the url is subject to changes on github's behalf, please submit a pull request to fix or request a fix on any url changes)
-#
-
-
-setopt interactivecomments
-setopt aliases                                                                                                                                                                   #10
-
-
-echo "attempting to fork ${0:t} with"                                                                                                                                            #9
-declare -g GIMP_TEMP_LOC=/tmp                                                                                                                                                    #8
-#declare -g GIMP_TEMP_LOC=~/.cache                                                                                                                                               #7
-declare -g GIMP_STATUS_LOG=$GIMP_TEMP_LOC/gimp-status.log
-declare -g GIMP_ERROR_LOG=$GIMP_TEMP_LOC/gimp-errors.log
-#GIMP_STATUS_LOG=/dev/null                                                                                                                                                       #6
-#GIMP_ERROR_LOG=$GIMP_STATUS_LOG
-declare -g STDOUT=1 STDERR=2                                                                                                                                                     #5
-#declare -g STDOUT=CON STDERR=AUX                                                                                                                                                #4
-declare -g GIMP_COMMAND_EXEC="/usr/bin/gimp $(for x; do echo -n "\"$x\" "; done)${1+ }$STDOUT> $GIMP_STATUS_LOG $STDERR> $GIMP_ERROR_LOG &!"                                     #1
-echo "executing command is [${GIMP_COMMAND_EXEC}], excluding braces ([])."
-eval "$GIMP_COMMAND_EXEC"                                                                                                                                                        #3
-rv=$?                                                                                                                                                                            #2
-if pgrep gimp &> /dev/null; then
-    echo "gimp running ok (`pidof gimp`)"
-else
-    echo "gimp not running, assuming an error (rv=$rv)"
-    [[ $rv -eq 0 ]] &&  rv=129
-fi
-exit $rv
-
-# Script Comments
-#
-#0  comments are in order of WHEN (time/date) they were added, not their position within the file itself or line numbers!
-#
-#1  most important line because it defines the actual command, nothing could happen if this line is not there
-#   second line after it, shows us EXACTLY whats being executed so we know theres no command line errors--watch this first run!
-#2  if fork was success, return 129, otherwise give back gimp's error code, and above, determine if gimp is running
-#   if it is, we make the return value 0 (succeess) or keep it 129 (unknown status) or 1-255 (gimp error)
-#3  This is the actual command that is executed once and only once, assumes it will be forked, exits with 129 if it is not (so we know it was OUR error, or anything else if gimp's error was > 0)
-#4  An old dossy environment would use something like this (dont use this if you arent sure what it is for!), or close to it.
-#5  You might want to change these if your terminal uses something other than '1' and '2' for stdout/err (ie, nonlinux systems).
-#6  Un-comment these lines if you dont want logs at all (caution: may hang the system if an error happens due to aformentioned bug!
-#7  Un-comment this line if you cannot write to /tmp (on a foriegn server, for example).
-#8  Due to gimp bug: startup doesnt happen if an error or message is printed and no device is there to display or output it, even if it is just a file, so we must log these to files so they dont hang GIMP's startup process.
-#9  IMPORTANT: 99% of the time, this (This pertains to this entire file) will NOT need changed, please dont change unless you know EXACTLY what you are doing!
-#10 Options processor part of the template was generated but currently unused, to adhere to my in-source comment laws, they must be pasted here in place of #10 until they are re-enabled:
-#
-# -------- cut here --------------------------------------------------------------------------
-# Option-recognition is currently disabled, it will stay that way until it is needed
-# 10 #  do not delete this text because it is still a possible use.
-# 10 #
-# 10 # declare -ga opts
-# 10 # declare -gi quiet_level=0
-# 10 # declare -g version_text="$(tput setaf 124)gimp-fork$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
-# 10 # declare -g help_text="gimp-fork
-# 10 # forks gimp while making sure it is done right
-# 10 #
-# 10 # SYNTAX
-# 10 #
-# 10 # 	gimp-fork [OPTIONS] ARGUMENTS
-# 10 #
-# 10 # OPTIONS
-# 10 # 	--help -h	show this help text
-# 10 #  --version -v   display version information and exit (also shows license info)
-# 10 #    --quiet -q   increase quiet level by one (quiet level is always zero if left alone)
-# 10 #
-# 10 # ARGUMENTS
-# 10 #
-# 10 # 	FILENAME	A filename that must exist or be writable by the current user.
-# 10 # 	PATHNAME	A relative or absolute path that must exist or be creatable.
-# 10 # 	STRING		A readable string, it must not contain any unreprintable characters.
-# 10 # 	NUMBER		An integer, usually between -32767 and 32767.
-# 10 # 	BOOLEAN		A true/false value, represented as 0 for false, and any other value for true.
-# 10 # 	FLOAT		A floating point single or double precision value, it is precise down to about 5 ot 6 decimal places.
-# 10 # 	ENG			Scientific notation, expressed in powers (3x10^4 is written as 3.4)
-# 10 # 	DEG			Like GRAD/RAD, but expressed in degrees (hours, minutes, seconds) so 3 5'5\" is written as \"3.5.5\"
-# 10 #
-# 10 #
-# 10 # LICENSE
-# 10 #
-# 10 # 	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
-# 10 #
-# 10 # "
-# 10 #
-# 10 # lecho() { builtin echo "$@"; }
-# 10 #
-# 10 # echo() {
-# 10 # 	if [[ $quiet_level -gt 0 ]]; then
-# 10 # 		return 127
-# 10 # 	else
-# 10 # 		builtin echo "$@"
-# 10 # 	fi
-# 10 # }
-# 10 #
-# 10 # is() {
-# 10 #     case $1 in
-# 10 #         quiet)  ((quiet_level > 0));;
-# 10 #       verbose)  ((quiet_level < 0));;
-# 10 #        normal)  ((quiet_level == 0));;
-# 10 #      notquiet)  ((quiet_level <= 0));;
-# 10 #             *)  ((quiet_level == 1));;
-# 10 #     esac
-# 10 # }
-# 10 # if opts=( `getopt -n $0 -o hvqV -l verbose,help,version,quiet -- "$@"` ); then
-# 10 # 	eval set -- "${opts[@]}"
-# 10 # 	while [[ $# -ge 0 ]]; do
-# 10 # 		curopt=$1
-# 10 # 		nextopt=${2-none}
-# 10 # 		shift
-# 10 # 		case $curopt in
-# 10 # 			--help|-h)	echo "$help_text"; exit 127;;
-# 10 # 			--version|-v) echo "$version_text"; exit 127;;
-# 10 #             --verbose|-V) let quiet_level--;;
-# 10 # 			--quiet|-q) let quiet_level++;;
-# 10 # 			--) is verbose && echo "done with options";  break;;
-# 10 # 			*)	is verbose && echo "handling option: $curopt (next:$nextopt)";;
-# 10 # 		esac
-# 10 # 	done
-# 10 # 	for arg; do
-# 10 # 		case $arg in
-# 10 # 			*)	is verbose && echo "handling argument: $arg";;
-# 10 # 		esac
-# 10 # 	done
-# 10 # else
-# 10 # 	is notquiet && echo "error, code is $?, exiting with fail"
-# 10 # fi
-# -------- cut here --------------------------------------------------------------------------
+echo "forking $(basename $0) with $# arguments ($@)"
+exec qfork /usr/bin/$(basename $0) "$@" || echo "failed to fork lowriter"
diff --git a/eso/ubin-local/twil b/eso/ubin-local/twil
--- a/eso/ubin-local/twil
+++ b/eso/ubin-local/twil
@@ -1,35 +1,138 @@
 #!/bin/bash
+#
+#    twil
+#    target a working path and file into a launcher
+#    mini
+#    eso/ubin-local
+#
+#    Copyright (C) 1995-2021 Gabriel Thomas Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all of my projects can be
+#    obtained by visiting the repository: 
+#
+#    <https://github.com/osirisgothra>
+#
+#    Because of the global availability of github at this point, hosting
+#    any additional servers for public use no longer serves a purpose. All
+#    content is available 24/7 through github. (Thanks to GITHUB!).
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#    HISTORY
+#
+#	 Sat 28 Nov 2020 09:04:36 PM EST
+#            root@ initially created this file
+#            with the original name, twil
+#   ABOUT
+#
+#	adapter program for launching stuff with other stuff
+#
+#	arguments: passed to program (not launcher)
+#	variables expected on ENVIRONMENT TABLE: working  launcher  target (all array form)
+#
+#	name      | type  | description
+#	-----------+-------+--------------------------------------------------------------------------------------------
+#      working | string |  the directory to chdir(1) to before running anything
+#	  launcher | string |  the program which will recieve the target and arguments to act on
+#	    target | string |  the target to pass to launcher, which will recieve the arguments from
+#	           |        |  the command line.
+#	largs	   | sarray |  a single variable to an array with splitting, to send to launcher (not arguments for target)
+# 	 positional| array  |  the built-in arguments ($1-$9 etc) will be passed directly after the target
+#	           |        |  and are usually arguments for the target program
+#  -----------------------------------------------------------------------------------------------------------------
+#
+#
 
-vassert() { test -v $1 || { echo "cannot configure - program forgot to setup $1 variable"; exit $((127+${2-0} )); }; }
+case $1 in
+	conf*)
+		shift
+		exec twil_editor "$@"
+		echo "returned from exec (failed, code: $?)"
+		exit
+		;;
+	make)
+		shift
+		fname="$1"
+		lname="$2"
+		target="$3"
+		wname=$(dirname $target)
+		if [[ -r $fname ]]; then
+			echo "already exists, use editor to modify"
+		else
+			if touch $fname; then
+# ---------------------------------------------------------------------------------- #
+				echo "#!/bin/bash
+launcher=\"$lname\"
+working=\"$working\"
+target=\"$target\"
+" > $fname && echo "created $fname" || echo "failed to finish writing $fname";
+# ---------------------------------------------------------------------------------- #
+			else
+				echo "failed to write $fname"
+			fi
+		fi
+		exit
+		;;
+esac
 
-vassert working
-vassert launcher
-vassert target
 
+# vassert
+# syntax: vassert([var],[exitoffset],[msg])
+#	[var] 			variable to check (remember you need to EXPORT variables when running the script instead of sourcing
+#					if the special value 'GENFAIL' is used, then $3 ([msg]) is printed then exits with exitoffset (see below)
+#   [exitoffset] 	the return code is usually 127 if ommitted, but, this value will be ADDED if supplied, to 127 (if you specify '4' the return value is '131' which is '127+4')
+#                   the code is only used when the assert fails (which is when the variable IS NOT defined at all, beware of other programs using such names!)
+#	[msg]			used before exit, only when GENFAIL is used
+# notes: if GENFAIL is used in [var], the assert ALWAYS fails, this is used in post-failing situations, you'll see below...
+function __vassert()
+{
+	if [[ $1 == GENFAIL ]]; then
+		echo "${3-A General Undescribed Failure Has Happened, Exiting}"  > /dev/stderr
+		exit $((127+${2-0}))
+	else
+		test -v $1 || {
+			echo "cannot configure - program forgot to setup $1 variable"  > /dev/stderr
+			exit $((127+${2-0} ))
+		}
+	fi
+}
 
+# codes: working 137	launcher 147	target 157
 
+__vassert working	10
+__vassert launcher	20
+__vassert target	30
 
 if [[ -d $working ]]; then
-	chdir "$working"
-
-	# unlike zsh, bash uses zero based arrays by default on non-positional parameter arrays (not 1-based)
-	if [[ -x ${target[0]} ]]; then
-		if [[ -x ${launcher[0]} ]]; then
-			# bash requires arrays to be quoted to have each element split instead of whitespace and expansion (this goes for target, launcher, AND positionals)
-			exec "${launcher[@]}" "${target[@]}" "$@"
+	cd "$working"
+	if [[ -x $target ]]; then
+		if [[ -x $launcher ]]; then
+			if [[ $largs != "" ]]; then
+				exec "$launcher" $largs "$target" "$@"
+			else
+				exec "$launcher" "$target" "$@"
+			fi
 			ec=$?
-			echo "error: exec on $launcher (lastarg=$_) failed (lasterr=$ec)"
-			let ec+=129
-			(( ec < 255 )) && exit $ec || { echo "error code is $ec but wont be returned  it is out of range!";  exit 129; };
+			__vassert GENFAIL $ec "error: exec on $launcher (lastarg=$_) failed (lasterr=$ec)"
 		else
-			echo "error: launcher $launcher is not found" > /dev/stderr
-			exit 128
+			__vassert GENFAIL $LINENO "error: launcher $launcher is not found"
 		fi
 	else
-		echo "warning: cannot find or execute $target" > /dev/stderr
-		exit 127
+		__vassert GENFAIL $LINENO "warning: cannot find or execute $target"
 	fi
 else
-	echo "fatal: cannot chdir into working dir: $working" > /dev/stderr
-	exit 126
+	__vassert GENFAIL $LINENO "fatal: cannot chdir into working dir: $working"
 fi
