synchronized with paralell offline tree

diff --git a/eso/ubin-local/ited b/eso/ubin-local/ited
--- a/eso/ubin-local/ited
+++ b/eso/ubin-local/ited
@@ -2,6 +2,7 @@
 # vi: mls=2:hls:fdo=insert:fcl=all:fdl=2:fen:fdm=marker:fmr=#<,>#:fdm=syntax:cc=160:siso=50:so=$COLUMNS:ft=zsh:ts=4:sw=4:et:bs=2
 #
 emulate zsh
+print -P  "ppid: $(readlink -e /proc/$PPID/exe)"
 #
 #    ited
 #    edit inventorytweaks rules/sorting/config files in currently running modpack (see requirements)
@@ -40,27 +41,17 @@ emulate zsh
 #            osirisgothra@ initially created this file
 #            with the original name, ited
 #
-# TARGET NOTES
+#	NOTES:
 #
-# 	EXECUTIVE STATE CHANGES
-#		marking single existing file executable
-#			- mode of 'ited' changed to u+rwx/og+rx.. []
-#		completed (0)
-# 	ARGUMENTUAL ANALYSIS
-#       remaining arguments:
-#			no arguments to list
-#       disposition:
-#			4 were used during execution of template
-#   		0 were extra and/or unexpected
-# 	TEMPLATE SUMMARY OF GENERATION
-#	     outcome: good
-#	     errors: 0
-# 	FINAL NOTE
-#	     template program under renovation
-#        you should REMOVE the TARGET NOTES section once youve reviewed this!
-#		 (Sat 27 Jun 2020 12:21:15 PM EDT): osirisgothra ignored the final note and left this behind for
-#		           the user(s) to see, how embarassed I am for the author!
-#
+#		TODO:
+#			- see inline code for TODO messages
+#			- sanitization of arguments if we ever use them
+#			- = = of $0 because it could be unsafe (maybe)
+#			- verify prerequisites are what we expect (version checks and/or mimetype checks, permissions)
+#			- verify permissions on all files involved in high-level calls
+#		DONE:
+#			Q: verification of the jku_gamedir script (make sure its really the correct script)
+#				A: using another tool called mgamedir which is much faster for both calls, may combine these later
 #
 #  (this template+header was created using the template generator by Gabriel T. Sharp)
 #
@@ -68,19 +59,31 @@ emulate zsh
 #
 #
 
+# zsh check
+
 [[ $zsh_eval_context =~ toplevel ]]  || echo "fatal: zsh(1) required!"
 
+# required modules 
+
+zmodload zsh/terminfo
+zmodload zsh/termcap
+zmodload zsh/mathfunc
+
+
 # functions
+sc() { echoti sc; }
+rc() { echoti rc; }
+ce() { echoti cuu 0; }
 
 function print() 
-{ 
-        builtin print -P "$@"
-}
+{                         
+	builtin print -P "$@" 
+}                         
+  
 
 # prologue variables
 
-
-declare -ga prerequisites=( zsh jku_gamedir java perl which find sed grep pgrep ps basename dirname realpath nano )
+declare -ga prerequisites=( zsh mgamedir java perl which find sed grep pgrep ps basename dirname realpath nano )
 declare -gi errors=0
 
 setopt kshglob
@@ -95,64 +98,221 @@ setopt kshglob
 setopt noxtrace
 _debug=0
 
+# cuu (up cursor) / sc (save cursor position) / rc (restore cur. pos)
+echoti cuu 2
+echoti sc
+echocip() { # echo clearing to eol + inplace (no cursor change)
+	echoti sc
+	if [[ $1 == -n ]] || [[ $1 == -ne ]]; then shift
+		pat="$1"
+		shift
+		set -- "$pat\n" "$@"
+	elif [[ $1 =~ ^-.* ]]; then	shift
+	fi
+	printf "$@"
+}
+
 # required externals
 
+integer n=${#prerequisites}
+integer i=0
 for x ($prerequisites)  {
-							print "checking for required components..."
+							# the two IF statements with i++ are intended to allow the user to see the stage start from 0% and end at 100% during the run
+
+							if [[ $i -gt 0 ]]; then let i++; fi
+							integer p=$(( i*100 / n ))
+							print -P "$(rc)checking for required components...${p}%% $(ce)"
                             if [[ -x `which -p "$x"` ]]  {
                                     [[ $_debug == 1 ]] && print "%BFound:%b $x"
                             } else {
                                         print "%F{124}%Berror:%b %U$x%u is required but is NOT found%f"
                                         let errors++
                             }
+							if [[ $i -le 0 ]]; then let i++; fi
 }
+echo "\n"
+
+# ask mgamedir if minecraft is running
+if [[ `mgamedir is_running` == "no" ]]; then
+	echo "minecraft not running"
+	if [[ -w $ITED_ROOT/config/InvTweaksRules.txt ]]; then
+		echo "setting mgamedir stand-in because ITED_ROOT is set to a valid directory"
+		mgamedir()
+		{
+			case $1 in
+				dir)	echo "$ITED_ROOT";;
+				name)	echo "User-specified manual directory";;
+				*)		echo "N/A";;
+			esac
+			return 0
+		}
+	else
+		echo "Please either: \n\t1) run minecraft before using this program\n\t2) specify a base directory in ITED_ROOT\n"
+		exit 1
+	fi
+fi
 
 # epilogue variables
 
-declare -gx gamedir="$(jku_gamedir)"
-declare -gx gamename="$(jku_gamedir -g)"
+# CHANGED: 1) gamename/gamedir depends now on mgamedir instead of jku_gamedir (see above)
+#          2) dcrg avoids reuse of text
+# TODO:  write real process monitoring progress meter
+
+dcrg="detecting currently running game"
+print -P "$(sc)$dcrg (5%)..."
+#declare -gx gamedir="$(jku_gamedir)"
+declare -gx gamedir=$(mgamedir dir)
+print -P "$(rc)$dcrg (55%)...$(ce)"
+#declare -gx gamename="$(jku_gamedir -g)"
+declare -gx gamename=$(mgamedir name)
+print -P "$(rc)$dcrg (75%)...$(ce)"
 declare -gx progname=$(basename $0)
 declare -gx progpath=$(realpath $(dirname $0))
+print -P "$(rc)$dcrg (100%)...$(ce)\n"
 
-# modules
-
-zmodload zsh/mathfunc
-zmodload zsh/termcap
 
 # program
 
-function t() { for x { echotc "$x" } }
+function t()																																				
+{ 
+ 	for x { echotc "$x" }
+} 
 
 
-function main()
-{
-    [[ $_debug == 1 ]] && print "prog name=$progname path=$progpath"
-    print "found running game in '$gamedir' called '$gamename'"
+function main()                                                                                                                                              
+{ 
+	# 0=nobackup 1=copy to cache ~/.cache/ited/backup
+
+	io_backup=0
+	io_useconfig=0
+
+	wants_config_file=""
+	# see attached ini example at end of file
+	# perl .ini reading
+	# [needs no modules and works with perl5 released on ubuntu 9.04 or newer, tested]
+	# read from .itedrc, [Files] section, any valid filenames that exist (can be zero length)
+	declare -ga extrafiles=( `perl -wne '$n=$_; chomp($n); print if /^\s*\[Files\]\s*(#.*|)$/ ... /\[/ and not /([\[#]|^\s*$)/ and -r $n and -f $n' /home/osirisgothra/.itedrc` )
+	# reads from .itedrc [Config] section, values are converted to lowercase
+	# VALUE=1 would be io_value=1, MY=VALUE is io_my=value, and so on
+	# naturally because of this, filenames are not in this section at all
+	eval `perl -wne 'printf(lc("io_$_")) if /^\s*\[Config\]/ ... /\[/ and not /([\[#]|^\s*$)/ and /^[^#]*\S=\S/' /home/osirisgothra/.itedrc`
+	# rc file's config value overrides the command line:
+	(( io_useconfig )) && ITED_USE_CONFIG_FILE=1
+	print "found running game in '$gamedir' called '$gamename'"
 	_configdir="$gamedir/config"
-	_files=( --syntax=invtweaksrules $_configdir/InvTweaksRules.txt 
-			 	$_configdir/InvTweaksTree.txt
-			 	$_configdir/InvTweaks.cfg		)
-	echo -n "detecting nano settings..."
-	for x in ~/.nanorc /etc/nanorc /var/nano/nanorc ~/.config/nano/nanorc ~/.config/nanorc ~/.config/.nanorc; do
-		if [[ -r $x ]]; then
-			_conf="$x"
-			break
-		fi
-	done
-	[[ -r "$_conf" ]] || echo "fatal: cannot locate nano config file -- please create one or reinstall nano"
-	if ! grep -q invtweaksrules\.nanorc $_conf; then
-		echo "invtweaksrules syntax rule not installed, color support will be limited!"
+
+	# sanitize invalid values to zero if needed
+	[[ "$ITED_USE_CONFIG_FILE" =~ ^[01]$ ]] || ITED_USE_CONFIG_FILE=0
+	# dont need quotes for it here, its been sanitized, but i use them anyway in case code structure changes
+	if [[ "$ITED_USE_CONFIG_FILE" == 1 ]]; then
+		print -P  "using config file at user request of ITED_USE_CONFIG_FILE"
+		wants_config_file="$_configdir/InvTweaks.cfg"
 	else
-		echo "configuration ok, full color supported"
+		print -P  "ITED_USE_CONFIG_FILE is zero, InvTweaks.cfg will not be included"
 	fi
-	print "initializing nano..."
-	nano $_files
-	print "cleaning up..."
-	unset IFS
-	
+    [[ $_debug == 1 ]] && print "prog name=$progname path=$progpath"
+    
+	_nanoflags=(  --syntax=invtweaksrules )
+
+	if [[ $ITED_SWAP_LAST_ENTRIES == "1" ]]; then
+		_files=(	${wants_config_file}
+				 	$_configdir/InvTweaksTree.txt
+				 	$_configdir/InvTweaksRules.txt
+					$extrafiles
+				)
+	else
+		_files=(	${wants_config_file}
+				 	$_configdir/InvTweaksRules.txt
+				 	$_configdir/InvTweaksTree.txt
+					$extrafiles
+				)
+	fi
+	if ((io_backup)); then
+		backupdir=~/.cache/ited/backups
+		if mkdir -p $backupdir; then
+			if cp --dereference $_files $backupdir; then
+				echo "made backup: ok"
+			else
+				echo "fatal error: cannot backup to $backupdir (check space, permissions, etc)"
+				exit 128
+			fi
+		else
+			echo "fatal error: cannot create backup path $backupdir (check permissions, space, etc)"
+			exit 129
+		fi
+	else
+		echo "skipping backup (no Backup key in config file, or no config file)"
+	fi
+	if [[ $1 =~ ^--?v(im)? ]]; then
+		if [[ $1 =~ n$ ]]; then
+			# VIM - CLI NORMAL
+			print -P  "using vim (normal) as requested  --vimn/-vn"
+			vim -o $_files
+		elif [[ $1 =~ g$ ]]; then
+			# VIM - GUI (GVIM)
+			print -P  "using vim (gui gtk/gnome/athena/etc) as requested --vimg/-vg"
+			gvim -o $_files
+		else
+			# VIM - TINY (MINIMAL)
+			print -P  "using vim (tiny) as requested --vim/-v"
+			vim.tiny -u /dev/null $_files
+		fi
+	else
+
+		print -Pn "%F{124}detecting nano settings...%f"
+		for x in ~/.nanorc /etc/nanorc /var/nano/nanorc ~/.config/nano/nanorc ~/.config/nanorc ~/.config/.nanorc; do
+			if [[ -r $x ]]; then
+				_conf="$x"
+				break
+			fi
+		done
+		[[ -r "$_conf" ]] || print -P  "%F{red}fatal: cannot locate nano config file -- please create one or reinstall nano%f"
+		if ! grep -q invtweaksrules\.nanorc $_conf; then
+			print -P  "invtweaksrules syntax rule not installed, color support will be limited!"
+		else
+			print -P  "configuration ok, full color supported"
+		fi
+		print "initializing nano..."
+		nano $_nanoflags $_files
+		print "cleaning up..."
+		unset IFS
+	fi
 }
 
 # entry point
+print -P  "starting main program handoff"
 main "$@"
+print -P  "returned ok"
 
-
+## INI EXAMPLE
+## REMOVE THE LEADING "## " (no quotes) FROM ITS TEXT BELOW TO USE CONFIG FILE
+## BE SURE TO NAME IT $HOME/.itedrc (ie, for root its /root/.itedrc))
+##-----BEGIN INI EXAMPLE (NEXT LINE IS LINE 1 (or 0 with base0))--------------
+## #
+## # .itedrc
+## # ited configuration
+## #
+## # Sections denoted with [section_name] on a line
+## # values are either in the form of 'FILENAME"
+## # or "NAME=VALUE"
+## # Valid Sections:
+## #	Name			Contains Items of Type		Description
+## #	[Files]			FILENAME					Files to load also, after the last file but before the configuration
+## #												there is no limit to how many you can load, they can even be empty but must be readable plain text files.
+## #	[Config]		NAME=VALUE					Most options go here
+## #
+## # Options (for Config)
+## #
+## #	Name			Value(s) Accepted			Description
+## #	UseConfig		1 or 0						if 1, loads the InvTweaks.cfg file also (changes value of wantsconfig internally)
+## #	Backup			1 or 0						copy files opened to ~/.cache/ited-backups first
+##
+##
+## [Config]
+## UseConfig=0
+## Backup=1
+##
+##
+## [Files]
+## /home/osirisgothra/in/config/moditems.txt
+#----------END EXAMPLE FILE--------_CUT_-----------------------------_CUT_----------------_CUT_------------------------
diff --git a/eso/ubin-local/loadavg b/eso/ubin-local/loadavg
--- a/eso/ubin-local/loadavg
+++ b/eso/ubin-local/loadavg
@@ -102,6 +102,7 @@ zmodload zsh/mathfunc
 maxf=5
 
 if ! o=( $(getopt -l help -o hqaf:la -n ${0}(:t) -- $@) ); then
+
 	exit $?
 fi
 function help()
@@ -188,6 +189,10 @@ if [[ -n $average ]]; then
 	# when using fields we will average out the fields used only
 
 	if [[ -n $fields ]]; then
+		if ((fields < 1)); then
+			echo "error: field value must be 1, 2, or 3!"
+			exit 125
+		fi
 		# ensure a is a floating point type so its values get divided properly
 		# this method also allows multiple fields just like before, in this case
 		# specifying a field more than once will give extra weight to that field
diff --git a/eso/ubin-local/quietly b/eso/ubin-local/quietly
--- a/eso/ubin-local/quietly
+++ b/eso/ubin-local/quietly
@@ -212,12 +212,31 @@ else
 		target=none
 	done
 	if [[ $target == none ]]; then
+		# TODO: get rid of echos where not needed
 		echo "no target was found - aborted"
 		if [[ -x /usr/lib/command-not-found ]]; then
 			echo "you have a cnf-handler, passing this on to ulcnf..."
-			/usr/lib/command-not-found "$linkbase"
+			if (( `loadavg -a -f1` > 1.50 )); then
+				echo "system load is higher than normal so cnf will not be shown"
+			else
+				/usr/lib/command-not-found "$linkbase"
+			fi
 		else
 			echo "no cnf handlers found (or click here: http://www.google.com/search?q=get+$linkbase)"
+		fi
+		if [[ -L "$0" ]]; then
+			print -P "%F{red}quietly%F{blue}<->%F{green}$0%f is %Bnot%b valid\n%F{green}remove its link now %f[%F{green}y/[n]%f]%B?%b"
+			read -sq
+			case $REPLY in
+				y|Y)	printf " YES\nremoving $0 in 4 seconds..."; sleep 4
+						cp "$0" "/tmp/last_quietlylink_removed.q"
+						rm "$0" && echo "ok" || echo "failed, remove it manually!"
+						;;
+				n|N)	printf "NO\nskipping removal\n"
+						;;
+			esac
+		else
+			print -P "%F{red}quietly%F{blue}<->%F{green}$0%f is %Bnot%b valid, but is also a %Uphysical%u file, you must delete it yourself for safety reasons"
 		fi
 		exit err_fnf
 	else
diff --git a/eso/ubin-local/surf b/eso/ubin-local/surf
--- a/eso/ubin-local/surf
+++ b/eso/ubin-local/surf
@@ -1,106 +1,68 @@
-#!/bin/bash
+#!/bin/zsh
+# rewrite of ~/bin/surf
+# for zsh, a bit smarter but more hardwired
+# also, no need to make cache or anything its faster now
+# requires also the program 'qfork' (distributed with this script)
 
-# try to find it quickly in usual locations
-if [[ -x /usr/bin/surf ]] && ! diff "$BASH_SOURCE" "/usr/bin/surf"; then
-	if [[ $SURF_NO_LOOK_IN_USUAL_SPOT -eq 1 ]]; then
-		echo "warn: found in usual spot but SURF_NO_LOOK_IN_USUAL_SPOT=1 is set. however, if it is the only result it might be chosen anyway."
-	else
-		echo "short-circuting: surf found in usual spot, using it"
-		echo "(disable this by defining SURF_NO_LOOK_IN_USUAL_SPOT=1)"
-		exec /usr/bin/surf "$@" || exit $?
-	fi
+# check for qfork
+if ! [[ $(qfork --marco) == "pollo" ]]; then
+	echo "qfork is not installed, it is REQUIRED"
+	exit 127
 fi
 
+# set debug=1 to show debug messages, or debug=0 to not
+# use the DEBUG_SURF if using env
+declare -gi debug=0
+# overrides above, dont change this!
+# second incantation "0" is not the same as "" and unset, it MUST exist to be considered!!
+[[ $DEBUG_SURF == 1 ]] && debug=1
+[[ $DEBUG_SURF == 0 ]] && debug=0
+decho() { [[ $debug == 1 ]] && echo "$(date): $@"; }
 
-TTY="$(tty)"
-
-function kdialog()
-{
-	# only use kdialog IF we dont have a tty (like running from an X based launcher)
-	if [[ $TTY =~ (pts|tty) ]]; then
-		case $1 in
-			--msgbox)	shift; printf "[44m[1m[ $* ][0m\n";;
-			*) printf "kdlg: $*\n";;
-		esac
-	else
-		command kdialog "$@"
-	fi
-}
-
-
-function errexit()
-{
-	kdialog --msgbox "cant find surf anywhere! $*"
-	echo "CANT FIND SURF!"
-	exit 1
-}
-
-if [[ -r ~/.config/surflocation ]]; then
-	SURFCACHE=~/.config/surflocation
+# resolve our script to physical path for later
+decho -ne "resolving $0 to "
+declare -g __this=`readlink -e "$0"`
+declare -g __expected_mimetype="application/x-executable"
+if [[ $__this == $0 ]]; then
+	decho "[same script, ok]"
 else
-	SURFCACHE="/tmp/surfloc.cached"
+	decho "$__this (fully dereferenced link)"
 fi
 
-if [[ ! -r "$SURFCACHE" ]]; then
-	kdialog --msgbox "I am going to look for surf for you, and save the location!"
-	echo "$SURFCACHE not found, looking for surf..."
-	# note: "nlocate" does NOT search for just files (stupid right?) so we have to check em ourselves
-	declare -a files=( `locate */surf` )
-	declare -i index=0
-	echo
-	echo "Heres the list: ${files[@]}"
-	echo
-	while true; do
-		nextfile=${files[index]}
-		echo "now checking: $nextfile - to see if it is a file/executable/nondirectory"
-		if [[ -f "$nextfile" ]] && [[ -x "$nextfile" ]] && [[ ! -d "$nextfile" ]]; then
-			if diff "$nextfile" "$BASH_SOURCE"; then
-				echo "$nextfile is THIS script, obviously not what we are looking for"
+declare -ga prefixes=( / /usr ~/ ./ )
+declare -ga minfixes=( " " "local" "share" "src" "src/fork" "src" "src/fork" "src/clone" ".local" ".local/share" )
+declare -ga suffixes=( /bin /surf "/" /sbin )
+for p ( $prefixes ) {
+for m ( $minfixes ) {
+for s ( $suffixes ) {
+	[[ $p == " " ]] && p=""
+	[[ $m == " " ]] && m=""
+	[[ $s == " " ]] && s=""
+
+	f="$p$m$s"
+	g="${f//\/\///}"
+	if [[ -d $g ]] && [[ -x $g/surf ]]; then
+		g="${g%/}/surf"
+		# resolve all links to their dirs so checks will test if it is the caller script
+		g=`readlink -e "$g"`
+		if [[ -d $g ]]; then
+			decho "$g is a directory"
+		else
+			decho "$g is executable, examining..."
+			if [[ $g = $__this ]]; then
+				decho "this is the currently running script, skipping"
 			else
-				if file "$nextfile" | grep ELF; then
-					echo "$nextfile verified as an ELF binary"
-					break
-				else
-					echo "$nextfile is a script (possibly a different/modified version of THIS script)"
+				__mimetype=`mimetype --output-format "%m" "$g"`
+				decho "mimetype is $__mimetype"
+				if [[ $__mimetype == $__expected_mimetype ]]; then
+					echo "found $g which is $__mimetype match, passing your arguments to it..."
+					qfork $g "$@"
+					exit $?
 				fi
 			fi
 		fi
-		let index++
-		echo "no go, going to the next one.. (number $index in the list)"
-		if [[ $index -gt "${#files[@]}" ]]; then
-			# /dev/null is guarenteed to NEVER be executable POSIX-HFS specifications
-			echo "FAILED, could NOT find one, so we have to use /dev/null to trip the checker"
-			nextfile=/dev/null
-			break
-		fi
-	done
-	SURFLOC="$nextfile"
-	if [[ ! -x "$SURFLOC" ]]; then
-		errexit
 	fi
-	kdialog --msgbox "we made it, it was found at $SURFLOC and will be stored in $SURFCACHE until the next system reboot clears the cache"
-	echo "found surf at $SURFLOC"
-	echo "recording cache to $SURFLOC"
-	echo "$SURFLOC" > "$SURFCACHE"
-else
-	SURFLOC=`cat $SURFCACHE`
-	if [[ ! -x "$SURFLOC"  || ! -f "$SURFLOC" || -d "$SURFLOC" ]]; then
-		rm -f "$SURFCACHE"
-		errexit "The cache file was found, but it pointed to somewhere that didnt execute, the cache file has been deleted, try running again to perform the initial search"
-	elif diff "$SURFLOC" "$BASH_SOURCE"; then
-		rm -f "$SURFCACHE"
-		errexit "The cache file points to this script, not okay (removing script file -- please try again)"
-	elif file "$SURFLOC" | grep ELF; then
-		echo "cached file $SURFLOC is an executable, binary file. Using it as the target file (and keeping in cache)"
-	else
-		echo "file $SURFLOC is not a binary executable, removing it (please try again!)"
-		rm -f "$SURFCACHE"
-		errexit "failed to execute any valid cache file, please start this program again to rescan!"
-	fi
-fi
-# at this point $SURFLOC will have a valid, executable location, no matter what
-# execution problems are now the problem of the binary, not us
-# our script is called 'surf' so we can safely 'exec' into it to keep
-# the expected PID when we were launched, this is required for startup
-# notification on some systems to work correctly (and monitoring apps)
-exec "$SURFLOC" "$@"
+}
+}
+}
+
diff --git a/eso/ubin-local/tg2 b/eso/ubin-local/tg2
--- a/eso/ubin-local/tg2
+++ b/eso/ubin-local/tg2
@@ -1,30 +1,24 @@
-#!/usr/bin/perl
+#!/bin/zsh
+#!/bin/bash
 #
-# FILE
-#    perltemplate-file
-#    the perltemplate-file perl script
+#    tg2
+#    thrgrep2, without using external utilities (except renice/ionice)
+#    mini
+#    esoteric projects
 #
-# PROJECT
-#    perltemplate-file-proj
-#	 project perltemplate-file-proj: container for perltemplate-file
+#    Copyright (C) 1995-2020 Gabriel Thomas Sharp
 #
-# AUTHOR / COPYRIGHT
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all of my projects can be
+#    obtained by visiting the repository:
 #
-#    Copyright (C) 2020, Gabriel Thomas Sharp
+#    <https://github.com/osirisgothra>
 #
-#    Written by Gabriel Thomas Sharp osirisgothra@larnica.(none)
-#    Latest versions of this and all of Gabriel Thomas Sharp's projects can be
-#    obtained from:
+#    Because of the global availability of github at this point, hosting
+#    any additional servers for public use no longer serves a purpose. All
+#    content is available 24/7 through github. (Thanks to GITHUB!).
 #
-#     <<projbranch>>
-#
-#    Documentation Available At:
-#
-#     <http://www.github.com/osirisgothra/perltemplate-file-proj.git>
-#
-# LICENSE
-#
-#    perltemplate-file-proj/perltemplate-file  is free software; you can redistribute it and/or modify
+#    This program is free software; you can redistribute it and/or modify
 #    it under the terms of the GNU General Public License as published by
 #    the Free Software Foundation; either version 2 of the License, or
 #    (at your option) any later version.
@@ -38,155 +32,311 @@
 #    with this program; if not, write to the Free Software Foundation, Inc.,
 #    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
-#  NOTES
+#    HISTORY
 #
-#     * TODO: move 'use' statements to top if you want to keep them**
-#    ** this feature will be added to the next version of perltemplate (hopefully)
-#   *** warnings are disabled for experimental and once because they are pretty
-#       annoying here, you might want to re-enable them for your own program
-#       to do this during testing and development.
+#     Tue 18 Aug 2020 06:43:59 AM EDT
+#            osirisgothra@ initially created this file
+#            with the original name, tg2
 #
-#  HISTORY
+#    NOTES
+#    
+#        INDEX
+#        I.    CRITICAL SECTION NOTES
+#                A.    ASYNCHRONOUS CRITICAL SECTION (CONSIDERING OTHER THREADS OR PROCESSES, EVEN OTHER USERS ON THE SYSTEM)
+#                B.  BASIC VARIABLES
+#                C.  CONSTANTS
+#                D.  OTHER DECLARATIONS
+#                
 #
-#	Mon Feb 10 10:34:21 2020
-#         osirisgothra@larnica.(none) created this file using the template generator 'perltemplate'
-#         and named it perltemplate-file for the project '<projname'.
+#        CRITICAL SECTION NOTES (no section tag, then its section A!)
 #
+#        A.    ASYNCHRONOUS CRITICAL SECTION (CONSIDERING OTHER THREADS OR PROCESSES, EVEN OTHER USERS ON THE SYSTEM)
+#            ABSTRACT: this critical section (documentation) is ironically about "critical section (threading)" dont get them mixed up!
+#            LEADNOTE: These lines should probably either be locked as a mutex somehow for the working pid/gpid:
+#                      it is at this point that the $_commpath is _assumed_ to still exist (but could easily not if target is running paralell and not stopped
+#                  possilbe solutions should be listed here, so far i have:
+#                 1) stop the process, verify it is still present, perform actions, then continue the process (probably safest)
+#                 2) use some custom utility or script+libcall (perl or python since they are usually stock) to "lock" the process in some other way or
+#                    to perform the actions with a guarentee that no timeslices will be given to the target PID (probably fastest, but not very safe)
+#                 3) check pid just before each action below (somewhat safe, somewhat slow, and not very accurate, but suprisingly preferred by other programs)
+#                 last but not least) prompt the user to do one of the above if process is not "locked" (how we would know this is not very clear, and therefore not very safe or fast)
+#                 FOR NOW: assuming after a re-check of the PID's /proc path, that it exists, and attempt actions on it
+#                  also, ionice/renice are being used as surrogates so they will have the final word on securing the process during modifications
+#                    however i wish to embed this into C or perl code eventually!!
 #
-# (created with perltemplate by Gabriel T. Sharp <osirisgothra@hotmail.com>)
+#        B    
+#  (this template+header was created using the template generator by Gabriel T. Sharp)
 #
 
-use warnings;
-use v5.18;
-use strict;
-no warnings "experimental";			# 	allow given/when/default and smartmatching without their warnings***
-no warnings "once";					# 	allow variables to be used just once without warning***
-use Path::Tiny	qw( rootdir  );						#	path("name") or Path::Tiny::rootdir->child("name")
-use Getopt::Long::Descriptive; 
-use Term::ANSIColor 4.0  qw ( colorstrip color colored uncolor coloralias :constants colorvalid :pushpop );
-use Curses::UI;
-use Path::Tiny::Ext qw (basename);
+# MODULES
+
+zmodload zsh/mathfunc
+zmodload zsh/termcap
+zmodload zsh/terminfo
+
+# OPTIONS
+
+setopt extendedglob
+setopt globassign
+setopt globdots
+setopt globsubst
+setopt kshglob
+setopt promptsubst
+setopt noxtrace
+
+# DECLARATIONS
+
+declare -g noflags=1
+declare -ga opts=( )
+declare -gA params=(    defined 1
+                        nice    -1
+                        class    none
+                        level    5
+                    )
+declare -gi quiet_level=0
+declare -g version_text="$(tput setaf 124)tg2$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
+declare -g help_text="tg2
+
+thrgrep2, without using external utilities (except renice/ionice)
+
+SYNTAX
+
+    tg2 [OPTIONS] ARGUMENT(S)
+
+OPTIONS
+
+    Expects zero or more of the following options:
+
+ Long Form    Short Form   Breif Description
+
+ --help            -h      Show this help text.
+ --version         -v      Displays license and version information, then exit.
+ --class[=]CLASS   -c      Specify ionice class (detailed below).
+ --level[=]LEVEL   -l       for classes other than idle/none, priority level from 0 to 7.
+ --nice[=]NICENESS -n       Set the nice level to a value between -20 (highest priority) to 19 (lowest).
+ --quiet           -q      Show less messages (defaults to zero).
 
 
+ARGUMENT
+
+    Expects one or more of the following arguments:
+
+    PID         A process identifier (usually a number in the 1-32767 range)
+    COMMAND     The name of a running processes command (comm under /proc)
+
+    You may omit these arguments when using '--help'
+
+GENERATED
+
+    The core of this project file was created using the template and license
+    generator v1.0 by Gabriel T Sharp <osirisgothra@hotmail.com>.
+
+LICENSE
+
+    GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
+
+"
+
+## FUNCTIONS
+
+cleanup() {
+        clear
+        echo -ne "cleaning up environment..."
+        setterm -cursor on
+        echo "finished!"
+        exit 0
+}
+setup()
+{
+        setterm -cursor off
+}
+decho() { ((TG2_DEBUG_ECHO)) && print -P -- "$@"; }
+__ionice() {
+    [[ $# -le 3 ]] && { echo "FATAL: not enough args ($#, need at least 4) in ionice func"; exit 127; }
+    _ppi=${2-0}
+    [[ $_ppi -le 1 ]] && { echo "FATAL: bad ppid in ionice func"; exit 127; }
+    _old=`ionice -p $_ppi`
+    #                          1  2          3   4             5?   6?
+    if sudo -H ionice -p $_threadid -c $params[class] -n $params[level]; then
+        _new=`ionice -p $_ppi`
+        echo "   |"
+        echo "   +------- $_old => $_new"
+    else
+        echo "pid($_ppi), ionice($_old) could not set new class/level (are you superuser/sudoer?)"
+    fi
+}
+main() {
+    # restores terminal and any other things we messed with that the user wouldnt want dumped on
+    unsetopt monitor
+
+    setup
+    trap cleanup INT TERM KILL QUIT EXIT SEGV
+    # these allow user to use CTRL+Z to suspend, without losing the cursor
+    trap "setterm -cursor on" TSTP
+    trap "setterm -cursor off" CONT
+
+    deflev=`sudo ionice`
+    # syntax: main [proccess-name] [...]
+    # be sure the params[] hash was already set prior to this call!
+    integer tot_procs=0
+    integer tot_changed=0
+    printf '[1;1H[2J'
+    for _procname_tofind; do
+        for _commpath in /proc/*/comm; do
+            
+            if [[ -r $_commpath ]]; then
+                # TODO: this is the entrance to a critical section (see CRITICAL SECTION NOTE above)
+                _proccname="$(<$_commpath)"
+                if [[ $_proccname == $_procname_tofind ]]; then
+                    _pid=$_commpath(:h)
+                    echo $_pid $_proccname
+                    #                    v--- include main pid too
+                    for _threadid in $_pid(:t) $_pid/task/*(:t); do
+                        let tot_procs++
+                        printf '[1;1H'
+                        #printf '[2K'
+                        sudo renice -n $params[nice] -p $_threadid
+                        if [[ $params[class] =~ ^(idle|none)$ ]]; then
+                            __ionice -p $_threadid -c $params[class]
+                        else
+                            __ionice -p $_threadid -c $params[class] -n $params[level]
+                        fi
+                    done
+                fi
+            else
+                # the last check for process presence ended falsely (see TODO above)
+                # this is the only checking inside the critical section, but it may be exited even after this
+                # it is for this reason it should be locked after this evaluation above passes truthfully
+                echo "info: $_commpath was ended during operation, removing from list of possible identities"
+            fi
+        done
+    done
+    echo "default class:level is currently: $deflev"
 
 
-## PATH ##
-# # creating Path::Tiny objects
-# print("for this to work, must have /tmp/foo.txt and /tmp/foo/bar.txt first, attempt will be made to create them...");
-# sleep(1);
-# my $data1 = `ls -l /`;
-# my $data2 = `ls /etc`;
-# path('/tmp/foo/bar.txt')->spew($data1);
-# path('/tmp/foo.txt')->spew($data2);
-# my $dir = path("/tmp");
-# my $foo = path("foo.txt");
-# my $subdir = $dir->child("foo");
-# my $bar = $subdir->child("bar.txt");
-# # stringifies as cleaned up path
-# my $file = path("./foo.txt");
-# say $file; # "foo.txt"
-# # reading files
-# my $guts = $file->slurp;
-# $guts = $file->slurp_utf8;
-# my @lines = $file->lines;
-# @lines = $file->lines_utf8;
-# my ($head) = $file->lines( {count => 1} );
-# my ($tail) = $file->lines( {count => -1} );
-# say "head";
-# say $head;
-# say "tail";
-# say $tail;
-# say "write data...";
-# # writing files
-# my @data = qw ( sample data );
-# $bar->spew( @data );
-# $bar->spew_utf8( @data );
-# # reading directories
-# for ( $dir->children ) { say("children: $_"); }
-# my $iter = $dir->iterator;
-# while ( my $next = $iter->() ) { say("iterated: $next"); }
-# ## PATH END ##
+}
 
-# ## GETOPT ##
-# my ($opt, $usage) = describe_options(
-#     '$0 %o <some-arg> file',
-#     [ 'no-dialog', "dont use dialog to show log",  ],
-#     [ 'no-follow',   "do not follow the log, just show it",   { default  => 79 } ],
-#     [],
-#     [ 'verbose|v',  "print extra stuff"            ],
-#     [ 'help',       "print usage message and exit" ],
-# );
-# say($usage->text), exit if $opt->help;
-# say("getopt: arguments processed: $#ARGV");
-# ## GETOPT END ##
 
-# ## ANSI* ##
-# # color
-# print color 'bold blue';
-# print "This text is bold blue.\n";
-# print color 'reset';
-# print "This text is normal.\n";
-# print colored("Yellow on magenta.", 'yellow on_magenta'), "\n";
-# print "This text is normal.\n";
-# print colored ['yellow on_magenta'], 'Yellow on magenta.', "\n";
-# print colored ['red on_bright_yellow'], 'Red on bright yellow.', "\n";
-# print colored ['bright_red on_black'], 'Bright red on black.', "\n";
-# print "\n";
-# # Strip all color escape sequences.
-# print colorstrip '\e[1mThis is bold\e[0m', "\n";
-# # Determine whether a color is valid.
-# my $valid = colorvalid('blue bold', 'on_magenta');
-# print "Color string is ", $valid ? "valid\n" : "invalid\n";
-# # Create new aliases for colors.
-# coloralias('alert', 'red');
-# print "Alert is ", coloralias('alert'), "\n";
-# print colored("This is in red.", 'alert'), "\n";
-# print BOLD, BLUE, "This text is in bold blue.\n", RESET;
-# # localized
-# {
-# 	local $Term::ANSIColor::AUTORESET = 1;
-# 	print BOLD BLUE "This text is in bold blue.\n";
-# 	print "This text is normal.\n";
-# }
-# print PUSHCOLOR RED ON_GREEN "This text is red on green.\n";
-# print PUSHCOLOR BRIGHT_BLUE "This text is bright blue on green.\n";
-# print RESET BRIGHT_BLUE "This text is just bright blue.\n";
-# print POPCOLOR "Back to red on green.\n";
-# print LOCALCOLOR GREEN ON_BLUE "This text is green on blue.\n";
-# # localized 
-# print "This text is red on green.\n";
-# {
-# 	local $Term::ANSIColor::AUTOLOCAL = 1;
-# 	print ON_BLUE "This text is red on blue.\n";
-# 	print "This text is red on green.\n";
-# }
-# print POPCOLOR "Back to whatever we started as.\n";
-# ## END ANSI ## 
+echo() {
+    if [[ $quiet_level -gt 0 ]]; then
+        return 127
+    else
+        builtin echo "$@"
+    fi
+}
 
-# ## CURSES ##
-# say("curses: entering setting");
-# my $debug = 0;  #1=yes 0=no
-# my $cui = Curses::UI->new( -color_support => 1, -clear_on_exit => 1, -debug => $debug, ); # this is where we gloss over setting up all the widgets and data structures + start the event loop
-# $cui->dialog("Hello, world!");
-# my $yes = $cui->dialog( 	-message => "Hello, world?", -buttons => ["yes","no"], -values  => [1,0], -title   => "Question", );
-# if ($yes) {	chomp(); } # whatever
-# $cui->error("It's the end of the\n"."world as we know it!");
-# $file = $cui->filebrowser(	-path => "/tmp", -show_hidden => 1, );
-# # Filebrowser will return undef if no file was selected.
-# if (defined $file) {    unless (open F, ">$file") {	print F "Hello, world!\n"; close F; } else { $cui->error(qq(Error on writing to "$file":\n$!)); }     }
-# $cui->status("Saying hello to the world..."); 		# code for saying "Hello, world!"
-# $cui->status("Saying goodbye to the world..."); 	# code for saying "Goodbye, world!"
-# $cui->nostatus;
-# $cui->progress( 	-max => 10, 	-message => "Counting 10 seconds...", );
-# for my $second (0..10) {	$cui->setprogress($second); sleep 1; }
-# $cui->noprogress;
-#            my @menu = (
-#                  { -label => 'File',
-#                    -submenu => [
-#                   { -label => 'Exit      ^Q', -value => \&exit_dialog  }
-#                                ]
-#                   },
-#                );
-# #$cui->addmenu(\@menu);
-# $cui->mainloop;
-# ## END CURSES ##
+# LINE-ERROR support
+# allows for more specific error codes that are somewhat useful
+setopt aliases
+error()
+{
+    local code=${1-254}
+    local floc=${2-global}
+    local desc=${3-undefined}
+    local noexit=${3-0}
+    local body
+    printf -v body "%s %%F{red}%%Berror(%s:%%I%d%%i): %s %%U(recoverable=%d)%%u%%f%%b" "$(date)" $code $desc $noexit
+
+}
+
+## MAIN PROGRAM
+
+if opts=( `getopt -n $0 -o hvqc:l:n: -l class:,level:,nice:,help,version,quiet -- "$@"` ); then
+    eval set -- "${opts[@]}"
+    while [[ $# -ge 0 ]]; do
+        curopt=$1
+        nextopt=${2-none}
+        shift
+        # handle --options and -o ptions here
+        case $curopt in
+            --class|-c)    params[class]=$nextopt; shift;;
+            --level|-l) params[level]=$nextopt; shift;;
+            --nice|-n) params[nice]=$nextopt; shift;;
+            --help|-h)    echo "$help_text"; exit 127;;
+            --version|-v) echo "$version_text"; exit 127;;
+            --quiet|-q) let quiet_level++;;
+            --) decho "done with options"; break;;
+            *)    decho "handling option: $curopt (next:$nextopt)";;
+        esac
+    done
+    # validate/setup variables
+    declare -g progname=$0(:t)
+    declare -g progpath=$0
+    declare -g progdir=$0(:h)k
+    [[ $params[class] == nil ]] && [[ $params[nice] == nil ]] && error 128 "must specify either a class or nice level"
+    [[ $params[class] != nil ]] && [[ $params[class] != idle ]] && [[ $params[level] == nil ]] && error 129
+
+    main "$@"
+else
+    error 130 "while parsing options got code $? from getopt"
+fi
+
+# BEGIN TEMPORARY STUFF
+#
+# DOC FOR NICE/RENICE/IONICE
+#
+#    NICE (new process only)
+#
+#        Usage: nice [OPTION] [COMMAND [ARG]...]
+#        Run COMMAND with an adjusted niceness, which affects process scheduling.
+#        With no COMMAND, print the current niceness.  Niceness values range from
+#        -20 (most favorable to the process) to 19 (least favorable to the process).
+#
+#        Mandatory arguments to long options are mandatory for short options too.
+#          -n, --adjustment=N   add integer N to the niceness (default 10)
+#              --help     display this help and exit
+#              --version  output version information and exit
+#
+#        NOTE: your shell may have its own version of nice, which usually supersedes
+#        the version described here.  Please refer to your shell's documentation
+#        for details about the options it supports.
+#
+#        GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
+#        Full documentation at: <https://www.gnu.org/software/coreutils/nice>
+#        or available locally via: info '(coreutils) nice invocation'
+#
+#    IONICE
+#
+#        Usage:
+#         ionice [options] -p <pid>...
+#         ionice [options] -P <pgid>...
+#         ionice [options] -u <uid>...
+#         ionice [options] <command>
+#
+#        Show or change the I/O-scheduling class and priority of a process.
+#
+#        Options:
+#         -c, --class <class>    name or number of scheduling class,
+#                                  0: none, 1: realtime, 2: best-effort, 3: idle
+#         -n, --classdata <num>  priority (0..7) in the specified scheduling class,
+#                                  only for the realtime and best-effort classes
+#         -p, --pid <pid>...     act on these already running processes
+#         -P, --pgid <pgrp>...   act on already running processes in these groups
+#         -t, --ignore           ignore failures
+#         -u, --uid <uid>...     act on already running processes owned by these users
+#
+#         -h, --help             display this help
+#         -V, --version          display version
+#
+#        For more details see ionice(1).
+#
+#    RENICE    (existing processes only)
+#
+#        Usage:
+#         renice [-n] <priority> [-p|--pid] <pid>...
+#         renice [-n] <priority>  -g|--pgrp <pgid>...
+#         renice [-n] <priority>  -u|--user <user>...
+#
+#        Alter the priority of running processes.
+#
+#        Options:
+#         -n, --priority <num>   specify the nice increment value
+#         -p, --pid <id>         interpret argument as process ID (default)
+#         -g, --pgrp <id>        interpret argument as process group ID
+#         -u, --user <name>|<id> interpret argument as username or user ID
+#
+#         -h, --help             display this help
+#         -V, --version          display version
+#
+#        For more details see renice(1).
+#
diff --git a/eso/ubin-local/xy b/eso/ubin-local/xy
--- a/eso/ubin-local/xy
+++ b/eso/ubin-local/xy
@@ -1,4 +1,210 @@
-#!/bin/bash 
-# vim:filetype=sh
+#!/bin/zsh
+#
+#    xy
+#    learn x in y downloader/displayer in CLI
+#    mini
+#    eso/ubin-local
+#
+#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all of my projects can be
+#    obtained by visiting the repository: 
+#
+#    <https://github.com/osirisgothra>
+#
+#    Because of the global availability of github at this point, hosting
+#    any additional servers for public use no longer serves a purpose. All
+#    content is available 24/7 through github. (Thanks to GITHUB!).
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#    HISTORY
+#
+#	 Tue 13 Oct 2020 11:35:00 AM EDT
+#            osirisgothra@ initially created this file
+#            with the original name, xy
+#
+# TARGET NOTES
+#
+# 	EXECUTIVE STATE CHANGES
+#		marking single existing file executable
+#			- mode of 'xy' changed to u+rwx/og+rx.. []
+#		completed (0)
+# 	ARGUMENTUAL ANALYSIS
+#       remaining arguments:
+#			no arguments to list
+#       disposition:
+#			4 were used during execution of template
+#   		0 were extra and/or unexpected
+# 	TEMPLATE SUMMARY OF GENERATION
+#	     outcome: good
+#	     errors: 0
+# 	FINAL NOTE
+#	     template program under renovation
+#        you should REMOVE the TARGET NOTES section once youve reviewed this!
+#		 (Tue 13 Oct 2020 11:35:00 AM EDT): osirisgothra ignored the final note and left this behind for
+#		           the user(s) to see, how embarassed I am for the author!
+#
+#
+#  (this template+header was created using the template generator by Gabriel T. Sharp)
+#
 
-(( GET learnxinyminutes.com/docs/"$*" | html2text | perl -wne 'print unless /Further Reading:/ .. /Dhankhar/' ) 2>/dev/null)
+
+
+
+# Get Options from Command Line for xy 
+
+declare -ga opts
+declare -gi quiet_level=0
+declare -g version_text="$(tput setaf 124)xy$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
+declare -g help_text="xy
+learn x in y downloader/displayer in CLI
+
+SYNTAX
+
+	xy [OPTIONS] ARGUMENTS
+
+OPTIONS
+	--text -t   force plain-text processing in all cases
+    --html -H   force conversion to HTML in most cases* (overrides CONVERTER environment variable)
+    --file -f   use the file link in the page, if any (some pages may not have this, so it is not the default)
+	--help -h	show this help text
+ --version -v   display version information and exit (also shows license info)
+   --quiet -q   increase quiet level by one (quiet level is always zero if left alone)
+
+ARGUMENTS
+
+	STRING		A readable string, it must not contain any unreprintable characters.
+				this string will be used to locate the document (ie, 'perl')
+*NOTES
+
+  1) The HTML conversion is only possible when the text2html(1) binary is installed
+     on the target host. If it is not installed, CONVERTER=txt will be forced
+     even if you have -H and/or have set CONVERTER yourself. Usually this is
+     installed on most mid-sized and modern linux builds.
+  2) BEAR IN MIND that if you use the -f option, the string you provide must
+     be the filename, not the language identifier. For example, perl works for
+     looking up the perl page, but to see the code page you would need to
+     specify 'learnperl.pl'. To get a complete list of files on the server
+     you should visit their website (see below).
+
+PORTING
+
+	No information about porting has been submitted as of yet.
+
+EXAMPLE USAGE
+
+	show perl page: xy perl
+	show python page: xy python3
+		and so on...
+
+LEARNXINY
+
+	The author of this tool has no affiliation with the website. The content
+	from their website is subject to THEIR LICENSES, and you must agree to
+    them in order to download and view the content provided by them.
+
+	Credit for ALL the documents are listed on the website, and none of them
+    are me, so please give credit where it is due and adhere to their licenses
+	and rules where and when they apply. Those rules and licenses can be found
+    on the webpage(s) listed on each page or on the homepage, if not specified
+    otherwise. Lastly, if you are unsure, please write them to find out what
+    you can and cant do with this documentation. Err on caution!
+
+	Visit http://www.learnxiny.com for a list of available languages!
+
+LICENSE
+
+	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
+
+"
+extraprefix=""
+echo() {
+	if [[ $quiet_level -gt 0 ]]; then
+		return 127
+	else
+		builtin echo "$@"
+	fi
+}
+
+if opts=( `getopt -n $0 -o Htfhvq -l text,html,file,help,version,quiet -- "$@"` ); then
+	eval set -- "${opts[@]}"
+	while [[ $# -ge 0 ]]; do
+		curopt=$1
+		nextopt=${2-none}
+		shift
+		# handle --options and -o ptions here
+		case $curopt in
+			--html|-m) CONVERTER=html;;
+			--text|-t) CONVERTER=txt;;
+			--help|-h)	echo "$help_text"; exit 127;;
+			--version|-v) echo "$version_text"; exit 127;;
+			--quiet|-q) let quiet_level++;;
+			--file|-f) extraprefix="files/";;	# get from files instead
+			--) echo "done with options"; break;;
+			*)	echo "handling option: $curopt (next:$nextopt)";;
+		esac
+	done
+else
+	echo "error, code is $?, exiting with fail"
+fi
+
+# functions
+
+function ghtml()
+{
+	wget --no-check-certificate https://www.learnxinyminutes.com/docs/${extraprefix}"$*" -o /tmp/last-xy-$USER.log -O-; 
+}
+function iconverter()
+{
+	# use plain text if dealing with -f
+	if [[ -n $extraprefix ]]; then
+		CONVERTER=txt
+	fi
+
+	# useless use of cat i know: it is a placeholder value
+	# until another processor is replaced with it, if ever needed
+	# this makes converting in the future much easier:
+	case ${CONVERTER-html} in
+		html)	[[ -x /usr/bin/html2text ]] && 		{
+
+					/usr/bin/html2text
+
+													} || {
+
+					/usr/bin/cat
+
+				}
+				;;
+		*)		/usr/bin/cat;;
+	esac
+
+}
+function ipager()
+{
+	iconverter | less -P "?f%f .?m(%T %i of %m) .?ltlines %lt-%lb?L/%L. ."
+}
+
+## codestate: $@ populated with plain words supplied by user
+
+# deal with each query at a time
+for lang; do
+	ghtml $lang | ipager
+done
+
+
+
+
