online update

diff --git a/eso/ubin-local/nvidia-tweak b/eso/ubin-local/nvidia-tweak
--- a/eso/ubin-local/nvidia-tweak
+++ b/eso/ubin-local/nvidia-tweak
@@ -68,15 +68,34 @@ declare -a NVSC=( "$NVSP" "-a" )
 
 assign_attribute()
 {
-	if "${NVSC[@]}" "${1}=${2}" &> /dev/null; then
+	if "${NVSC[@]}" "${1}=${2}" &> /tmp/nvidia-tweak.log; then
 		echo "set $1 to $2"
 	else
-		echo "error: attribute $1 not accepted for value $2, locked out ($?)"
+		echo -ne "set $1 to $2 failed? :::"
+		cat /tmp/nvidia-tweak.log
+		rm $_
 	fi
 }
 
 # SCRIPTSTART
 
-assign_attribute OpenGLImageSettings $IMAGE_HI_SPEED
+echo -ne "loading configuration and sending to X driver..."
+nvidia-settings -l && echo "ok" || echo "(possibly failed? error code is $?)"
+
+# Visual Only Settings
 assign_attribute DigitalVibrance $ROBUST_VIBRANCE
+
+# GPU/GL Optimizations for Better Speed
 assign_attribute GPUPowerMizerMode $GPU_MAX_SPEED
+assign_attribute OpenGLImageSettings $IMAGE_HI_SPEED
+# assign_attribute GLThreadedOptimizations 1
+# assign_attribute GLSingleThreaded 0
+# assign_attribute GLAllowUnofficialProtocol 1
+# assign_attribute GLAllowFXAAUsage 0
+# assign_attribute GLIgnoreGLSLExtReqs 1
+# assign_attribute GLShaderDiskCachePath "/home/osirisgothra/.cache/shaders"
+# assign_attribute GLShaderDiskCache 1
+
+
+
+echo "You can edit the settings by typing 'nano $0'"
diff --git a/eso/ubin-local/pwp b/eso/ubin-local/pwp
--- a/eso/ubin-local/pwp
+++ b/eso/ubin-local/pwp
@@ -76,6 +76,17 @@
 #			 used on all github/osirisgothra projects, but it isnt, and since
 #			 has decided that rah template (random-as-hell template) is the
 #			 best of all his templates in which to use!
+#	 Mon 06 Apr 2020 09:46:56 PM EDT - Corona Update
+#			 osirisgothra@larnica says:
+#				- the computer got sick, it was a good oppurtunity to reinstall linux
+#				  and test to make this program out-of-the-box handle any problems
+#				  the results are disaster but the outcome is, now pwp can tell you
+#				  what is needed to be installed to run
+#					- out-of-the-box you will need to install: hsetroot, wmname, zsh, perl so i can work
+#					- you will need to make a ~/.pwp-wallpaper-dirs file with the names of the dirs where you wallpapers are
+#						this nifty file also allows for any globbing zsh is capable of(!)
+#			added some support for: KDE(4 and 5)	XFCE4, ICEWM, I3, DWM, GXDWM, but not enlightenment because because thats why
+#			(the eliteist programmer groups of enlightenment users usually write their own crap anyway right?)
 #
 # TARGET NOTES
 #
@@ -85,12 +96,230 @@
 #
 #  (this header was created using the template generator by Gabriel T. Sharp)
 #
-# PRE-RUN CHECKS
 
+# single instance filter (sif)
+# mode can be wait or exit (exit if you plan to spam hotkeys, wait if you have slower system)
+# wait should not be used in situations where more than 2 could be started 
+sif_mode=exit
+declare -ga running_pwps=( $(pgrep pwp) )
+declare -gi	msgshown=0
+while [[ $#running_pwps -gt 1 ]]; do
+	running_pwps=( $(pgrep pwp) )
+	echo "we are $$"
+	if [[ $#running_pwps -gt 1 ]]; then
+		case $sif_mode in
+			exit)	echo "there are too many instances running: $#running_pwps"
+					echo "sif-mode is set internally to 'exit', no further processing by this instance will be performed"
+					exit $#running_pwps;;
+			wait)	if [[ $msgshown == 0 ]]; then
+						echo "there are too many instances running: $#running_pwps"
+						echo "waiting for others to finish (interval $wait_ival)"
+						msgshown=1
+					fi
+					printf "."
+					sleep $(( $#running_pwps * wait_ival ))
+					;;
+		esac
+	else
+		break
+	fi
+done
+echo "okay result is: $#running_pwps running, with $running_pwps[1] as the pid (we are $$)"
+
+
+
+# Fade in/out controllers
+# when fademax is set to AUTO then the current gamma will be used!
+# warning, if you tie pwp to a hotkey, and more than one script runs without seeing each other
+# the gamma could get nerfed and you could end up not seeing (or seeing too much of) brightness on your screen!
+# pre-run checks will try to determine if it is a lone instance but it is not fool proof.
+# remember, if fademax is set to AUTO, it needs to be a string, not a float!
+float fadeautogammalevel=${$(xgamma 2>&1)[3]/,/}
+float fademax=1.2
+float fademin=-1.0
+# 0.1 = normal rate (single step)
+# 1 = 10 steps
+# 2 = 20 steps
+# 5   50 step, 10=100 steps
+# steps are not sleep delayed, just used
+# no time guarenteed could even be instant-check video  vendor info for speeds
+if [[ $fademax == "AUTO" ]]; then
+	unset fademax
+	float fademax=$fadeautogammalevel
+	if [[ $fademax -le $fademin ]]; then
+		echo "cannot continue, fademax should be greater than fademin and it is not (max=[$fademax] is not greater than min=[$fademin])"
+	fi
+fi
+	
+# frate: frame rate
+#       
+float rateout=0.25
+float ratein=0.25
+
+fadeout()
+{
+	float fval=$fademax;
+	for ((fval=fademax;fval>fademin;fval=fval-rateout)); do
+		xgamma -gamma $fval &> /dev/null
+	done
+}
+fadein()
+{
+	float fval=$fademin;
+	for ((fval=$fademin;fval<$fademax;fval=fval+$ratein)); do
+		xgamma -gamma $fval &> /dev/null
+	done	
+}
+if pgrep -root &> /dev/null && pgrep X &> /dev/null; then
+	echo "X is running"
+	if [[ $DISPLAY =~ ':[.0-9]+' ]]; then
+		echo "Found a DISPLAY ($DISPLAY) to connect to"
+	else
+		echo "But no valid DISPLAY was found :("
+		# CHOICE: could attach to :0 or :0.0 but that seems to be
+		# overstepping since we have no idea the intentions of the call
+		# and the chance that this could be exploited somehow
+		echo "exiting"
+		exit 127
+	fi
+else
+	echo "failed: not currently running an X window manager"
+fi
+
+if tty -s; then
+	echo "fading will not be done as we are in a terminal"
+else
+	echo "fade routines installed (we are not in a terminal and thus performed graphically"
+	fadeout
+	trap fadein EXIT
+fi
+
+# PRE RUN CHECKS
+
+# pre-run binary check
+#  these are required binaries that we simply have to have for the program to run at all
+#  for the most part, even an sh program can be used to gracefully check system and find
+#  out what the user needs to install (but then exits after that)
+corecheck()
+{
+	eval "$1" > /dev/null 2> /dev/null
+    [ $? -eq 127 ] && return 1
+    return 0
+}
+coretest()
+{
+	if corecheck $1; then
+		echo "[$1: ok]"
+	else
+		echo "[$1: missing!]: The command \"$1\" is a required program that is not accessible, please make this available to pwp!"
+		if test -x /usr/lib/command-not-found; then
+			echo "extra cnf info available:"
+			/usr/lib/command-not-found "$1"
+		fi
+		exit $[ 200 + $2 ]
+	fi
+}
+coretests()
+{
+	echo "performing core tests..."
+	# this command returns 0 with zsh only, 127 in other shells
+	if ! zmodload > /dev/null; then
+		echo "[zsh: missing!]: zsh is required to run this script, make sure you have properly linked zsh to a real zsh binary (must support loading of modules)"
+		exit 200
+	else
+		echo "[zsh: ok]"
+	fi
+	# we are zsh, but we need to check for the remaining items
+	x=0
+	for t in which hsetroot grep cp rm mktemp truncate xfconf-query; do
+		x=$(( $x + 1 ))
+		coretest $t $x
+	done
+	# at this point we can use which to find perl
+	if which perl 2> /dev/null; then
+		echo "perl [ok]"
+	else
+		echo "perl is required to run this program, please install perl (version 5.2+ reccomended, but most any perl should work)"
+		exit 199
+	fi
+
+}
+corechecks()
+{
+
+	# we only warn about the programs here
+	x=0
+	for t in xtitle wmname icewmbg; do
+		if ! which $t > /dev/null 2> /dev/null; then
+			echo "[31;mmissing program '${t}' some parts of the program may be impaired, you should install it[0m"
+			sleep 0.5
+		fi
+	done
+	# now check for missing required pathname(s)
+	if test -d ~/.cache/pwp; then
+		echo "user's cache directory found"
+		echo "verifying directory permissions..."
+		if chmod 700 ~/.cache/pwp; then
+			echo "verified, directory is private to user only (nobody else can see your wallpaper cache, that does not mean they cannot see your wallpaper files, unless they reside within this directory!)"
+		else
+			r=$?
+			[ $r -eq 127 ] && echo "127 error code: commonly means the binary is missing or unavailable/unusable for some reason"
+			echo "fail: cannot guarentee private directory (-rwx------) for ~/.cache/pwp (*chmod gave $r)"
+			echo "directories containing private data should not be group-visible, please check  your permissions for ~/.cache before proceeding"
+			exit 197
+		fi
+
+	else
+		echo "cant find user cache directory, creating it..."
+		if mkdir --mode=700 -p ~/.cache/pwp; then
+			echo "user's cache directory newly created (~/.cache/pwp)"
+		else
+			echo "fatal 198:$?: cannot create cache directory in ~/.cache/pwp (mkdir failed, check above for any explanations, mkdir returned $?)"
+			exit 198
+		fi
+	fi
+	if [[ -r ~/.pwp-wallpaper-dirs ]]; then
+		declare -gxa pwp_image_dirs=( )
+		echo "verified: ~/.pwp-wallpaper-dirs exists!"
+		# allows all the goodness of zsh globbing to be used in your ~/.pwp-wallpaper-dirs!
+		setopt localoptions
+		setopt extendedglob
+		setopt kshglob
+		setopt globassign
+
+		for x in $(<~/.pwp-wallpaper-dirs); do
+			# reprocess so that globbing gets a crack at it (supports in-file zsh extended globbing)
+			eval x=$x
+			if [[ -d $x ]]; then
+				echo "adding $x as a wallpaper dir!"
+				pwp_image_dirs+="$x"
+			else
+				echo "skipping $x, it doesnt exist"
+			fi
+		done
+		if [[ $#pwp_image_dirs -gt 0 ]]; then
+			echo "there are $#pwp_image_dirs valid path(s) in your .pwp-wallpaper-dirs file"
+		else
+			echo "ERROR: no readable directories in ~/.pwp-wallpaper-dirs, please add some"
+			exit 196
+		fi
+	else
+		echo "ERROR: you dont have a ~/.pwp-wallpaper-dirs file yet, please make one and on each line a directory on your system that has wallpapers in it. The most common place is /usr/share/wallpapers."
+		exit 197
+	fi
+
+	echo "checks all passed enough to start the pwp program..."
+}
+coretests
+corechecks
+
+# now we can safely enter zsh mode
+emulate zsh
+### end critical checks
 [[ $options[restricted] == on ]] && { "fail: must not be run with rzsh or zsh in restricted mode"; exit 127; }
 [[ $options[interactive] == on ]] && { "fail: do not run interactivly using source or dot(.) instead run as an executable"; exit 126; }
 [[ $DISPLAY =~ ^:[0-9][0-9]?(.[0-9][0-9]?)?$ ]] || { "fail: cant find proper DISPLAY, needs to run in X"; exit 125; }
-[[ "$XDG_CURRENT_DESKTOP" == "" ]] || ( [[ $KDE_FULL_SESSION != true ]] &&  { "fail: x desktop manager present, you must use it instead to set wallpapers!"; exit 124; } )
+# NEW: removed b/c adding support for window managers too: [[ "$XDG_CURRENT_DESKTOP" == "" ]] || ( [[ $KDE_FULL_SESSION != true ]] &&  { "fail: x desktop manager present, you must use it instead to set wallpapers!"; exit 124; } )
 # SHELL OPTIONS
 zmodload zsh/mathfunc
 setopt interactivecomments
@@ -104,7 +333,6 @@ declare -gx pwp_hsr_binary="hsetroot"
 declare -gx pwp_icewm_binary="icewmbg"
 declare -gx pwp_pgrep_binary="pgrep"
 declare -gx pwp_icewmbg_pid="$(command $pwp_pgrep_binary -x${icewmbg_process_age: 0:1} icewmbg || echo '-1')"
-declare -gx pwp_image_dirs=( /usr/share/wallpapers /b/way/usr/share/wallpapers /b/usr/share/wallpapers )
 declare -gx pwp_images=( )
 declare -gA pwp_presets=(
 	'Havelock Blue' '#3399FF'										# 0
@@ -130,16 +358,11 @@ declare -gA pwp_presets=(
 # FUNCTIONS
 function getimages()
 {
-	if [[ -s /tmp/imgcache ]]; then
+	if [[ -s ~/.cache/pwp/imgcache ]]; then
 		seecho "found cache, using it (remove it to refresh)"
-		#cat /tmp/imgcache | while read r; do
-		#	pwp_images+=( "$r" )
-		#done
-		#IFS=$'\n'
 		pwp_images=( )
-		#unset IFS
 	else
-		truncate -s0 /tmp/imgcache
+		truncate -s0 ~/.cache/pwp/imgcache
 		local id fn
 		for id in $pwp_image_dirs; do
 			if [[ -d $id ]]; then
@@ -151,7 +374,7 @@ function getimages()
 					pwp_images+=( $fn )
 					# to list, and to cache
 					# zero length or nonexistent
-					echo "$fn" >> /tmp/imgcache
+					echo "$fn" >> ~/.cache/pwp/imgcache
 				done
 			else
 				seecho "warning: configured directory, \"$id\" is currently not reachable by me"
@@ -162,10 +385,10 @@ function getimages()
 
 function getimage()
 {
-	if [[ -s /tmp/imgcache ]]; then
-		maxi="${$(wc -l /tmp/imgcache)% *}"
+	if [[ -s ~/.cache/pwp/imgcache ]]; then
+		maxi="${$(wc -l ~/.cache/pwp/imgcache)% *}"
 		iidx="$(( int(floor(rand48($SECONDS) * maxi)) ))"
-		sed -n "${iidx}p" /tmp/imgcache | tr -d '\n'
+		sed -n "${iidx}p" ~/.cache/pwp/imgcache | tr -d '\n'
 	else
 	local -i imin=1 imax=$#pwp_images iidx=${1-1}
 	if [[ $1 == "rand" ]]; then
@@ -245,16 +468,38 @@ function translate_tint()
 }
 function show_image()
 {
+	# TODO: a rewrite needs done to account for new window manager behaviors in 2017-2020, this was written originally in 2015
 	TINTCOLOR="$(translate_tint ${1-\#909090})"
 	echo "tint: $TINTCOLOR"
 	image_name="$(get_image_name)"
-	echo "image: $image_name"
+	if [[ -r $image_name ]]; then
+		echo "image exists"
+	else
+		echo "image not found (cache is invalid, removing it)"
+		echo "please re-run the program again so cache can be regenerated"
+		exit 195
+	fi
 	hsetroot -cover "$image_name" -tint "$TINTCOLOR" -write ~/.config/pwp.jpg
-	if [[ $KDE_FULL_SESSION == true ]]; then
+	# keep image history < 100 lines long to prevent huge file from forming
+	if [[ -r ~/.config/image-history.txt ]]; then
+		cat ~/.config/image-history.txt | tail -n100 > /tmp/ih
+		cp /tmp/ih ~/.config/image-history.txt
+	fi
+	echo "$image_name" >> ~/.config/image-history.txt
+	echo "image: '$image_name'"
+	if [[ $XDG_CURRENT_DESKTOP == XFCE ]]; then
+		print -P "\n%F{27}%BRUNNING IN XFCE COMPATIBILITY MODE (see NOTES: XFCECOMPAT)\n%f%b"
+		rm -f ~/.cache/pwp/^README
+		dest_img=~/.cache/pwp/$(mktemp -u pwp_xfceXXXXXXXXXXXXXX.jpg)
+		cp -f ~/.config/pwp.jpg $dest_img
+		# change: updated to account for any changes in 2020 (Xubuntu 20.04 compliant) --use older versions of pwp for older xubuntu versions
+		xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorHDMI-0/workspace0/last-image -s "$dest_img"
+	elif [[ $KDE_FULL_SESSION == true ]] || [[ $XDG_CURRENT_DESKTOP == KDE ]]; then
 		print -P "\n%F{27}%BRUNNING IN KDE COMPATIBILITY MODE (see NOTES: KDECOMPAT)\n%f%b"
-		rm /var/cache/pwp/^README
-		cp ~/.config/pwp.jpg /var/cache/pwp/$(mktemp -u pwpXXXXXXXXXXXXX.jpg) -f
-		echo "be sure to use /var/cache/pwp as your wallpaper slideshow to be compatible with kde!"
+		rm -f ~/.cache/pwp/^README
+		cp ~/.config/pwp.jpg ~/.cache/pwp/$(mktemp -u pwp_kdeXXXXXXXXXXXXX.jpg) -f
+		echo "be sure to use ~/.cache/pwp as your wallpaper slideshow to be compatible with kde!"
+
 	fi
 
 }
diff --git a/eso/ubin-local/quietly b/eso/ubin-local/quietly
--- a/eso/ubin-local/quietly
+++ b/eso/ubin-local/quietly
@@ -34,6 +34,9 @@ emulate zsh
 #    with this program; if not, write to the Free Software Foundation, Inc.,
 #    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
+#	NOTES
+#	- (setting color vars): fhicolor (first high color, 16, is usually black)
+#
 #	HOW TO USE
 #
 #	 Usage is simple, just link a name of your preferred privledged program
@@ -66,13 +69,44 @@ emulate zsh
 #
 #
 
-#TODO: add interactive setup for adding links
 
+
+# direct use call
+
+if ( [[ $1 == "-q" ]] || [[ $1 == "--quietly" ]] ) && [[ $0 =~ quietly ]]; then
+	shift
+	echo "trying to run [$@] quietly..."
+	if [[ -x $1 ]] && [[ ${1: 0:2} != "./" ]]; then
+		echo "in same dir ($1) without a './', adding one..."
+		cmd="./$1"; shift
+	else
+		cmd="$1"; shift
+	fi
+	set -- "$cmd" "$@"
+	"$@" &> /dev/null &
+	job=$jobstates[$#jobstates]
+	echo "job: $job"
+	disown %
+	return $?
+fi
 
 setopt aliases
+setopt interactivecomments
+setopt kshglob
+setopt extendedglob
+setopt globassign
+setopt nullglob
+
+zmodload zsh/zutil 		\
+		 zsh/termcap 	\
+		 zsh/terminfo 	\
+		 zsh/pcre
+
+
 disable hash
 disable true
 disable false
+
 
 alias char='typeset -gg'
 alias int='typeset -gi'
@@ -82,36 +116,13 @@ alias bool='typeset -gi'
 alias echo='print -P'
 alias necho='print -Pn'
 alias rint='typeset -gir'
-alias color='integer lastcolor_fg; integer lastcolor_bg; () {
-	case $1 in
-		fg)	echo $lastcolor_fg;;
-		bg) echo $lastcolor_bg;;
-	  last) echo $lastcolor_fg $lastcolor_bg;;
-	     *)	integer fg=7
-			integer bg=0
-			fg=${1-7} bg={2-0}
-			if [[ $fg =~ , ]]; then
-				fg=${1%%,*} bg=${1##*,}
-			fi
-			if [[ $fg == $bg ]]; then
-				echo "warning: color spec must not be same for both back/foreground colors, setting to default"
-				tput sgr0
-			else
-				tput setaf $fg
-				tput setab $bg
-				lastcolor_bg=$bg
-				lastcolor_fg=$fg
-			fi;;
-	esac
-}'
-# syntax: color [fg] [bg] | color [fg,bg]
 
 rint false=0
 rint true=1
-# fhicolor (first high color, 16, is usually black)
 int black=0 red=1 green=2 yellow=3 blue=4 pink=5 cyan=6 white=7 lite=8
-int lblack=$[lite+0] litered=$[lite+1] litegreen=$[lite+2] liteyellow=$[lite+3] liteblue=$[lite+4] litepink=$[lite+5] litecyan=$[lite+6] litewhite=$[lite+7] fhicolor=$[lite+8]
-
+int liteblack=$[lite+0] litered=$[lite+1] litegreen=$[lite+2] liteyellow=$[lite+3] liteblue=$[lite+4] litepink=$[lite+5] litecyan=$[lite+6] litewhite=$[lite+7] fhicolor=$[lite+8]
+integer lastcolor_fg=$white
+integer lastcolor_bg=$black
 char linkname="$0"
 char linkbase=$(basename "$0")
 char scriptname=$(realpath "$0")
@@ -120,36 +131,70 @@ char scriptbase=$(basename $scriptname)
  int err_disqualified=0+err_base
  int err_fnf=1+err_base
  int err_abort=2+err_base
-bool use_debug=true
+bool use_debug=false
 bool use_messages=false
+bool use_logfile=false
 char flagfile="$HOME/.config/quietly/flags/donotdebug.flg"
+char logfile="quietly-output_user-${USER}_tty-${TTY//\//_}.log"
+
+# this pass will assure us the system is in an agreeable state
+rm $(mktemp) || { echo "fatal: cannot write to tmp (out of disk/memory resources? low system privileges?)"; exit 254; }
+[[ $(systemctl is-system-running) != running ]] && { echo "warning: system reports a degraded state (usually means awaiting a reboot)!"; }
+
+# to log or not to log
+if [[ $use_logfile != false ]]; then
+	touch $logfile || { echo "error: logging to $logfile could not be performed, logging can not happen, messages will be dumped to /dev/null!"; logfile="/dev/null"; }
+	if [[ $use_messages != false ]]; then
+		echo "logging enabled: $logfile"
+	fi
+else
+	# disable logging, we will use /dev/null if it so happens to need it
+	logfile="/dev/null"
+fi
 
 # flagfile (usually ~/.config/quietly/flags/donotdebug.flg) overrides all and makes truely quiet
-[[ -r $flagfile ]] && use_debug=false && use_messages=false
+[[ $linkname =~ quietly ]] || { [[ -r $flagfile ]] && use_debug=false && use_messages=false; }
+
+[[ $use_debug -ge 1 ]] && echo "usedebug=$use_debug (false=$false)"
 
 if ((use_debug == false)); then
-	echo() { : ; }
+	if [[ $use_messages != false ]]; then
+		echo "entering quiet state"
+	fi
+	#exec &> $logfile
 elif ((use_debug == true)); then
-	color $litered,$blue
-	echo "warn: $0 is running in DEBUG mode right now, you must disable this inside the script or execute 'mkdir -pf $flagfile' to make a flag dirent"
-	:
+	#color $litered,$blue
+	echo "warn: $0 is running in DEBUG mode right now, you must disable this inside"
+	echo "the script or execute 'mkdir -pf $flagfile' to make a flag (as a directory"
+	echo "not a empty file)."
 else
 	echo "fail: use_debug must be either true or false, not ${use_debug-NO_VALUE}"
 	echo "remedy this, and restart"
 	exit err_abort
 fi
-
-
-
 echo "linkname (base=$linkbase) is $linkname"
 echo "scriptname (base=$scriptbase) is $scriptname"
-
-
 if [[ $linkbase == $scriptbase ]]; then
-	echo "script and link are same, usually means you either"
-	echo "1) copied file instead of linking, 2) ran $scriptbase directly"
-	echo "this program can only be run from a symbolic link"
-	echo "program state: disqualified for linking"
+print <<EXPLANATION_END
+
+    That is an error!
+
+	script and link are same, usually means you either:
+
+	    1) copied file instead of linking
+	    2) ran $scriptbase directly
+
+
+	this program can only be run from a symbolic link unless:
+
+	    1) you supply special arguments to run directly some-program:
+	       syntax: quietly -q some-program program-args
+	       syntax: quietly --quietly some-program program-args
+	    2) modify the program itself
+
+	program state: disqualified for linking or forking
+EXPLANATION_END
+
 	exit err_disqualified
 else
 	echo "searching for a binary named $linkbase"
@@ -168,6 +213,12 @@ else
 	done
 	if [[ $target == none ]]; then
 		echo "no target was found - aborted"
+		if [[ -x /usr/lib/command-not-found ]]; then
+			echo "you have a cnf-handler, passing this on to ulcnf..."
+			/usr/lib/command-not-found "$linkbase"
+		else
+			echo "no cnf handlers found (or click here: http://www.google.com/search?q=get+$linkbase)"
+		fi
 		exit err_fnf
 	else
 		echo "found target: $target - attempting $ma on this ($ma \"$target $@\")"
diff --git a/eso/ubin-local/template b/eso/ubin-local/template
--- a/eso/ubin-local/template
+++ b/eso/ubin-local/template
@@ -171,9 +171,99 @@ $TARGET_NOTES
 #
 #  (this template+header was created using the template generator by Gabriel T. Sharp)
 #
+
+
+
+
+# Get Options from Command Line for $1 
+
+declare -ga opts
+declare -gi quiet_level=0
+declare -g version_text="\$(tput setaf 124)$1\$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
+declare -g help_text="$1
+$2
+
+SYNTAX
+
+	$1 [OPTIONS] ARGUMENTS
+
+OPTIONS
+	--help -h	show this help text
+ --version -v   display version information and exit (also shows license info)
+   --quiet -q   increase quiet level by one (quiet level is always zero if left alone)
+
+ARGUMENTS
+
+	FILENAME	A filename that must exist or be writable by the current user.
+	PATHNAME	A relative or absolute path that must exist or be creatable.
+	STRING		A readable string, it must not contain any unreprintable characters.
+	NUMBER		An integer, usually between -32767 and 32767.
+	BOOLEAN		A true/false value, represented as 0 for false, and any other value for true.
+	FLOAT		A floating point single or double precision value, it is precise down to about 5 ot 6 decimal places.
+	ENG			Scientific notation, expressed in powers (3x10^4 is written as 3.4)
+	DEG			Like GRAD/RAD, but expressed in degrees (hours, minutes, seconds) so 3 5'5\" is written as \"3.5.5\" 
+
+
+LICENSE
+
+	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'
+
+"
+
+echo() {
+	if [[ \$quiet_level -gt 0 ]]; then
+		return 127
+	else
+		builtin echo "\$@"
+	fi
+}
+
+if opts=( \`getopt -n \$0 -o hvq -l help,version,quiet -- "\$@"\` ); then
+	eval set -- "\${opts[@]}"
+	while [[ \$# -ge 0 ]]; do
+		curopt=\$1
+		nextopt=\${2-none}
+		shift
+		# handle --options and -o ptions here
+		case \$curopt in
+			--help|-h)	echo "\$help_text"; exit 127;;
+			--version|-v) echo "\$version_text"; exit 127;;
+			--quiet|-q) let quiet_level++;;
+			--) echo "done with options"; break;;
+			*)	echo "handling option: \$curopt (next:\$nextopt)";;
+		esac	
+	done
+	for arg; do
+		# verify/handle non-option arguments
+		case \$arg in
+			*)	echo "handling argument: \$arg";;
+		esac
+	done		
+	
+else
+	echo "error, code is \$?, exiting with fail"
+fi
+
+
+
+
 MY_EXTREME_END_OF_FILE
 
 
 echo "#	template output completed (code=$([[ $? -ne 0 ]] && echo $? || echo 'OK(ERROR_NONE)' ))\n#\n#"
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 
 
diff --git a/eso/ubin-local/thrgrep b/eso/ubin-local/thrgrep
--- a/eso/ubin-local/thrgrep
+++ b/eso/ubin-local/thrgrep
@@ -1,78 +1,219 @@
 #!/bin/zsh
-MAXINT=32767
-docloc="/usr/share/doc/paradisim/mini/ubin-local/thrgrep"
-presetconfig="$HOME/.thrgreppresetrc"
-# adhere to this comment either inline or during execution!
-! [[ -r ~/.iamosirisgothra ]] && { echo "
-# NB: not intended for release of any kind use at own risk, or not at all! (ctrl+break aborts) you will have to read code to disable this message if you are not me
-"; sleep 15; }
-# NB: new argument, do we:
-#    1) allow preset lines such as:
-#					 "mystuffavg" "allavg"
-#    2) or have a special operator like:
-#					 alias mystuffavg=allavg
-#				or	alias mystuffavg allavg
-#				or  allavg [definitions] "aliases:testavg,[otheraliasnames]"
-#	problem being in 1) confusion whether the preset is a process name or not
-#	and in 2) another type of syntax to check, that basically doesnt do
-#	anything special or new (except resolves ambiguity).
-#	at this time, the only way it can be done is to use a "singular list"
-#	to disambiguate it from a non-preset or process name. This can be written
-#	one of two different ways:
-#						"mystuffavg"  ",allavg"
-#	or (preferred) 		"mystuffavg"	"allavg,"
 #
-#	the second one is preferred because the operator is in the back which
-#   keeps it from obstructing the name from view, and also acts as a placeholder
-#   for new items, should they be added (this is actually an idiom used by many
-#	mid and hi-level languages, where lists or hashes [aka dictionaries] are used).
-#	# NB: much argumenting about if (or not) bash->zsh was 'worth it', i wrote out
-# this lengthy evaluation to put this topic to bed.
-# CHANGED: arrays from bash format ( declare -gxA VARNAME=( [keyname]="value" )
-#                   to zsh format: ( declare -gxA VARNAME=( "keyname" "value" )#
-# have been converted and then also the ini file updated, and tested 
-# the meta feature was never in the bash version (is why we went to zsh)
-# the meta feature makes use of parameter flags (zsh only) and prevents the
-# need of manipulating IFS (saving, checking, setting, resetting)
-# the risks of going to zsh were far less than the risks of staying with bash
-# draft risks:
-# bash risks: possibly incompatible because of newer versions (0%)
-#             syntax problems (5%)  inferior syntax methods (30%)
-#             execution time and redundant code (10%)
-#             syntax reviewing confusion (10%)
-#			  user not having bash (0%)  conversion of code (%0)
-#			  overall: 55%
-# zsh risks:  user not having zsh (5%)   conversion of code (1%)
-#			  syntax reviewing confusion (5%)
-#			  overhead due to underuse on the system (2%)
-#			  overall: 13%
-# calculated risks: (draft is for observation and reference only, 
-#                    not for calculation!)
-# risk ---------------:---BASH---:---ZSH---:
-# incompatible version:    0%         1%
-#   conversion of code:   25%         5%
-#   syntax workarounds:   20%         0%
-#script execution time:    0%        15%
-#  reviewing confusion:   10%         8%
-#    language overhead:    2%        20%
-# user missing program:    0%        10%
-# -overall percentage:----[57%]------[59%]
-# -average----------------[8.1%]     [8.4%]
-# -largest risk-----------[25%]------[20%]
-# -integrated risk--------[30.0]     [29.1]
-# -overall gain in using zsh: [0.9] (9%)
-# -integrated "worth-it" percentage: [0.65] (65% gain in positive features and effects)
-#declare -gxA BUILTIN_PRESETS=( [rtfast]="-12 realtime 2" [rtgood]="-14 realtime 4"
-#							 [normal]="0 best-effort 5" [lazy]="12 idle 0" 
-#							 [javafast]="java -14 realtime 5"
-#							 [xorg]="Xorg -14 realtime 2"  )
-# yes this is sugar, pure sugar, and will be moved to another document once
-# this document is in the tree and has a place for older version(s)
-# *if this happened already you are looking at an older branch!!*
-# now, no more complaining, yes its worth it!
+#    thrgrep
+#    programs to NICE, CPUMASK, SECONTEXT, and IOPRIORITY, rolled into one
+#    mini/eso/ubin-local
+#    local esoteric projects/scripts/etc
+#
+# LICENSE, SUPPORT & AUTHOR INFORMATION
+#
+#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
+#
+#    Written by Gabriel T. Sharp <21shariria@gmail.com>
+#    Latest versions of this and all of my projects can be
+#    obtained by visiting the repository: 
+#
+#    <https://github.com/osirisgothra>
+#
+#    Because of the global availability of github at this point, hosting
+#    any additional servers for public use no longer serves a purpose. All
+#    content is available 24/7 through github. (Thanks to GITHUB!).
+#
+#    This program is free software; you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation; either version 2 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License along
+#    with this program; if not, write to the Free Software Foundation, Inc.,
+#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
+#
+#  HISTORY
+#
+#	 Sun 14 Jun 2020 07:17:29 PM EDT
+#            osirisgothra@ initially created this file
+#            with the original name, thrgrep
+#
+#  SCRIPT COMMENTS
+#
+#		     As a practice and a matter of pedantic ethics, use this section to 
+#		outline changes, bugs, notes, etc. You need only reference the location 
+#       of or, preferably, block description or name. Don't use line numbers as 
+#	    those will/may change often! You can, alternatively, use a count (for a
+#		example: "next 4 lines" is a valid location as long as its also has ref
+#		to block description..
+#
+#	SCRIPT BLOCK or LINE DESC	|	DESCRIPTION
+#	============================|=============================================
+#   ENDOFFILE, UNDER "FOOTNOTES"|  USED TO STORE LENGTHY DESCRIPTIONS
+#								|  do NOT store index for it here, though!
+#	STARTOFFILE, HERE			|  added template, use for short comments only
+#
+#   ==========================================================================  
+#	
+#
+#  TARGET NOTES
+#
+# 	EXECUTIVE STATE CHANGES
+#		marking single existing file executable
+#			- mode of 'thrgrep' changed to u+rwx/og+rx.. []
+#		completed (errors: 0)
+#
+# 	ARGUMENTUAL ANALYSIS
+#       remaining arguments:
+#			0 arguments, with 0 error argument(s)
+#       disposition:
+#			4 were used during execution of template
+#   		0 were extra/unexpected error(s)
+#
+# 	TEMPLATE SUMMARY OF GENERATION
+#	 final outcome: good
+#     total errors: 0
+#
+# 	FINAL NOTES
+#		 (Sun 14 Jun 2020 07:17:29 PM EDT): osirisgothra reammended the target results 
+#
+#  (this template+header was created using the template generator by Gabriel T. Sharp)
+#
+#	template output completed (code=OK(ERROR_NONE))
+#
+#
+
+
+
+declare -gi MAXINT=32767
+declare -g docloc="/usr/share/doc/paradisim/mini/ubin-local/thrgrep"
+declare -g presetconfig="$HOME/.thrgreppresetrc"
+
+! [[ -r ~/.iamosirisgothra ]] && { echo "\n NB: not intended for release of any kind use at own risk, or not at all! (ctrl+break aborts) you will have to read code to disable this message if you are not me \n"; sleep 15; }
+
+# zmodules required 
+
+zmodload zsh/terminfo 
+zmodload zsh/mathfunc
+
+# store original tty caller
 otty=$(tty)
+# restore terminal setup (keyboard mainly)
 stty sane
-unset_state="$(uuidgen)"
+
+
+
+declare -g unset_state="$(uuidgen)"
+
+
+# do not change these unless you know what you are doing and understand the risks in doing so:
+# they do not affect the system once thrgrep is completed, it disappears anyway. This just helps
+# this process complete a bit faster. Multiple self calls will not trip this as per checking var.
+#	self_nice		niceness of thrgrep script
+#	self_class		io class (idle, realtime, best-effort, none)
+#	self_class_level	(0-7 or just 0 for idle and none)
+#	self_thrgrep_threshold	system load is at or lower, will not self thrgrep (-1 means disable and never use, 255 means disable and always use)
+#
+#
+declare -gi self_nice=-16
+declare -g self_class=realtime
+declare -g self_class_level=2
+declare -gF self_thrgrep_threshold=255
+declare -gF self_load=${$(</proc/loadavg)[1]}
+declare -gi maxstep=2
+declare -gi gstart=17
+declare -gi del=15
+
+cecho()
+{
+	# dont use the first 16 colors, or the 16 grays at the end
+	# (only use "chroma-vibrant" colors)
+	dir=${RANDOM: 0:1}
+	let del--
+	if [[ $del -le 0 ]]; then
+		del=${RANDOM: 0:2}
+	
+		if [[ $dir -ge 5 ]]; then
+			dir=6
+		else
+			dir=-6
+		fi
+	fi
+
+	let gstart+=$(( dir / sin(del) ))
+	if [[ $gstart -ge 230 ]]; then
+		gstart=23
+	elif [[ $gstart -le 16 ]]; then
+		gstart=223
+	fi
+
+	case $# in
+		0) 	echo "ERROR:NO_STRING_GIVEN(f=$0 l=$LINENO)"
+			return
+			;;
+		1) 	start=$gstart
+		   	step=4
+			[[ $step -ge $maxstep ]] && step=$maxstep
+		   	str=$1
+			;;
+		*)	start=$1
+			step=$2
+			str=$3
+			;;
+	esac
+
+	cur=$start
+	for ((x=0;x<$#str;x++)); do		
+		ch=${str: x:1}
+		c $cur
+		let cur+=$step
+		printf "%s" "$ch"
+	done
+	
+}
+c() { echoti setaf ${1-7}; [[ $# -gt 1 ]] && { echoti setab ${2}; shift 2; if [[ $# -gt 0 ]]; then echoti $@; fi; }; }
+
+# tests (comment these out)
+# first incantation of cecho/c
+#cecho 39 5 "the quick brown fox: jumped over, the; 123456789 lazy / d0gs!?"
+# second incantation (random)
+#cecho "the quick brown fox: jumped over, the; 123456789 lazy / d0gs!?"
+
+echo() {
+	case $# in
+	1)	cecho "$@"; builtin echo "";;
+	*)	builtin echo "$@";;
+	esac
+}
+
+
+if [[ $THRGREP_CHANGED_MY_PRI != 1 ]]; then
+	if ( [[ $self_load -le $self_thrgrep_threshold  ]] && [[ $self_thrgrep_threshold -le 254 ]] ) || [[ $self_thrgrep_threshold -le -1 ]]; then
+		if [[ $self_thrgrep_threshold -le -1 ]]; then
+			echo "skipping self threshold (its hard-disabled in the script: $0)"
+		else
+			echo "skipping self threshold because threshold is $self_thrgrep_threshold and load is $self_load"
+		fi
+	else
+		if [[ $self_thrgrep_threshold -ge 255 ]]; then
+			echo "setting self priority (it is hard coded in the script: $0)"
+		else
+			echo "setting self priority (to survive a high load ($self_load, greater than the $self_thrgrep_threshold limit) situation)..."
+		fi
+		echo "***beginning self priority***"
+		export THRGREP_CHANGED_MY_PRI=1
+		tg_name=${0##*/}
+		"$0" "$tg_name" -16 realtime 2
+		r=$? ps=$pipestatus
+		echo "***self priority setting ends***"
+		echo "self I/O and NICE setting completed (errors=$r, pipestatus=$ps ($#ps in pipeline))"
+	fi
+else
+	echo "skipping self threshold because: threshold delegation has already executed and we are it (tasking $$ to adjust ${PPID}'s level)"
+fi	
+
+
 assert()
 {
 	# syntax: assert(directive,value) (works for all but developer tool(s) below)
@@ -204,7 +345,7 @@ local function debug()
 	#completely transparent if not enabled, let all status codes
 	#fall through the cracks!
 	if ((tg_debug_enable)); then
-		printf "debug($SECONDS,$PWD,$?,$pipestatus): $*"
+		cecho "debug($SECONDS,$PWD,$?,$pipestatus): $*"
 	fi
 }
 assert()
@@ -426,7 +567,8 @@ fi
 std_out="/dev/stdout"
 err_out="/dev/null"
 
-for THREADID in "${THREADS[@]}"; do
+( for THREADID in "${THREADS[@]}"; do
+	
 	case $# in
 		0)	# display only
 			echo "$THREADID"
@@ -434,7 +576,7 @@ for THREADID in "${THREADS[@]}"; do
 		1)	# renice only
 #			[[ $1 =~ ^-?[0-9]+$ ]] || die "bad nice level value: $1"
 #			[[ $THREADID =~ ^[0-9]+$ ]] || die "thread id not legal (numeric decimal integers only): $THREADID"
-			$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out
+			$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out 
 			;;
 		2)	# renice | besteffort-prio
 			$pfx renice -n $1 -p $THREADID 2>$err_out 1>$std_out
@@ -453,5 +595,13 @@ for THREADID in "${THREADS[@]}"; do
 			break
 			;;
 	esac
-done
+
+done ) | while read r; do
+			echo "$r"
+		done
+
+exit $?
+#################################### /\F    N   S/\ #####################################################
+#### DO NOT PLACE CODE BELOW HERE ##/  \O T/\O E/  \### END OF PROGRAM ########## KEEP ABOVE HERE #######
+####################################    \O/  \T/    #####################################################
 
diff --git a/eso/ubin-local/xclip b/eso/ubin-local/xclip
--- a/eso/ubin-local/xclip
+++ b/eso/ubin-local/xclip
@@ -1,5 +1,8 @@
 #!/bin/zsh
 
+# never change this
+myuuid=7a3118cc-17fa-47d4-900a-b96ad749c032
+
 # may need to change it
 debugging=0
 
@@ -12,8 +15,28 @@ else 				\
 	decho() { return $?; }
 }					\
 
-xclip_bin="/usr/bin/xclip"
-[[ -x $xclip_bin ]] || { echo "error: xclip dir not set right, edit it first (passing rest to xclip on path would be dangerous)"; exit 127; }
+# get script path *OR* fall back on first executable xclip and assume
+myname="$0"
+[[ -x $myname ]] || myname=`which xclip`
+if ! grep -q $myuuid $myname; then
+	echo "script identity self-check failed, please check for corruption or tampered script file"
+	exit 128
+fi
+for xclip_bin  in `which -a xclip` /usr/bin/xclip; do
+	if [[ $xclip_bin != $myname ]]; then
+		break
+	fi
+	xclip_bin=""
+done
+if [[ -x $xclip_bin ]]; then
+	unset myname
+else
+	echo "xclip is not installed, please install it before using this shim"
+	echo "command not found: xclip"
+	echo "getting libcnf response in background..."
+	( test -x /usr/lib/command-not-found && $_ xclip ) & disown
+	exit 127
+fi
 
 # NB: /usr/bin/xclip uses sub-standard argument parsing that is not part of the modern CLI standard on linux:
 # note: xclip help is accessed by -help not --help! (b/c some may see it as a bug) furthermore all xclip flags are -singledashed not --doubledashed
