added templates for snip aka snip-it and did the summer esoteric commission of small binaries and scripts

diff --git a/eso/ubin-local/pwp b/eso/ubin-local/pwp
--- a/eso/ubin-local/pwp
+++ b/eso/ubin-local/pwp
@@ -68,6 +68,7 @@
 #			is a restricted mode program, nothing like that is done here.
 #
 # HISTORY
+#    
 #    Thu Oct 18 14:12:11 EDT 2018
 #          osirisgothra@larnica created this file, adding the header
 #          with the name 'pick-wallpaper', which would later be changed
@@ -102,7 +103,29 @@
 #						this nifty file also allows for any globbing zsh is capable of(!)
 #			added some support for: KDE(4 and 5)	XFCE4, ICEWM, I3, DWM, GXDWM, but not enlightenment because because thats why
 #			(the eliteist programmer groups of enlightenment users usually write their own crap anyway right?)
-#
+#    Mon 28 Jun 2021 02:24:26 PM EDT
+#           osirisgothra@larnica made some changes, confined many messages to result() and resultend() to neaten up
+#           and takes advantage of zsh prompt sequences.
+#           bugfixes:   - pwp_image_dirs      now recognizes comments
+#                                             no longer assumes IFS to include '\n' it is not explicit
+#                                             now supports inline comments, too
+#                       - messages            put many annoying messages away into result()
+#           features:   + finished adding the XFCE compatibility feature
+#                         XFCE is now fully supported, and supports multiple-desktop wallpapers
+#                         you can use a PWP_NOWORKSPACE=1 and then set WORKSPACE_NUM=number to
+#                         force a specific desktop to get its wallpaper chosen, or, you can just
+#                         run it while on the desktop you want to change and it will be autodetected,
+#                         this new feature has the downside of manual cache clearout, but will never be
+#                         more than the number of desktops times the average file size. These files are
+#                         kept in ~/.cache/pwp and can be removed easily.
+#                         KEEP IN MIND, that if you go to another window manager, you will lose your wallpapers
+#                         unless you write-protect them, in which case they will be locked in. I might add a feature
+#                         to preserve these files, but at this time, this is the way *I* want it to work, so I
+#                         am keeping that as an intended feature/side-effect.
+#                       + self aware testing, succeeded - pwp will not step on its own toes
+#                       + probably-the-last-update update, planning on moving it to a perl application in the future
+#                         but that is just a minor thought at this point nothing definite is planned.
+
 # TARGET NOTES
 #
 #   WARNING -- WRITTEN FOR RESTRICTED SHELL MODE#
@@ -118,9 +141,14 @@
 # single instance filter (sif)
 # mode can be wait or exit (exit if you plan to spam hotkeys, wait if you have slower system)
 # wait should not be used in situations where more than 2 could be started 
+
+
 sif_mode=exit
 declare -ga running_pwps=( $(pgrep pwp) )
 declare -gi	msgshown=0
+# show some extra messages 
+declare -gi pwpdebug=0
+
 while [[ $#running_pwps -gt 1 ]]; do
 	running_pwps=( $(pgrep pwp) )
 	echo "we are $$"
@@ -224,14 +252,33 @@ corecheck()
     [ $? -eq 127 ] && return 1
     return 0
 }
+result()
+{
+    print -Pn "%F{234}%B[%b%F{199}$1%F{234}%B=%b"
+    if [[ $2 =~ "(was found|ok|present|success|good|OK|okay|true|yes)" ]]; then
+        print -Pn "%F{120}$2"
+    elif [[ $2 =~ "(missing|fail|no|false|not found|present|error|fatal|critical)" ]]; then
+        print -Pn "%F{160}$2"
+    else
+        print -Pn "%F{202}$2"
+    fi
+    print -Pn "%B%F{234}]%f%b "
+    if [[ $# -eq 3 ]]; then
+        echo "\n\t($3)\n\n"
+    fi
+}
+resultend() 
+{ 
+    print -Pn "%f%b\n"; 
+}
 coretest()
 {
 	if corecheck $1; then
-		echo "[$1: ok]"
+	    result "$1" "ok"
 	else
-		echo "[$1: missing!]: The command \"$1\" is a required program that is not accessible, please make this available to pwp!"
+		result "$1" "missing -- the command \"$1\" is a required program that is not accessible, please make this available to pwp!"
 		if test -x /usr/lib/command-not-found; then
-			echo "extra cnf info available:"
+			result "$1" "extra cnf info available"
 			/usr/lib/command-not-found "$1"
 		fi
 		exit $[ 200 + $2 ]
@@ -242,10 +289,10 @@ coretests()
 	echo "performing core tests..."
 	# this command returns 0 with zsh only, 127 in other shells
 	if ! zmodload > /dev/null; then
-		echo "[zsh: missing!]: zsh is required to run this script, make sure you have properly linked zsh to a real zsh binary (must support loading of modules)"
+		result "zsh" "missing--zsh is required to run this script, make sure you have properly linked zsh to a real zsh binary (must support loading of modules)"
 		exit 200
 	else
-		echo "[zsh: ok]"
+	    result "zsh" "ok"
 	fi
 	# we are zsh, but we need to check for the remaining items
 	x=0
@@ -254,12 +301,14 @@ coretests()
 		coretest $t $x
 	done
 	# at this point we can use which to find perl
-	if which perl 2> /dev/null; then
-		echo "perl [ok]"
+	# dont use the &> just yet, until we are in zsh emulation mode
+	if which perl 1> /dev/null 2> /dev/null; then
+		result "perl" "ok"
 	else
-		echo "perl is required to run this program, please install perl (version 5.2+ reccomended, but most any perl should work)"
+		result "perl" "failed" "perl is required to run this program, please install perl (version 5.2+ reccomended, but most any perl should work)"
 		exit 199
 	fi
+	resultend
 
 }
 corechecks()
@@ -275,58 +324,83 @@ corechecks()
 	done
 	# now check for missing required pathname(s)
 	if test -d ~/.cache/pwp; then
-		echo "user's cache directory found"
-		echo "verifying directory permissions..."
+	    result "user .cache/pwp" "ok"
 		if chmod 700 ~/.cache/pwp; then
-			echo "verified, directory is private to user only (nobody else can see your wallpaper cache, that does not mean they cannot see your wallpaper files, unless they reside within this directory!)"
+		    result ".cache/pwp permissions" "ok"
 		else
 			r=$?
-			[ $r -eq 127 ] && echo "127 error code: commonly means the binary is missing or unavailable/unusable for some reason"
-			echo "fail: cannot guarentee private directory (-rwx------) for ~/.cache/pwp (*chmod gave $r)"
-			echo "directories containing private data should not be group-visible, please check  your permissions for ~/.cache before proceeding"
+			[ $r -eq 127 ] && result "permissions .cache" "failed- 127 error code: commonly means the binary is missing or unavailable/unusable for some reason"
+			result ".cache permission" "failed- cannot guarentee private directory (-rwx------) for ~/.cache/pwp (*chmod gave $r)"
+			result ".cache permission" "failed- directories containing private data should not be group-visible, please check  your permissions for ~/.cache before proceeding"
 			exit 197
 		fi
 
 	else
-		echo "cant find user cache directory, creating it..."
+		result ".cache/pwp" "missing, creating"
 		if mkdir --mode=700 -p ~/.cache/pwp; then
-			echo "user's cache directory newly created (~/.cache/pwp)"
+		    result ".cache/pwp" "created ok"
 		else
-			echo "fatal 198:$?: cannot create cache directory in ~/.cache/pwp (mkdir failed, check above for any explanations, mkdir returned $?)"
+		    result ".cache/pwp" "failed to create- 198:$?: cannot create cache directory in ~/.cache/pwp (mkdir failed, check above for any explanations, mkdir returned $?)"
 			exit 198
 		fi
 	fi
+	resultend
+	
 	if [[ -r ~/.pwp-wallpaper-dirs ]]; then
 		declare -gxa pwp_image_dirs=( )
-		echo "verified: ~/.pwp-wallpaper-dirs exists!"
+		result "~/.pwp-wallpaper-dirs" "exists"
 		# allows all the goodness of zsh globbing to be used in your ~/.pwp-wallpaper-dirs!
 		setopt localoptions
 		setopt extendedglob
 		setopt kshglob
 		setopt globassign
-
+        OLDIFS="$IFS"
+		IFS=$'\n'
 		for x in $(<~/.pwp-wallpaper-dirs); do
-			# reprocess so that globbing gets a crack at it (supports in-file zsh extended globbing)
-			eval x=$x
-			if [[ -d $x ]]; then
-				echo "adding $x as a wallpaper dir!"
-				pwp_image_dirs+="$x"
-			else
-				echo "skipping $x, it doesnt exist"
+		    if [[ $x =~ '^\s*#.*$' ]]; then
+		        ((pwpdebug)) && echo "skipping comment line: $x"
+	        else
+	            y="$x"
+	            x="${${${x%%\#*}%% }## }"
+	            ((pwpdebug)) && echo "translated '$y' to '$x' to remove comments"
+    			# reprocess so that globbing gets a crack at it (supports in-file zsh extended globbing)
+    			if [[ -n "$x" ]]; then
+        			eval x=$x
+        			if [[ -d $x ]]; then
+        			    result "$x" "was found"
+        				pwp_image_dirs+="$x"
+        			else
+        				result "$x" "missing"
+        			fi
+    			else
+    			    result "$x" "error: bad or corrupt line"
+			    fi
+			    
 			fi
 		done
+		if [[ -n "$OLDIFS" ]]; then
+		    IFS="$OLDIFS"
+	    else
+	        unset IFS
+        fi
 		if [[ $#pwp_image_dirs -gt 0 ]]; then
-			echo "there are $#pwp_image_dirs valid path(s) in your .pwp-wallpaper-dirs file"
+		    result "pwp image dir count" "$#pwp_image_dirs"
 		else
+		    result "pre-run checks" "failed"
+		    resultend
 			echo "ERROR: no readable directories in ~/.pwp-wallpaper-dirs, please add some"
 			exit 196
 		fi
 	else
+	    result "pre-run checks" "failed"
+	    resultend
 		echo "ERROR: you dont have a ~/.pwp-wallpaper-dirs file yet, please make one and on each line a directory on your system that has wallpapers in it. The most common place is /usr/share/wallpapers."
 		exit 197
 	fi
-
-	echo "checks all passed enough to start the pwp program..."
+	resultend
+	
+	result "pre-run checks" "passed ok"
+	resultend
 }
 coretests
 corechecks
@@ -513,11 +587,53 @@ function show_image()
 	echo "image: '$image_name'"
 	if [[ $XDG_CURRENT_DESKTOP == XFCE ]]; then
 		print -P "\n%F{27}%BRUNNING IN XFCE COMPATIBILITY MODE (see NOTES: XFCECOMPAT)\n%f%b"
-		rm -f ~/.cache/pwp/^README
-		dest_img=~/.cache/pwp/$(mktemp -u pwp_xfceXXXXXXXXXXXXXX.jpg)
+		eval `xprop -root -notype _NET_NUMBER_OF_DESKTOPS _NET_CURRENT_DESKTOP | tr -d ' '`
+        echo "currently running XFCE with ${_NET_NUMBER_OF_DESKTOPS-an unknown or unpollable number of} desktops"        
+        if [[ "$PWP_NOWORKSPACE" == "" ]] && [[ $_NET_CURRENT_DESKTOP -ge 0 ]] && [[ $_NET_CURRENT_DESKTOP -le $_NET_NUMBER_OF_DESKTOPS ]]; then
+            echo "assigning wallpaper to desktop $_NET_CURRENT_DESKTOP"
+            WORKSPACE_NUM=$_NET_CURRENT_DESKTOP
+        else
+            if [[ $_NET_NUMBER_OF_DESKTOPS -gt 0 ]]; then
+                echo "workspace count ok"
+            else
+                echo "truncating to 1 for number of desktops"
+                _NET_NUMBER_OF_DESKTOPS=1
+            fi
+            # must scrub WORKSPACE_NUM from the environment, so malicious intent is cancelled out
+            # passing redirects and whatnot (like a /../../../../../../etc/<somefile> would cause
+            # the file to be written there, so only numbers 0-9, with at least a single digit, and no
+            # more than 3 digits
+            if [[ "$WORKSPACE_NUM" == "" ]]; then
+                echo "cannot determine current desktop, using 0 as the default"
+                WORKSPACE_NUM=0
+            else
+                if [[ $WORKSPACE_NUM =~ '^[0-9]+$' ]]; then
+                    WORKSPACE_NUM=${WORKSPACE_NUM: -3}
+                    #use the last three digits at most, in case user used a number like '000000001' instead of just '1'
+                    echo "using $WORKSPACE_NUM as preconfigured by the environment"
+                else
+                    echo "the environment variable is set to '$WORKSPACE_NUM', which is forbidden, it must be a number!"
+                    echo "failing to desktop 0 instead..."
+                    WORKSPACE_NUM=0
+                fi
+            fi
+        fi    
+        if [[ $((WORKSPACE_NUM+1)) -gt $_NET_NUMBER_OF_DESKTOPS ]]; then
+            result "within desktop valid range" "failed - desktop $((WORKSPACE_NUM)) cannot be used, desktop $((_NET_NUMBER_OF_DESKTOPS-1)) is the highest that is available"
+            resultend
+            exit 127
+        else
+            result "within desktop valid range" "ok -- $WORKSPACE_NUM"
+        fi
+        #figure out whats needed here
+		#rm -f ~/.cache/pwp/^README
+		# must number them this way, lest they wont stay, and would disappear shortly after being cached
+		# drawback is that we cant remove these until we exit the window manager and even then it might be
+		# a bad idea -- this will have to be user discretion for deletion
+		dest_img=~/.cache/pwp/xfce4-desktop-$WORKSPACE_NUM
 		cp -f ~/.config/pwp.jpg $dest_img
 		# change: updated to account for any changes in 2020 (Xubuntu 20.04 compliant) --use older versions of pwp for older xubuntu versions
-		xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorHDMI-0/workspace0/last-image -s "$dest_img"
+		xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorHDMI-0/workspace${WORKSPACE_NUM}/last-image -s "$dest_img"
 	elif [[ $KDE_FULL_SESSION == true ]] || [[ $XDG_CURRENT_DESKTOP == KDE ]]; then
 		print -P "\n%F{27}%BRUNNING IN KDE COMPATIBILITY MODE (see NOTES: KDECOMPAT)\n%f%b"
 		rm -f ~/.cache/pwp/^README
diff --git a/eso/ubin-local/quietly b/eso/ubin-local/quietly
--- a/eso/ubin-local/quietly
+++ b/eso/ubin-local/quietly
@@ -1,7 +1,28 @@
-#!/bin/sh
+#!/bin/zsh
 # this is a childlike script, which only blips in and out, and thanks to exec(2), does supply krita with a PID
 # just a shim to run whatever krita i like the best a.t.m. (you can delete this script, its not really that important)
-right_now_i_like="/usr/local/bin/krita-4.4.1"
-#
+# uncomment the one you want
+# 4.4.1 - newer but has bugs especially with tablet
+# preferred_version="4.4.1"
+# 4.3 - more stable, however it is a compiled devel  release!clear
+declare -gA delay=( info    2       warn    1       error   3   normal  5 )
+wait() { for n { sleep $delay[$n] } }
+info() { print -P "%F{10}${*}%f"; sleep $delay[info]; }
+warn() { print -P "%F{11}${*}%f"; sleep $delay[warn]; }
+fail() { print -P "%F{9}%B${*}%f%b"; sleep $delay[error]; exit $((127 + ${3-0})); }
+preferred_version="4.3"
+preferred_path="/usr/local/bin/krita-$preferred_version"
+pp="$preferred_path"
+for item (/etc /tmp /dev /proc $HOME /usr /usr/bin /usr/local/bin /sbin /usr/sbin /var /sys /boot /poof /fart) {
+[[ -d /etc ]] || fail "unexpected system layout, $item is expected to exist!" 5 }
+[[ -w /tmp ]] || fail "cannot write to /tmp - this makes the system in an unstable state" 6
+[[ -r /proc/self/fd/0 ]] || fail "unexpected system layout - requires linux" 7
+[[ -w $HOME ]] || fail "cannot write to user home $HOME - please fix this issue and try again" 8
+[[ -r $pp ]] || fail "cannot read $pp" 9
+[[ -w $pp ]] || warn "$pp is not read-only, you should probably write protect it so it cant be compromised"
+[[ -x $pp ]] || fail "$pp not executable" 10
+[[ -s $pp ]] || fail "$pp is an empty file, probably was corrupted and truncated, check your disk for errors asap!" 11
 
-exec $right_now_i_like "$@"
+exec $preferred_path "$@"
+
+echo "failed to launch: $preferred_path (exec failed, path not found or permission/disk space issue?)"
